
package asnGenerated;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Choice ( name = "CancelArg" )
    public class CancelArg implements IASN1PreparedElement {
            
        @ASN1Element ( name = "invokeID", isOptional =  false , hasTag =  true, tag = 0 , hasDefaultValue =  false  )
    
	private InvokeID invokeID = null;
                
  
        @ASN1Null ( name = "allRequests" ) 
    
        @ASN1Element ( name = "allRequests", isOptional =  false , hasTag =  true, tag = 1 , hasDefaultValue =  false  )
    
	private org.bn.types.NullObject allRequests = null;
                
  
        
        public InvokeID getInvokeID () {
            return this.invokeID;
        }

        public boolean isInvokeIDSelected () {
            return this.invokeID != null;
        }

        private void setInvokeID (InvokeID value) {
            this.invokeID = value;
        }

        
        public void selectInvokeID (InvokeID value) {
            this.invokeID = value;
            
                    setAllRequests(null);
                            
        }

        
  
        
        public org.bn.types.NullObject getAllRequests () {
            return this.allRequests;
        }

        public boolean isAllRequestsSelected () {
            return this.allRequests != null;
        }

        private void setAllRequests (org.bn.types.NullObject value) {
            this.allRequests = value;
        }

        
        public void selectAllRequests () {
            selectAllRequests (new org.bn.types.NullObject());
	}
	
        public void selectAllRequests (org.bn.types.NullObject value) {
            this.allRequests = value;
            
                    setInvokeID(null);
                            
        }

        
  

	    public void initWithDefaults() {
	    }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(CancelArg.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }


    }
            