
package asnGenerated.v3;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Choice ( name = "BearerCapability" )
    public class BearerCapability implements IASN1PreparedElement {
            
        @ASN1Element ( name = "bearerCap", isOptional =  false , hasTag =  true, tag = 0 , hasDefaultValue =  false  )
    
	private BearerCap bearerCap = null;
                
  
        
        public BearerCap getBearerCap () {
            return this.bearerCap;
        }

        public boolean isBearerCapSelected () {
            return this.bearerCap != null;
        }

        private void setBearerCap (BearerCap value) {
            this.bearerCap = value;
        }

        
        public void selectBearerCap (BearerCap value) {
            this.bearerCap = value;
                        
        }

        
  

	    public void initWithDefaults() {
	    }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(BearerCapability.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }


    }
            