
package asnGenerated.v3;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Sequence ( name = "CallSegmentToCancel", isSet = false )
    public class CallSegmentToCancel implements IASN1PreparedElement {
            
        @ASN1Element ( name = "invokeID", isOptional =  true , hasTag =  true, tag = 0 , hasDefaultValue =  false  )
    
	private InvokeID invokeID = null;
                
  
        @ASN1Element ( name = "callSegmentID", isOptional =  true , hasTag =  true, tag = 1 , hasDefaultValue =  false  )
    
	private CallSegmentID callSegmentID = null;
                
  
        
        public InvokeID getInvokeID () {
            return this.invokeID;
        }

        
        public boolean isInvokeIDPresent () {
            return this.invokeID != null;
        }
        

        public void setInvokeID (InvokeID value) {
            this.invokeID = value;
        }
        
  
        
        public CallSegmentID getCallSegmentID () {
            return this.callSegmentID;
        }

        
        public boolean isCallSegmentIDPresent () {
            return this.callSegmentID != null;
        }
        

        public void setCallSegmentID (CallSegmentID value) {
            this.callSegmentID = value;
        }
        
  
                    
        
        public void initWithDefaults() {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(CallSegmentToCancel.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            