
package asnGenerated.v3;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Sequence ( name = "MoveLegArg", isSet = false )
    public class MoveLegArg implements IASN1PreparedElement {
            
        @ASN1Element ( name = "legIDToMove", isOptional =  false , hasTag =  true, tag = 0 , hasDefaultValue =  false  )
    
	private LegID legIDToMove = null;
                
  
        @ASN1Element ( name = "extensions", isOptional =  true , hasTag =  true, tag = 2 , hasDefaultValue =  false  )
    
	private Extensions extensions = null;
                
  
        
        public LegID getLegIDToMove () {
            return this.legIDToMove;
        }

        

        public void setLegIDToMove (LegID value) {
            this.legIDToMove = value;
        }
        
  
        
        public Extensions getExtensions () {
            return this.extensions;
        }

        
        public boolean isExtensionsPresent () {
            return this.extensions != null;
        }
        

        public void setExtensions (Extensions value) {
            this.extensions = value;
        }
        
  
                    
        
        public void initWithDefaults() {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(MoveLegArg.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            