
package asnGenerated.v3;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Sequence ( name = "PlayAnnouncementArg", isSet = false )
    public class PlayAnnouncementArg implements IASN1PreparedElement {
            
        @ASN1Element ( name = "informationToSend", isOptional =  false , hasTag =  true, tag = 0 , hasDefaultValue =  false  )
    
	private InformationToSend informationToSend = null;
                
  @ASN1Boolean( name = "" )
    
        @ASN1Element ( name = "disconnectFromIPForbidden", isOptional =  false , hasTag =  true, tag = 1 , hasDefaultValue =  true  )
    
	private Boolean disconnectFromIPForbidden = null;
                
  @ASN1Boolean( name = "" )
    
        @ASN1Element ( name = "requestAnnouncementComplete", isOptional =  false , hasTag =  true, tag = 2 , hasDefaultValue =  true  )
    
	private Boolean requestAnnouncementComplete = null;
                
  
        @ASN1Element ( name = "extensions", isOptional =  true , hasTag =  true, tag = 3 , hasDefaultValue =  false  )
    
	private ExtensionsArray extensions = null;
                
  
        
        public InformationToSend getInformationToSend () {
            return this.informationToSend;
        }

        

        public void setInformationToSend (InformationToSend value) {
            this.informationToSend = value;
        }
        
  
        
        public Boolean getDisconnectFromIPForbidden () {
            return this.disconnectFromIPForbidden;
        }

        

        public void setDisconnectFromIPForbidden (Boolean value) {
            this.disconnectFromIPForbidden = value;
        }
        
  
        
        public Boolean getRequestAnnouncementComplete () {
            return this.requestAnnouncementComplete;
        }

        

        public void setRequestAnnouncementComplete (Boolean value) {
            this.requestAnnouncementComplete = value;
        }
        
  
        
        public ExtensionsArray getExtensions () {
            return this.extensions;
        }

        
        public boolean isExtensionsPresent () {
            return this.extensions != null;
        }
        

        public void setExtensions (ExtensionsArray value) {
            this.extensions = value;
        }
        
  
                    
        
        public void initWithDefaults() {
            Boolean param_DisconnectFromIPForbidden =         
            null;
        setDisconnectFromIPForbidden(param_DisconnectFromIPForbidden);
    Boolean param_RequestAnnouncementComplete =         
            null;
        setRequestAnnouncementComplete(param_RequestAnnouncementComplete);
    
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(PlayAnnouncementArg.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            