/************************************************************************
     Name:     INAP Stack Manager Common - defines
 
     Type:     C include file
 
     Desc:     Defines required by All the Stack Manager Files

     File:     INGwSmCommon.h

     Sid:      INGwSmCommon.h 0  -  03/27/03 

     Prg:      gs,bd

************************************************************************/

#ifndef __BP_AINSMCOMMON_H__
#define __BP_AINSMCOMMON_H__

#include "Util/imOid.h"

/*
 * SSI Related defines
 */

/* INCTBD */
#define MTP2_LINK_USAPID 0
#define MTP3_LINK_LSAPID 0
#define SCTP_ENDPOINT_LSAPID 0
#define SCTP_ENDPOINT_USAPID 0
#define M3UA_ENDPOINT_SAPID 0
#define TUCL_ENDPOINT_USAPID 0
#define DOWN 1
#define ONLINE 1
#define ROUTE_NSAPID 0
#define LSN_SW_ITU 2
#define MTP3_USERPART_SAPID 0
#define M3UA_USERPART_SAPID 0
#define SCCP_USERPART_SAPID 0
#define SCCP_USERPART_SAPID_2 1
#define RTTYPE_PS 3
#define SCCP_SSN_SAPID 0
#define TCAP_SSN_USAPID 0
#define TCAP_SSN_LSAPID 0
#define SCTP_PROC_ID 51
#define MAX_PROC_IDS 2


#define BP_AIN_SM_POOL              DFLT_POOL
// DFLT_REGION (0) shall be used by stack layers and New memory region 1
// shall be used by stack manager and application layer
#define BP_AIN_SM_REGION            1
#define BP_AIN_SM_PRIOR             PRIOR0 
#define BP_AIN_SM_ROUTE             RTESPEC 
#define BP_AIN_SM_DEST_INST         0
#define BP_AIN_SM_SRC_INST          0

//set loose coupling for all layers
#define BP_AIN_SM_COUPLING          0

//Transport Types
#define TRANSPORT_TYPE_MTP      0
#define TRANSPORT_TYPE_SIGTRAN  1
#define TRANSPORT_TYPE_BOTH     2

/*
 * Define the return codes for the functions
 */

#define BP_AIN_SM_FAIL              0
#define BP_AIN_SM_OK                1
#define BP_AIN_SM_SCENARIO_COMP     2
#define BP_AIN_SM_INDEX_OVER        3
#define BP_AIN_SM_SEND_NEXT         4
#define BP_AIN_SM_INDEX_REPEAT      5


/*** Enable/Disable debug cmd related info ***/
#define LYR_TCAP      1
#define LYR_PSF_TCAP  2
#define LYR_SCCP      3
#define LYR_PSF_SCCP  4
#define LYR_M3UA      5
#define LYR_PSF_M3UA  6
#define LYR_LDF_M3UA  7
#define LYR_SCTP      8
#define LYR_TUCL      9
#define LYR_MTP3      10
#define LYR_PSF_MTP3  11
#define LYR_LDF_MTP3  12
#define LYR_MTP2      13
#define LYR_RELAY     14
#define LYR_SG        15
#define LYR_MR        16
#define LYR_SH        17
#define LYR_ALL       0

/** Assoc states for SIGTRAN **/
#define ASSOC_STATE_UNKNOWN            1
#define ASSOCUP_SENT       2
#define ASSOCUP_DONE       3
#define ASSOCUP_FAIL       4
#define ASPUP_SENT         5
#define ASPUP_DONE         6
#define ASPUP_FAIL         7
#define ASPACTV_SENT       8
#define ASPACTV_DONE       9
#define ASPACTV_FAIL       10
#define ASSOC_DISABLE      11

/**Endpoint sap states **/
#define BINDED              1
#define UNBINDED            2
#define EP_UNKNOWN          3

//SubOperations
#define BP_AIN_SM_SCT_TSAP 1
#define BP_AIN_SM_SCT_SCTSAP 2
#define BP_AIN_SM_TCA_USAP  3
#define BP_AIN_SM_TCA_LSAP 4
#define BP_AIN_SM_M3U_PS  5
#define BP_AIN_SM_M3U_ROUTE 6
#define BP_AIN_SM_IT_NSAP 7
#define BP_AIN_SM_IT_SCTSAP 8

#define CMD_TYPE_BASELINE 100
#define ADD_NETWORK 			CMD_TYPE_BASELINE + 1
#define DEL_NETWORK 			CMD_TYPE_BASELINE + 2
#define ADD_LINKSET  			CMD_TYPE_BASELINE + 3
#define ADD_LINK     			CMD_TYPE_BASELINE + 4
#define ADD_USERPART    	CMD_TYPE_BASELINE + 5
#define ADD_GTRULE     		CMD_TYPE_BASELINE + 6
#define ADD_GTADDRMAP   	CMD_TYPE_BASELINE + 7
#define ASSOC_UP     			CMD_TYPE_BASELINE + 8
#define ASSOC_DOWN     		CMD_TYPE_BASELINE + 9
#define ASP_UP     				CMD_TYPE_BASELINE + 10
#define ASP_DOWN     			CMD_TYPE_BASELINE + 11
#define ASP_ACTIVE     		CMD_TYPE_BASELINE + 12
#define ASP_INACTIVE    	CMD_TYPE_BASELINE + 13
#define ADD_ROUTE   			CMD_TYPE_BASELINE + 14
#define ADD_LOCAL_SSN   	CMD_TYPE_BASELINE + 15
#define ADD_REMOTE_SSN  	CMD_TYPE_BASELINE + 16
#define ADD_AS     				CMD_TYPE_BASELINE + 17
#define ADD_ASP     			CMD_TYPE_BASELINE + 18
#define ADD_ENDPOINT   		CMD_TYPE_BASELINE + 19
#define ENABLE_LINK     	CMD_TYPE_BASELINE + 20
#define ENABLE_DEBUG    	CMD_TYPE_BASELINE + 21
#define ENABLE_TRACE    	CMD_TYPE_BASELINE + 22
#define ENABLE_LOCAL_SSN  CMD_TYPE_BASELINE + 23
#define ENABLE_USERPART   CMD_TYPE_BASELINE + 24
#define ENABLE_ENDPOINT   CMD_TYPE_BASELINE + 25
#define DISABLE_DEBUG     CMD_TYPE_BASELINE + 26
#define DISABLE_TRACE     CMD_TYPE_BASELINE + 27
#define DISABLE_LOCAL_SSN CMD_TYPE_BASELINE + 28
#define DISABLE_USERPART  CMD_TYPE_BASELINE + 29
#define DISABLE_ENDPOINT  CMD_TYPE_BASELINE + 30
#define DISABLE_LINK      CMD_TYPE_BASELINE + 31
#define DEL_LINK          CMD_TYPE_BASELINE + 32
#define DEL_LINKSET       CMD_TYPE_BASELINE + 33
#define DEL_ROUTE         CMD_TYPE_BASELINE + 34
#define DEL_ENDPOINT      CMD_TYPE_BASELINE + 35
#define DEL_ASP           CMD_TYPE_BASELINE + 36
#define DEL_AS            CMD_TYPE_BASELINE + 37
#define DEL_LOCAL_SSN     CMD_TYPE_BASELINE + 38
#define DEL_REMOTE_SSN    CMD_TYPE_BASELINE + 39
#define DEL_USR_PART      CMD_TYPE_BASELINE + 40
#define STA_LINK          CMD_TYPE_BASELINE + 41
#define STA_LINKSET       CMD_TYPE_BASELINE + 42
#define STA_ROUTE         CMD_TYPE_BASELINE + 43
#define STA_PS            CMD_TYPE_BASELINE + 44
#define STA_PSP           CMD_TYPE_BASELINE + 45
#define STA_NODE          CMD_TYPE_BASELINE + 46
#define ENABLE_NODE       CMD_TYPE_BASELINE + 47
#define DISABLE_NODE      CMD_TYPE_BASELINE + 48
#define DEL_GTRULE        CMD_TYPE_BASELINE + 49
#define DEL_GTADDRMAP     CMD_TYPE_BASELINE + 50
#define MODIFY_LINKSET    CMD_TYPE_BASELINE + 51
#define MODIFY_LINK       CMD_TYPE_BASELINE + 52
#define MODIFY_AS         CMD_TYPE_BASELINE + 53
#define BND_M3UA          CMD_TYPE_BASELINE + 54
#define OPEN_ENDPOINT     CMD_TYPE_BASELINE + 55
#define ABORT_SG_TRANS    CMD_TYPE_BASELINE + 56
#define ENABLE_ALARM      CMD_TYPE_BASELINE + 57
#define DISABLE_ALARM     CMD_TYPE_BASELINE + 58
#define GET_STATS         CMD_TYPE_BASELINE + 59
#define ASSOC_ABRT     		CMD_TYPE_BASELINE + 60
#define UNBIND     		    CMD_TYPE_BASELINE + 61
#define DISABLE_SAPS      CMD_TYPE_BASELINE + 62
#define OPR_STATUS        CMD_TYPE_BASELINE + 63
#define SHUTDOWN_LAYERS   CMD_TYPE_BASELINE + 64
#define BND_SCTP          CMD_TYPE_BASELINE + 65
#define SEND_DAUD         CMD_TYPE_BASELINE + 66
#define SEND_INIT    	  CMD_TYPE_BASELINE + 67
#define AUDIT_INC    	  CMD_TYPE_BASELINE + 68


// Commands from Bulk Config. 
// leaving gap of 11 for future use.
#define INITIALIZE_ENA_LINK CMD_TYPE_BASELINE + 80
#define ENA_SGTRN_LYRS      CMD_TYPE_BASELINE + 81

/*
 * Define the layer ids
 */

#define BP_AIN_SM_LAYER_BASELINE     0

#define BP_AIN_SM_INV_LAYER          BP_AIN_SM_LAYER_BASELINE + 0   /* Invalid Layer */
#define BP_AIN_SM_AIN_LAYER          BP_AIN_SM_LAYER_BASELINE + 1   /* AIN Layer */
#define BP_AIN_SM_TCA_LAYER          BP_AIN_SM_LAYER_BASELINE + 2   /* TCAP Layer */
#define BP_AIN_SM_SCC_LAYER          BP_AIN_SM_LAYER_BASELINE + 3   /* SCCP Layer */
#define BP_AIN_SM_M3U_LAYER          BP_AIN_SM_LAYER_BASELINE + 4   /* M3UA Layer */
#define BP_AIN_SM_SCT_LAYER          BP_AIN_SM_LAYER_BASELINE + 5   /* SCTP Layer */
#define BP_AIN_SM_TUC_LAYER          BP_AIN_SM_LAYER_BASELINE + 6   /* TUCL Layer */
#define BP_AIN_SM_MTP2_LAYER         BP_AIN_SM_LAYER_BASELINE + 7   /* MTP2 Layer */
#define BP_AIN_SM_IU_LAYER           BP_AIN_SM_LAYER_BASELINE + 8   /* INAP User Layer */
#define BP_AIN_SM_MTP3_LAYER         BP_AIN_SM_LAYER_BASELINE + 9   /* MTP3 Layer */
#define BP_AIN_SM_ALL_LAYER          BP_AIN_SM_LAYER_BASELINE + 10  /* ALL Layer */
#define BP_AIN_SM_PSF_M3UA_LAYER      BP_AIN_SM_LAYER_BASELINE + 11  /* PSF-M3UA Layer */
#define BP_AIN_SM_PSF_MTP3_LAYER      BP_AIN_SM_LAYER_BASELINE + 12  /* PSF-MTP3 Layer */
#define BP_AIN_SM_PSF_SCCP_LAYER      BP_AIN_SM_LAYER_BASELINE + 13  /* PSF-SCCP Layer */
#define BP_AIN_SM_PSF_TCAP_LAYER      BP_AIN_SM_LAYER_BASELINE + 14  /* PSF-TCAP Layer */
#define BP_AIN_SM_LDF_M3UA_LAYER      BP_AIN_SM_LAYER_BASELINE + 15  /* LDF-M3UA Layer */
#define BP_AIN_SM_LDF_MTP3_LAYER      BP_AIN_SM_LAYER_BASELINE + 16  /* LDF-MTP3 Layer */
#define BP_AIN_SM_SG_LAYER      BP_AIN_SM_LAYER_BASELINE + 17  /* SG Layer */
#define BP_AIN_SM_SH_LAYER      BP_AIN_SM_LAYER_BASELINE + 18  /* SH Layer */
#define BP_AIN_SM_MR_LAYER      BP_AIN_SM_LAYER_BASELINE + 19  /* MR Layer */
#define BP_AIN_SM_RY_LAYER      BP_AIN_SM_LAYER_BASELINE + 20  /* Relay Layer */
#define BP_AIN_SM_RELAY_LAYER      BP_AIN_SM_LAYER_BASELINE + 20  /* Relay Layer */



/**
 * sub-layer ids.
 */
#define BP_AIN_SM_SUBLYR_BASE       0
#define BP_AIN_SM_SUBLYR_NA         0   // no sublayer applicable
#define BP_AIN_SM_SUBLYR_TCP        BP_AIN_SM_SUBLYR_BASE + 1 // for TUCL 
#define BP_AIN_SM_SUBLYR_UDP        BP_AIN_SM_SUBLYR_BASE + 2 // for TUCL 
#define BP_AIN_SM_SUBLYR_RAW        BP_AIN_SM_SUBLYR_BASE + 3 // for TUCL 
// following are actually M3UA msg type instead of sublayers.
#define BP_AIN_SM_SUBLYR_M3U_ASPSM  BP_AIN_SM_SUBLYR_BASE + 4
#define BP_AIN_SM_SUBLYR_M3U_ASPTM  BP_AIN_SM_SUBLYR_BASE + 5
#define BP_AIN_SM_SUBLYR_M3U_DATA   BP_AIN_SM_SUBLYR_BASE + 6
#define BP_AIN_SM_SUBLYR_M3U_MGMT   BP_AIN_SM_SUBLYR_BASE + 7
#define BP_AIN_SM_SUBLYR_M3U_MSG    BP_AIN_SM_SUBLYR_BASE + 8
#define BP_AIN_SM_SUBLYR_M3U_RKM    BP_AIN_SM_SUBLYR_BASE + 9
#define BP_AIN_SM_SUBLYR_M3U_SSNM   BP_AIN_SM_SUBLYR_BASE + 10

/*
 * Define the Layer Mask
 */

#define BP_AIN_SM_MTP2_MASK          0x0200   /* MTP2 Layer */
#define BP_AIN_SM_SM_MASK            0x0100   /* Stack Mgr Layer */
#define BP_AIN_SM_TU_MASK            0x0080   /* INAP User Layer */
#define BP_AIN_SM_AIN_MASK           0x0040   /* AIN Layer */
#define BP_AIN_SM_TCA_MASK           0x0020   /* TCAP Layer */
#define BP_AIN_SM_SCC_MASK           0x0010   /* SCCP Layer */
#define BP_AIN_SM_M3U_MASK           0x0008   /* M3UA Layer */
#define BP_AIN_SM_SCT_MASK           0x0004   /* SCTP Layer */
#define BP_AIN_SM_TUC_MASK           0x0002   /* TUCL Layer */
#define BP_AIN_SM_MTP3_MASK          0x0001   /* MTP3 Layer */


/*
 * Define the selector for Blocking and Non Blocking operations
 */

#define BP_AIN_SM_SELECTOR_BASELINE  15

#define BP_AIN_SM_BLOCKING_OP        BP_AIN_SM_SELECTOR_BASELINE + 0
#define BP_AIN_SM_NONBLOCKING_OP     BP_AIN_SM_SELECTOR_BASELINE + 1

/*
 * Define the operation types possible
 */

#define BP_AIN_SM_OPTYPE_BASELINE    20

#define BP_AIN_SM_OPTYPE_CFG         BP_AIN_SM_OPTYPE_BASELINE + 0
#define BP_AIN_SM_OPTYPE_ALM         BP_AIN_SM_OPTYPE_BASELINE + 1
#define BP_AIN_SM_OPTYPE_CTL         BP_AIN_SM_OPTYPE_BASELINE + 2
#define BP_AIN_SM_OPTYPE_STA         BP_AIN_SM_OPTYPE_BASELINE + 3
#define BP_AIN_SM_OPTYPE_STS         BP_AIN_SM_OPTYPE_BASELINE + 4
#define BP_AIN_SM_OPTYPE_RCF         BP_AIN_SM_OPTYPE_BASELINE + 5
#define BP_AIN_SM_OPTYPE_TRC         BP_AIN_SM_OPTYPE_BASELINE + 6

/*
 * Define the operations/scenarios allowed to STack Manager
 */

#define BP_AIN_SM_OP_CCM_BASELINE    50

#define BP_AIN_SM_CCM_CS_LOADED      BP_AIN_SM_OP_CCM_BASELINE + 0
#define BP_AIN_SM_CCM_CS_RUNNING     BP_AIN_SM_OP_CCM_BASELINE + 1
#define BP_AIN_SM_CCM_CS_STOPPED     BP_AIN_SM_OP_CCM_BASELINE + 2
#define BP_AIN_SM_CCM_ACTIVE         BP_AIN_SM_OP_CCM_BASELINE + 3 
#define BP_AIN_SM_CCM_ALM_LEVEL      BP_AIN_SM_OP_CCM_BASELINE + 4 
#define BP_AIN_SM_CCM_TRC_LEVEL      BP_AIN_SM_OP_CCM_BASELINE + 5 
#define BP_AIN_SM_CCM_DBG_LEVEL      BP_AIN_SM_OP_CCM_BASELINE + 6 
#define BP_AIN_SM_CCM_STS_TIMER      BP_AIN_SM_OP_CCM_BASELINE + 7 
#define BP_AIN_SM_CCM_STS_LEVEL      BP_AIN_SM_OP_CCM_BASELINE + 8 
#define BP_AIN_SM_CCM_ASP_ACTIVE     BP_AIN_SM_OP_CCM_BASELINE + 9 
#define BP_AIN_SM_CCM_ASP_UP         BP_AIN_SM_OP_CCM_BASELINE + 10 
#define BP_AIN_SM_CCM_EST_ASS        BP_AIN_SM_OP_CCM_BASELINE + 11 
#define BP_AIN_SM_CCM_ASP_INACTIVE   BP_AIN_SM_OP_CCM_BASELINE + 12
#define BP_AIN_SM_CCM_ASP_DOWN       BP_AIN_SM_OP_CCM_BASELINE + 13
#define BP_AIN_SM_CCM_TRM_ASS        BP_AIN_SM_OP_CCM_BASELINE + 14
#define BP_AIN_SM_SYNC_PSP_STA       BP_AIN_SM_OP_CCM_BASELINE + 15
#define BP_AIN_SM_CCM_VERSION        BP_AIN_SM_OP_CCM_BASELINE + 16
#define BP_AIN_SM_ENABLE_NODE        BP_AIN_SM_OP_CCM_BASELINE + 17
#define BP_AIN_SM_CCM_ADD_M3UA_NETWORK   BP_AIN_SM_OP_CCM_BASELINE + 18
#define BP_AIN_SM_CCM_ADD_SCCP_NETWORK   BP_AIN_SM_OP_CCM_BASELINE + 19
#define BP_AIN_SM_CCM_DEL_M3UA_NETWORK   BP_AIN_SM_OP_CCM_BASELINE + 20
#define BP_AIN_SM_CCM_DEL_SCCP_NETWORK   BP_AIN_SM_OP_CCM_BASELINE + 21
#define BP_AIN_SM_CCM_ADD_LNKSET         BP_AIN_SM_OP_CCM_BASELINE + 22
#define BP_AIN_SM_CCM_ADD_MTP3_USERPART  BP_AIN_SM_OP_CCM_BASELINE + 23
#define BP_AIN_SM_CCM_ADD_M3UA_USERPART  BP_AIN_SM_OP_CCM_BASELINE + 24
#define BP_AIN_SM_CCM_ADD_SCCP_USERPART  BP_AIN_SM_OP_CCM_BASELINE + 25
#define BP_AIN_SM_CCM_ADD_MTP3_LNK       BP_AIN_SM_OP_CCM_BASELINE + 26
#define BP_AIN_SM_CCM_ADD_MTP2_LNK       BP_AIN_SM_OP_CCM_BASELINE + 27
#define BP_AIN_SM_CCM_M3U_ASSOC_UP      BP_AIN_SM_OP_CCM_BASELINE + 29
#define BP_AIN_SM_CCM_M3U_ASSOC_DOWN      BP_AIN_SM_OP_CCM_BASELINE + 30
#define BP_AIN_SM_CCM_M3U_ASP_UP      BP_AIN_SM_OP_CCM_BASELINE + 31
#define BP_AIN_SM_CCM_M3U_ASP_DOWN      BP_AIN_SM_OP_CCM_BASELINE + 32
#define BP_AIN_SM_CCM_M3U_ASP_ACTIVE      BP_AIN_SM_OP_CCM_BASELINE + 33
#define BP_AIN_SM_CCM_M3U_ASP_INACTIVE      BP_AIN_SM_OP_CCM_BASELINE + 34
#define BP_AIN_SM_CCM_ADD_MTP3_ROUTE   BP_AIN_SM_OP_CCM_BASELINE + 35
#define BP_AIN_SM_CCM_ADD_SCCP_ROUTE   BP_AIN_SM_OP_CCM_BASELINE + 36
#define BP_AIN_SM_CCM_ADD_M3UA_AS   BP_AIN_SM_OP_CCM_BASELINE + 37
#define BP_AIN_SM_CCM_ADD_M3UA_ASP   BP_AIN_SM_OP_CCM_BASELINE + 38
#define BP_AIN_SM_CCM_ADD_M3UA_EP   BP_AIN_SM_OP_CCM_BASELINE + 39
#define BP_AIN_SM_CCM_ADD_SCTP_TSAP   BP_AIN_SM_OP_CCM_BASELINE + 40
#define BP_AIN_SM_CCM_ADD_SCTP_SCTSAP   BP_AIN_SM_OP_CCM_BASELINE + 41
#define BP_AIN_SM_ENABLE_MTP3_LINK       BP_AIN_SM_OP_CCM_BASELINE + 42
#define BP_AIN_SM_ENABLE_TCAP_SSN      	 BP_AIN_SM_OP_CCM_BASELINE + 43
#define BP_AIN_SM_ENABLE_SCC_USRPART     BP_AIN_SM_OP_CCM_BASELINE + 44
#define BP_AIN_SM_ENABLE_M3UA_EP      	 BP_AIN_SM_OP_CCM_BASELINE + 45
#define BP_AIN_SM_ENABLE_SCTP_EP      	 BP_AIN_SM_OP_CCM_BASELINE + 46
#define BP_AIN_SM_ENB_TCA_DBG_LEVEL      BP_AIN_SM_OP_CCM_BASELINE + 47
#define BP_AIN_SM_ENB_SCC_DBG_LEVEL      BP_AIN_SM_OP_CCM_BASELINE + 48
#define BP_AIN_SM_ENB_MTP3_DBG_LEVEL     BP_AIN_SM_OP_CCM_BASELINE + 49
#define BP_AIN_SM_ENB_MTP2_DBG_LEVEL     BP_AIN_SM_OP_CCM_BASELINE + 50
#define BP_AIN_SM_ENB_M3U_DBG_LEVEL      BP_AIN_SM_OP_CCM_BASELINE + 51
#define BP_AIN_SM_ENB_SCT_DBG_LEVEL      BP_AIN_SM_OP_CCM_BASELINE + 52
#define BP_AIN_SM_ENB_TUC_DBG_LEVEL      BP_AIN_SM_OP_CCM_BASELINE + 53
#define BP_AIN_SM_ENB_TCA_TRC_LEVEL      BP_AIN_SM_OP_CCM_BASELINE + 54
#define BP_AIN_SM_ENB_SCC_TRC_LEVEL      BP_AIN_SM_OP_CCM_BASELINE + 55
#define BP_AIN_SM_ENB_MTP3_TRC_LEVEL     BP_AIN_SM_OP_CCM_BASELINE + 56
#define BP_AIN_SM_ENB_MTP2_TRC_LEVEL     BP_AIN_SM_OP_CCM_BASELINE + 57
#define BP_AIN_SM_ENB_M3U_TRC_LEVEL      BP_AIN_SM_OP_CCM_BASELINE + 58
#define BP_AIN_SM_ENB_SCT_TRC_LEVEL      BP_AIN_SM_OP_CCM_BASELINE + 59
#define BP_AIN_SM_ENB_TUC_TRC_LEVEL      BP_AIN_SM_OP_CCM_BASELINE + 60
#define BP_AIN_SM_DISABLE_TCAP_SSN       BP_AIN_SM_OP_CCM_BASELINE + 61
#define BP_AIN_SM_DISABLE_SCC_USRPART    BP_AIN_SM_OP_CCM_BASELINE + 62
#define BP_AIN_SM_DISABLE_M3UA_EP        BP_AIN_SM_OP_CCM_BASELINE + 63
#define BP_AIN_SM_DISABLE_SCTP_EP        BP_AIN_SM_OP_CCM_BASELINE + 64
#define BP_AIN_SM_DISB_TCA_DBG_LEVEL     BP_AIN_SM_OP_CCM_BASELINE + 65
#define BP_AIN_SM_DISB_SCC_DBG_LEVEL     BP_AIN_SM_OP_CCM_BASELINE + 66
#define BP_AIN_SM_DISB_MTP3_DBG_LEVEL    BP_AIN_SM_OP_CCM_BASELINE + 67
#define BP_AIN_SM_DISB_MTP2_DBG_LEVEL    BP_AIN_SM_OP_CCM_BASELINE + 68
#define BP_AIN_SM_DISB_M3U_DBG_LEVEL     BP_AIN_SM_OP_CCM_BASELINE + 69
#define BP_AIN_SM_DISB_SCT_DBG_LEVEL     BP_AIN_SM_OP_CCM_BASELINE + 70
#define BP_AIN_SM_DISB_TUC_DBG_LEVEL     BP_AIN_SM_OP_CCM_BASELINE + 71
#define BP_AIN_SM_DISB_TCA_TRC_LEVEL     BP_AIN_SM_OP_CCM_BASELINE + 72
#define BP_AIN_SM_DISB_SCC_TRC_LEVEL     BP_AIN_SM_OP_CCM_BASELINE + 73
#define BP_AIN_SM_DISB_MTP3_TRC_LEVEL    BP_AIN_SM_OP_CCM_BASELINE + 74
#define BP_AIN_SM_DISB_MTP2_TRC_LEVEL    BP_AIN_SM_OP_CCM_BASELINE + 75
#define BP_AIN_SM_DISB_M3U_TRC_LEVEL     BP_AIN_SM_OP_CCM_BASELINE + 76
#define BP_AIN_SM_DISB_SCT_TRC_LEVEL     BP_AIN_SM_OP_CCM_BASELINE + 77
#define BP_AIN_SM_DISB_TUC_TRC_LEVEL     BP_AIN_SM_OP_CCM_BASELINE + 78
#define BP_AIN_SM_DISABLE_MTP3_LINK      BP_AIN_SM_OP_CCM_BASELINE + 79
#define BP_AIN_SM_DISABLE_MTP2_LINK      BP_AIN_SM_OP_CCM_BASELINE + 80
#define BP_AIN_SM_ENABLE_MTP2_LINK       BP_AIN_SM_OP_CCM_BASELINE + 81
#define BP_AIN_SM_CCM_ADD_SCCP_L_SSN     BP_AIN_SM_OP_CCM_BASELINE + 82
#define BP_AIN_SM_CCM_ADD_TCAP_USAP      BP_AIN_SM_OP_CCM_BASELINE + 83
#define BP_AIN_SM_CCM_ADD_TCAP_LSAP      BP_AIN_SM_OP_CCM_BASELINE + 84
#define BP_AIN_SM_CCM_ADD_M3UA_ROUTE     BP_AIN_SM_OP_CCM_BASELINE + 85
#define BP_AIN_SM_CCM_M3UA_ASSOC_UP      BP_AIN_SM_OP_CCM_BASELINE + 86
#define BP_AIN_SM_CCM_M3UA_ASSOC_DOWN    BP_AIN_SM_OP_CCM_BASELINE + 87
#define BP_AIN_SM_CCM_M3UA_ASP_UP        BP_AIN_SM_OP_CCM_BASELINE + 88
#define BP_AIN_SM_CCM_M3UA_ASP_DOWN      BP_AIN_SM_OP_CCM_BASELINE + 89
#define BP_AIN_SM_CCM_M3UA_ASP_ACTIVE    BP_AIN_SM_OP_CCM_BASELINE + 90
#define BP_AIN_SM_CCM_M3UA_ASP_INACTIVE  BP_AIN_SM_OP_CCM_BASELINE + 91
#define BP_AIN_SM_CCM_ADD_SCCP_USAP     BP_AIN_SM_OP_CCM_BASELINE + 92
#define BP_AIN_SM_CCM_DEL_MTP3_LINK      BP_AIN_SM_OP_CCM_BASELINE + 93
#define BP_AIN_SM_CCM_DEL_MTP2_LINK      BP_AIN_SM_OP_CCM_BASELINE + 94
#define BP_AIN_SM_CCM_DEL_MTP3_LINKSET   BP_AIN_SM_OP_CCM_BASELINE + 95
#define BP_AIN_SM_CCM_DEL_MTP3_RTE       BP_AIN_SM_OP_CCM_BASELINE + 96
#define BP_AIN_SM_CCM_DEL_SCCP_RTE       BP_AIN_SM_OP_CCM_BASELINE + 97
#define BP_AIN_SM_CCM_DEL_M3UA_EP        BP_AIN_SM_OP_CCM_BASELINE + 98
#define BP_AIN_SM_CCM_DEL_SCTP_EP        BP_AIN_SM_OP_CCM_BASELINE + 99
#define BP_AIN_SM_CCM_DEL_TUCL_EP        BP_AIN_SM_OP_CCM_BASELINE + 100
#define BP_AIN_SM_CCM_DEL_M3UA_AS        BP_AIN_SM_OP_CCM_BASELINE + 101
#define BP_AIN_SM_CCM_DEL_M3UA_ASP       BP_AIN_SM_OP_CCM_BASELINE + 102
#define BP_AIN_SM_CCM_DEL_SCCP_UP        BP_AIN_SM_OP_CCM_BASELINE + 103
#define BP_AIN_SM_CCM_DEL_M3UA_UP        BP_AIN_SM_OP_CCM_BASELINE + 104
#define BP_AIN_SM_CCM_DEL_MTP3_UP        BP_AIN_SM_OP_CCM_BASELINE + 105
#define BP_AIN_SM_CCM_DEL_SCCP_RSSN      BP_AIN_SM_OP_CCM_BASELINE + 106
#define BP_AIN_SM_CCM_DEL_SCCP_LSSN      BP_AIN_SM_OP_CCM_BASELINE + 107
#define BP_AIN_SM_CCM_DEL_TCAP_USAP      BP_AIN_SM_OP_CCM_BASELINE + 108
#define BP_AIN_SM_CCM_MTP3_STA_LINK      BP_AIN_SM_OP_CCM_BASELINE + 109
#define BP_AIN_SM_CCM_MTP3_STA_LINKSET   BP_AIN_SM_OP_CCM_BASELINE + 110
#define BP_AIN_SM_CCM_SCCP_STA_ROUTE     BP_AIN_SM_OP_CCM_BASELINE + 111
#define BP_AIN_SM_CCM_M3UA_STA_PS        BP_AIN_SM_OP_CCM_BASELINE + 112
#define BP_AIN_SM_CCM_M3UA_STA_PSP       BP_AIN_SM_OP_CCM_BASELINE + 113
#define BP_AIN_SM_SG_ENABLE_NODE         BP_AIN_SM_OP_CCM_BASELINE + 114
#define BP_AIN_SM_SG_DISABLE_NODE        BP_AIN_SM_OP_CCM_BASELINE + 115
#define BP_AIN_SM_CCM_ADD_LDF_MTP3_LNK   BP_AIN_SM_OP_CCM_BASELINE + 116 
#define BP_AIN_SM_CCM_ADD_LDF_MTP3_USERPART  BP_AIN_SM_OP_CCM_BASELINE + 117 
#define BP_AIN_SM_CCM_ADD_LDF_M3UA_USERPART  BP_AIN_SM_OP_CCM_BASELINE + 118
#define BP_AIN_SM_CCM_ADD_SCCP_GTADDR_MAP    BP_AIN_SM_OP_CCM_BASELINE + 119
#define BP_AIN_SM_CCM_ADD_SCCP_GTRULE        BP_AIN_SM_OP_CCM_BASELINE + 120
#define BP_AIN_SM_ENB_SG_DBG_LEVEL           BP_AIN_SM_OP_CCM_BASELINE + 121
#define BP_AIN_SM_ENB_SH_DBG_LEVEL           BP_AIN_SM_OP_CCM_BASELINE + 122
#define BP_AIN_SM_ENB_MR_DBG_LEVEL           BP_AIN_SM_OP_CCM_BASELINE + 123
#define BP_AIN_SM_ENB_PSF_TCAP_DBG_LEVEL     BP_AIN_SM_OP_CCM_BASELINE + 124
#define BP_AIN_SM_ENB_PSF_SCCP_DBG_LEVEL     BP_AIN_SM_OP_CCM_BASELINE + 125
#define BP_AIN_SM_ENB_PSF_MTP3_DBG_LEVEL     BP_AIN_SM_OP_CCM_BASELINE + 126
#define BP_AIN_SM_ENB_PSF_M3UA_DBG_LEVEL     BP_AIN_SM_OP_CCM_BASELINE + 127
#define BP_AIN_SM_ENB_LDF_M3UA_DBG_LEVEL     BP_AIN_SM_OP_CCM_BASELINE + 128
#define BP_AIN_SM_ENB_LDF_MTP3_DBG_LEVEL     BP_AIN_SM_OP_CCM_BASELINE + 129
#define BP_AIN_SM_CCM_DEL_SCCP_GTADDR_MAP    BP_AIN_SM_OP_CCM_BASELINE + 130
#define BP_AIN_SM_CCM_DEL_SCCP_GTRULE        BP_AIN_SM_OP_CCM_BASELINE + 131
#define BP_AIN_SM_CCM_ADD_TUCL_EP            BP_AIN_SM_OP_CCM_BASELINE + 132
#define BP_AIN_SM_CCM_ADD_LDF_M3UA_EP        BP_AIN_SM_OP_CCM_BASELINE + 133
#define BP_AIN_SM_CCM_TCA_STA_NODE           BP_AIN_SM_OP_CCM_BASELINE + 134
#define BP_AIN_SM_CCM_SCC_STA_NODE           BP_AIN_SM_OP_CCM_BASELINE + 135
#define BP_AIN_SM_CCM_MTP3_STA_NODE          BP_AIN_SM_OP_CCM_BASELINE + 136
#define BP_AIN_SM_CCM_MTP2_STA_NODE          BP_AIN_SM_OP_CCM_BASELINE + 137
#define BP_AIN_SM_CCM_M3U_STA_NODE           BP_AIN_SM_OP_CCM_BASELINE + 138
#define BP_AIN_SM_CCM_SCT_STA_NODE           BP_AIN_SM_OP_CCM_BASELINE + 139
#define BP_AIN_SM_CCM_TUC_STA_NODE           BP_AIN_SM_OP_CCM_BASELINE + 140
#define BP_AIN_SM_CCM_DEL_LDF_M3UA_UP        BP_AIN_SM_OP_CCM_BASELINE + 141
#define BP_AIN_SM_CCM_DEL_LDF_MTP3_UP        BP_AIN_SM_OP_CCM_BASELINE + 142
#define BP_AIN_SM_CCM_DEL_M3UA_RTE           BP_AIN_SM_OP_CCM_BASELINE + 143
#define BP_AIN_SM_CCM_DEL_TCAP_LSAP          BP_AIN_SM_OP_CCM_BASELINE + 144
#define BP_AIN_SM_CCM_DEL_SCTP_T_EP          BP_AIN_SM_OP_CCM_BASELINE + 145
#define BP_AIN_SM_CCM_DEL_LDF_MTP3_LINK      BP_AIN_SM_OP_CCM_BASELINE + 146
#define BP_AIN_SM_CCM_MTP2_STA_LINK          BP_AIN_SM_OP_CCM_BASELINE + 147
#define BP_AIN_SM_CCM_MOD_MTP3_LNK           BP_AIN_SM_OP_CCM_BASELINE + 148
#define BP_AIN_SM_CCM_MOD_MTP2_LNK           BP_AIN_SM_OP_CCM_BASELINE + 149
#define BP_AIN_SM_CCM_MOD_LDF_MTP3_LNK       BP_AIN_SM_OP_CCM_BASELINE + 150 
#define BP_AIN_SM_CCM_MOD_M3UA_AS            BP_AIN_SM_OP_CCM_BASELINE + 151
#define BP_AIN_SM_CCM_MOD_LNKSET             BP_AIN_SM_OP_CCM_BASELINE + 152
#define BP_AIN_SM_CCM_M3UA_SCT_BND           BP_AIN_SM_OP_CCM_BASELINE + 153
#define BP_AIN_SM_CCM_SCCP_BND               BP_AIN_SM_OP_CCM_BASELINE + 154
#define BP_AIN_SM_CCM_M3UA_NSAP_BND          BP_AIN_SM_OP_CCM_BASELINE + 155
#define BP_AIN_SM_CCM_OPEN_EP                BP_AIN_SM_OP_CCM_BASELINE + 156
#define BP_AIN_SM_CCM_SCTP_BND               BP_AIN_SM_OP_CCM_BASELINE + 157
#define BP_AIN_SM_SG_ABORT_TRANS             BP_AIN_SM_OP_CCM_BASELINE + 158
#define BP_AIN_SM_ENB_TCA_ALM_LEVEL          BP_AIN_SM_OP_CCM_BASELINE + 159
#define BP_AIN_SM_ENB_SCC_ALM_LEVEL          BP_AIN_SM_OP_CCM_BASELINE + 160
#define BP_AIN_SM_ENB_MTP3_ALM_LEVEL         BP_AIN_SM_OP_CCM_BASELINE + 161
#define BP_AIN_SM_ENB_MTP2_ALM_LEVEL         BP_AIN_SM_OP_CCM_BASELINE + 162
#define BP_AIN_SM_ENB_M3U_ALM_LEVEL          BP_AIN_SM_OP_CCM_BASELINE + 163
#define BP_AIN_SM_ENB_SCT_ALM_LEVEL          BP_AIN_SM_OP_CCM_BASELINE + 164
#define BP_AIN_SM_ENB_TUC_ALM_LEVEL          BP_AIN_SM_OP_CCM_BASELINE + 165
#define BP_AIN_SM_ENB_SG_ALM_LEVEL           BP_AIN_SM_OP_CCM_BASELINE + 166
#define BP_AIN_SM_ENB_SH_ALM_LEVEL           BP_AIN_SM_OP_CCM_BASELINE + 167
#define BP_AIN_SM_ENB_MR_ALM_LEVEL           BP_AIN_SM_OP_CCM_BASELINE + 168
#define BP_AIN_SM_ENB_PSF_TCAP_ALM_LEVEL     BP_AIN_SM_OP_CCM_BASELINE + 169
#define BP_AIN_SM_ENB_PSF_SCCP_ALM_LEVEL     BP_AIN_SM_OP_CCM_BASELINE + 170
#define BP_AIN_SM_ENB_PSF_MTP3_ALM_LEVEL     BP_AIN_SM_OP_CCM_BASELINE + 171
#define BP_AIN_SM_ENB_PSF_M3UA_ALM_LEVEL     BP_AIN_SM_OP_CCM_BASELINE + 172
#define BP_AIN_SM_ENB_LDF_M3UA_ALM_LEVEL     BP_AIN_SM_OP_CCM_BASELINE + 173
#define BP_AIN_SM_ENB_LDF_MTP3_ALM_LEVEL     BP_AIN_SM_OP_CCM_BASELINE + 174
#define BP_AIN_SM_ENB_RY_ALM_LEVEL           BP_AIN_SM_OP_CCM_BASELINE + 175
#define BP_AIN_SM_DIS_TCA_ALM_LEVEL          BP_AIN_SM_OP_CCM_BASELINE + 176
#define BP_AIN_SM_DIS_SCC_ALM_LEVEL          BP_AIN_SM_OP_CCM_BASELINE + 177
#define BP_AIN_SM_DIS_MTP3_ALM_LEVEL         BP_AIN_SM_OP_CCM_BASELINE + 178
#define BP_AIN_SM_DIS_MTP2_ALM_LEVEL         BP_AIN_SM_OP_CCM_BASELINE + 179
#define BP_AIN_SM_DIS_M3U_ALM_LEVEL          BP_AIN_SM_OP_CCM_BASELINE + 180
#define BP_AIN_SM_DIS_TUC_ALM_LEVEL          BP_AIN_SM_OP_CCM_BASELINE + 181
#define BP_AIN_SM_DIS_SCT_ALM_LEVEL          BP_AIN_SM_OP_CCM_BASELINE + 182
#define BP_AIN_SM_DIS_SG_ALM_LEVEL           BP_AIN_SM_OP_CCM_BASELINE + 183
#define BP_AIN_SM_DIS_MR_ALM_LEVEL           BP_AIN_SM_OP_CCM_BASELINE + 184
#define BP_AIN_SM_DIS_SH_ALM_LEVEL           BP_AIN_SM_OP_CCM_BASELINE + 185
#define BP_AIN_SM_DIS_RY_ALM_LEVEL           BP_AIN_SM_OP_CCM_BASELINE + 186
#define BP_AIN_SM_DIS_PSF_M3UA_ALM_LEVEL     BP_AIN_SM_OP_CCM_BASELINE + 187
#define BP_AIN_SM_DIS_PSF_MTP3_ALM_LEVEL     BP_AIN_SM_OP_CCM_BASELINE + 188
#define BP_AIN_SM_DIS_LDF_MTP3_ALM_LEVEL     BP_AIN_SM_OP_CCM_BASELINE + 189
#define BP_AIN_SM_DIS_LDF_M3UA_ALM_LEVEL     BP_AIN_SM_OP_CCM_BASELINE + 190
#define BP_AIN_SM_DIS_PSF_TCAP_ALM_LEVEL     BP_AIN_SM_OP_CCM_BASELINE + 191
#define BP_AIN_SM_DIS_PSF_SCCP_ALM_LEVEL     BP_AIN_SM_OP_CCM_BASELINE + 192
#define BP_AIN_SM_CCM_STS_TCA                BP_AIN_SM_OP_CCM_BASELINE + 193
#define BP_AIN_SM_CCM_STS_SCC                BP_AIN_SM_OP_CCM_BASELINE + 194
#define BP_AIN_SM_CCM_STS_MTP3               BP_AIN_SM_OP_CCM_BASELINE + 195
#define BP_AIN_SM_CCM_STS_M3U                BP_AIN_SM_OP_CCM_BASELINE + 196
#define BP_AIN_SM_CCM_STS_SCT                BP_AIN_SM_OP_CCM_BASELINE + 197
#define BP_AIN_SM_CCM_M3UA_ASSOC_ABRT        BP_AIN_SM_OP_CCM_BASELINE + 198
#define BP_AIN_SM_CCM_M3UA_UNBIND            BP_AIN_SM_OP_CCM_BASELINE + 199
#define BP_AIN_SM_CCM_DIS_SCCP_LSSN          BP_AIN_SM_OP_CCM_BASELINE + 200
#define BP_AIN_SM_CCM_DIS_TCAP_USAP          BP_AIN_SM_OP_CCM_BASELINE + 201
#define BP_AIN_SM_CCM_DIS_TCAP_LSAP          BP_AIN_SM_OP_CCM_BASELINE + 202
#define BP_AIN_SM_CCM_SHTDN_TCA              BP_AIN_SM_OP_CCM_BASELINE + 203
#define BP_AIN_SM_CCM_SHTDN_SCC              BP_AIN_SM_OP_CCM_BASELINE + 204
#define BP_AIN_SM_CCM_SHTDN_MTP3             BP_AIN_SM_OP_CCM_BASELINE + 205
#define BP_AIN_SM_CCM_SHTDN_M3U              BP_AIN_SM_OP_CCM_BASELINE + 206
#define BP_AIN_SM_CCM_SHTDN_SCT              BP_AIN_SM_OP_CCM_BASELINE + 207
#define BP_AIN_SM_CCM_DIS_MTP3_SAP           BP_AIN_SM_OP_CCM_BASELINE + 208
#define BP_AIN_SM_CCM_DIS_M3UA_SAP           BP_AIN_SM_OP_CCM_BASELINE + 209
#define BP_AIN_SM_CCM_DIS_SCT_SAP            BP_AIN_SM_OP_CCM_BASELINE + 210
#define BP_AIN_SM_CCM_DIS_TUC_SAP            BP_AIN_SM_OP_CCM_BASELINE + 211
#define BP_AIN_SM_ENB_RY_DBG_LEVEL           BP_AIN_SM_OP_CCM_BASELINE + 212
#define BP_AIN_SM_DISB_RY_DBG_LEVEL          BP_AIN_SM_OP_CCM_BASELINE + 213
#define BP_AIN_SM_DISB_SG_DBG_LEVEL          BP_AIN_SM_OP_CCM_BASELINE + 214
#define BP_AIN_SM_DISB_SH_DBG_LEVEL          BP_AIN_SM_OP_CCM_BASELINE + 215
#define BP_AIN_SM_DISB_MR_DBG_LEVEL          BP_AIN_SM_OP_CCM_BASELINE + 216
#define BP_AIN_SM_DISB_PSF_TCAP_DBG_LEVEL    BP_AIN_SM_OP_CCM_BASELINE + 217
#define BP_AIN_SM_DISB_PSF_SCCP_DBG_LEVEL    BP_AIN_SM_OP_CCM_BASELINE + 218
#define BP_AIN_SM_DISB_PSF_MTP3_DBG_LEVEL    BP_AIN_SM_OP_CCM_BASELINE + 219
#define BP_AIN_SM_DISB_PSF_M3UA_DBG_LEVEL    BP_AIN_SM_OP_CCM_BASELINE + 220
#define BP_AIN_SM_DISB_LDF_M3UA_DBG_LEVEL    BP_AIN_SM_OP_CCM_BASELINE + 221
#define BP_AIN_SM_DISB_LDF_MTP3_DBG_LEVEL    BP_AIN_SM_OP_CCM_BASELINE + 222
#define BP_AIN_SM_CCM_AUDIT_INC              BP_AIN_SM_OP_CCM_BASELINE + 223
#define BP_AIN_SM_CCM_M3UA_SNDDAUD           BP_AIN_SM_OP_CCM_BASELINE + 224




/*
 * Define the operation sub-types possible from CCM-->SM
 */

//Invalid Operation
#define BP_AIN_SM_SUBTYPE_INVALID                 -1


#define BP_AIN_SM_CFG_OPSUBTYPE_BASE              100

//Configuration related
#define BP_AIN_SM_SUBTYPE_GENCFG                  BP_AIN_SM_CFG_OPSUBTYPE_BASE + 0
#define BP_AIN_SM_SUBTYPE_USPCFG                  BP_AIN_SM_CFG_OPSUBTYPE_BASE + 1
#define BP_AIN_SM_SUBTYPE_LSPCFG                  BP_AIN_SM_CFG_OPSUBTYPE_BASE + 2
#define BP_AIN_SM_SUBTYPE_NWKCFG                  BP_AIN_SM_CFG_OPSUBTYPE_BASE + 3
#define BP_AIN_SM_SUBTYPE_RTECFG                  BP_AIN_SM_CFG_OPSUBTYPE_BASE + 4
#define BP_AIN_SM_SUBTYPE_PSCFG                   BP_AIN_SM_CFG_OPSUBTYPE_BASE + 5
#define BP_AIN_SM_SUBTYPE_PSPCFG                  BP_AIN_SM_CFG_OPSUBTYPE_BASE + 6
#define BP_AIN_SM_SUBTYPE_LNKSETCFG               BP_AIN_SM_CFG_OPSUBTYPE_BASE + 7
#define BP_AIN_SM_SUBTYPE_RTECFG_SELF             BP_AIN_SM_CFG_OPSUBTYPE_BASE + 8
#define BP_AIN_SM_SUBTYPE_RTECFG_PEER             BP_AIN_SM_CFG_OPSUBTYPE_BASE + 9
#define BP_AIN_SM_SUBTYPE_RSETMAPCFG_CRITICAL     BP_AIN_SM_CFG_OPSUBTYPE_BASE + 10
#define BP_AIN_SM_SUBTYPE_RSETMAPCFG_NONCRITICAL  BP_AIN_SM_CFG_OPSUBTYPE_BASE + 11
#define BP_AIN_SM_SUBTYPE_RSETMAPCFG_DEF          BP_AIN_SM_CFG_OPSUBTYPE_BASE + 12
#define BP_AIN_SM_SUBTYPE_ENT_SG                  BP_AIN_SM_CFG_OPSUBTYPE_BASE + 13
#define BP_AIN_SM_SUBTYPE_ENT_TUCL                BP_AIN_SM_CFG_OPSUBTYPE_BASE + 14
#define BP_AIN_SM_SUBTYPE_ENT_SCTP                BP_AIN_SM_CFG_OPSUBTYPE_BASE + 15 
#define BP_AIN_SM_SUBTYPE_ENT_SCCP                BP_AIN_SM_CFG_OPSUBTYPE_BASE + 16
#define BP_AIN_SM_SUBTYPE_ENT_TCAP                BP_AIN_SM_CFG_OPSUBTYPE_BASE + 17
#define BP_AIN_SM_SUBTYPE_ENT_M3UA                BP_AIN_SM_CFG_OPSUBTYPE_BASE + 18
#define BP_AIN_SM_SUBTYPE_ENT_MTP3                BP_AIN_SM_CFG_OPSUBTYPE_BASE + 19
#define BP_AIN_SM_SUBTYPE_ENT_MTP2                BP_AIN_SM_CFG_OPSUBTYPE_BASE + 20
#define BP_AIN_SM_SUBTYPE_LIS_CHANCFG             BP_AIN_SM_CFG_OPSUBTYPE_BASE + 21
#define BP_AIN_SM_SUBTYPE_SRV_CHANCFG             BP_AIN_SM_CFG_OPSUBTYPE_BASE + 22
#define BP_AIN_SM_SUBTYPE_CLI_CHANCFG             BP_AIN_SM_CFG_OPSUBTYPE_BASE + 23
#define BP_AIN_SM_SUBTYPE_OPENEP                  BP_AIN_SM_CFG_OPSUBTYPE_BASE + 24
#define BP_AIN_SM_SUBTYPE_GTADDRMAP               BP_AIN_SM_CFG_OPSUBTYPE_BASE + 25
#define BP_AIN_SM_SUBTYPE_GTRULE                  BP_AIN_SM_CFG_OPSUBTYPE_BASE + 26

#define BP_AIN_SM_CTL_OPSUBTYPE_BASE              BP_AIN_SM_CFG_OPSUBTYPE_BASE + 100

//control related
#define BP_AIN_SM_SUBTYPE_ENAALM                  BP_AIN_SM_CTL_OPSUBTYPE_BASE + 1
#define BP_AIN_SM_SUBTYPE_DISALM                  BP_AIN_SM_CTL_OPSUBTYPE_BASE + 2
#define BP_AIN_SM_SUBTYPE_ENATRC                  BP_AIN_SM_CTL_OPSUBTYPE_BASE + 3
#define BP_AIN_SM_SUBTYPE_DISTRC                  BP_AIN_SM_CTL_OPSUBTYPE_BASE + 4
#define BP_AIN_SM_SUBTYPE_ENADBG                  BP_AIN_SM_CTL_OPSUBTYPE_BASE + 5
#define BP_AIN_SM_SUBTYPE_DISDBG                  BP_AIN_SM_CTL_OPSUBTYPE_BASE + 6
#define BP_AIN_SM_SUBTYPE_SHTDWN                  BP_AIN_SM_CTL_OPSUBTYPE_BASE + 7
#define BP_AIN_SM_SUBTYPE_ENASAP                  BP_AIN_SM_CTL_OPSUBTYPE_BASE + 8
#define BP_AIN_SM_SUBTYPE_DISSAP                  BP_AIN_SM_CTL_OPSUBTYPE_BASE + 9
#define BP_AIN_SM_SUBTYPE_AUDDLG                  BP_AIN_SM_CTL_OPSUBTYPE_BASE + 10
#define BP_AIN_SM_SUBTYPE_AUDINV                  BP_AIN_SM_CTL_OPSUBTYPE_BASE + 11
#define BP_AIN_SM_SUBTYPE_CNGCTL                  BP_AIN_SM_CTL_OPSUBTYPE_BASE + 12
#define BP_AIN_SM_SUBTYPE_DELRTE                  BP_AIN_SM_CTL_OPSUBTYPE_BASE + 13
#define BP_AIN_SM_SUBTYPE_DISCSA                  BP_AIN_SM_CTL_OPSUBTYPE_BASE + 14
#define BP_AIN_SM_SUBTYPE_ENACSA                  BP_AIN_SM_CTL_OPSUBTYPE_BASE + 15
#define BP_AIN_SM_SUBTYPE_ENAERR                  BP_AIN_SM_CTL_OPSUBTYPE_BASE + 16
#define BP_AIN_SM_SUBTYPE_GRDTMR                  BP_AIN_SM_CTL_OPSUBTYPE_BASE + 17
#define BP_AIN_SM_SUBTYPE_DELADM                  BP_AIN_SM_CTL_OPSUBTYPE_BASE + 18
#define BP_AIN_SM_SUBTYPE_DELASS                  BP_AIN_SM_CTL_OPSUBTYPE_BASE + 19
#define BP_AIN_SM_SUBTYPE_DELNWK                  BP_AIN_SM_CTL_OPSUBTYPE_BASE + 20
#define BP_AIN_SM_SUBTYPE_ESTASS                  BP_AIN_SM_CTL_OPSUBTYPE_BASE + 21
#define BP_AIN_SM_SUBTYPE_TRMASS                  BP_AIN_SM_CTL_OPSUBTYPE_BASE + 22
#define BP_AIN_SM_SUBTYPE_SNDAUP                  BP_AIN_SM_CTL_OPSUBTYPE_BASE + 23
#define BP_AIN_SM_SUBTYPE_SNDAAC                  BP_AIN_SM_CTL_OPSUBTYPE_BASE + 24
#define BP_AIN_SM_SUBTYPE_SNDADN                  BP_AIN_SM_CTL_OPSUBTYPE_BASE + 25
#define BP_AIN_SM_SUBTYPE_SNDAIA                  BP_AIN_SM_CTL_OPSUBTYPE_BASE + 26
#define BP_AIN_SM_SUBTYPE_SNDSCN                  BP_AIN_SM_CTL_OPSUBTYPE_BASE + 27
#define BP_AIN_SM_SUBTYPE_INHASS                  BP_AIN_SM_CTL_OPSUBTYPE_BASE + 28
#define BP_AIN_SM_SUBTYPE_UINASS                  BP_AIN_SM_CTL_OPSUBTYPE_BASE + 29
#define BP_AIN_SM_SUBTYPE_DELPS                   BP_AIN_SM_CTL_OPSUBTYPE_BASE + 30
#define BP_AIN_SM_SUBTYPE_DELPSP                  BP_AIN_SM_CTL_OPSUBTYPE_BASE + 31
#define BP_AIN_SM_SUBTYPE_REGDRK                  BP_AIN_SM_CTL_OPSUBTYPE_BASE + 32
#define BP_AIN_SM_SUBTYPE_DERDRK                  BP_AIN_SM_CTL_OPSUBTYPE_BASE + 33
#define BP_AIN_SM_SUBTYPE_ENBLNK                  BP_AIN_SM_CTL_OPSUBTYPE_BASE + 34
#define BP_AIN_SM_SUBTYPE_ENB_LSSN                BP_AIN_SM_CTL_OPSUBTYPE_BASE + 35
#define BP_AIN_SM_SUBTYPE_ENB_USRPART             BP_AIN_SM_CTL_OPSUBTYPE_BASE + 36
#define BP_AIN_SM_SUBTYPE_M3U_ENB_EP              BP_AIN_SM_CTL_OPSUBTYPE_BASE + 37
#define BP_AIN_SM_SUBTYPE_SCT_ENB_EP              BP_AIN_SM_CTL_OPSUBTYPE_BASE + 38
#define BP_AIN_SM_SUBTYPE_DIS_LSSN                BP_AIN_SM_CTL_OPSUBTYPE_BASE + 39
#define BP_AIN_SM_SUBTYPE_DIS_USRPART             BP_AIN_SM_CTL_OPSUBTYPE_BASE + 40
#define BP_AIN_SM_SUBTYPE_M3U_DIS_EP              BP_AIN_SM_CTL_OPSUBTYPE_BASE + 41
#define BP_AIN_SM_SUBTYPE_SCT_DIS_EP              BP_AIN_SM_CTL_OPSUBTYPE_BASE + 42
#define BP_AIN_SM_SUBTYPE_DISLNK                  BP_AIN_SM_CTL_OPSUBTYPE_BASE + 43
#define BP_AIN_SM_SUBTYPE_ENAENT                  BP_AIN_SM_CTL_OPSUBTYPE_BASE + 44
#define BP_AIN_SM_SUBTYPE_DELLNK                  BP_AIN_SM_CTL_OPSUBTYPE_BASE + 45
#define BP_AIN_SM_SUBTYPE_DELLNKSET               BP_AIN_SM_CTL_OPSUBTYPE_BASE + 46
#define BP_AIN_SM_SUBTYPE_DEL_RTE                 BP_AIN_SM_CTL_OPSUBTYPE_BASE + 47
#define BP_AIN_SM_SUBTYPE_DEL_EP                  BP_AIN_SM_CTL_OPSUBTYPE_BASE + 48
#define BP_AIN_SM_SUBTYPE_DEL_ASP                 BP_AIN_SM_CTL_OPSUBTYPE_BASE + 49
#define BP_AIN_SM_SUBTYPE_DEL_AS                  BP_AIN_SM_CTL_OPSUBTYPE_BASE + 50
#define BP_AIN_SM_SUBTYPE_DEL_UP                  BP_AIN_SM_CTL_OPSUBTYPE_BASE + 51
#define BP_AIN_SM_SUBTYPE_DEL_RSSN                BP_AIN_SM_CTL_OPSUBTYPE_BASE + 52
#define BP_AIN_SM_SUBTYPE_DEL_LSAP                BP_AIN_SM_CTL_OPSUBTYPE_BASE + 53
#define BP_AIN_SM_SUBTYPE_DEL_USAP                BP_AIN_SM_CTL_OPSUBTYPE_BASE + 54
#define BP_AIN_SM_SUBTYPE_DEL_LSSN                BP_AIN_SM_CTL_OPSUBTYPE_BASE + 55
#define BP_AIN_SM_SUBTYPE_ENBNODE                 BP_AIN_SM_CTL_OPSUBTYPE_BASE + 56
#define BP_AIN_SM_SUBTYPE_DISNODE                 BP_AIN_SM_CTL_OPSUBTYPE_BASE + 57
#define BP_AIN_SM_SUBTYPE_DEL_T_EP                BP_AIN_SM_CTL_OPSUBTYPE_BASE + 58
#define BP_AIN_SM_SUBTYPE_ABORT_SG_TRANS          BP_AIN_SM_CTL_OPSUBTYPE_BASE + 59
#define BP_AIN_SM_SUBTYPE_ABRTASS                 BP_AIN_SM_CTL_OPSUBTYPE_BASE + 60
#define BP_AIN_SM_SUBTYPE_M3UUBND                 BP_AIN_SM_CTL_OPSUBTYPE_BASE + 61
#define BP_AIN_SM_SUBTYPE_DISUSAP                 BP_AIN_SM_CTL_OPSUBTYPE_BASE + 62
#define BP_AIN_SM_SUBTYPE_DISLSAP                 BP_AIN_SM_CTL_OPSUBTYPE_BASE + 63
#define BP_AIN_SM_SUBTYPE_SHTDN_TCA               BP_AIN_SM_CTL_OPSUBTYPE_BASE + 64
#define BP_AIN_SM_SUBTYPE_SHTDN_SCC               BP_AIN_SM_CTL_OPSUBTYPE_BASE + 65
#define BP_AIN_SM_SUBTYPE_SHTDN_MTP3              BP_AIN_SM_CTL_OPSUBTYPE_BASE + 66
#define BP_AIN_SM_SUBTYPE_SHTDN_M3U               BP_AIN_SM_CTL_OPSUBTYPE_BASE + 67
#define BP_AIN_SM_SUBTYPE_SHTDN_SCT               BP_AIN_SM_CTL_OPSUBTYPE_BASE + 68
#define BP_AIN_SM_SUBTYPE_AUDIT                   BP_AIN_SM_CTL_OPSUBTYPE_BASE + 69
#define BP_AIN_SM_SUBTYPE_SNDDAUD                 BP_AIN_SM_CTL_OPSUBTYPE_BASE + 70

#define BP_AIN_SM_STS_OPSUBTYPE_BASE              BP_AIN_SM_CTL_OPSUBTYPE_BASE + 100

//status related
#define BP_AIN_SM_SUBTYPE_SYSID                   BP_AIN_SM_STS_OPSUBTYPE_BASE + 1
#define BP_AIN_SM_SUBTYPE_SAPSTA                  BP_AIN_SM_STS_OPSUBTYPE_BASE + 2
#define BP_AIN_SM_SUBTYPE_RTESTA                  BP_AIN_SM_STS_OPSUBTYPE_BASE + 3
#define BP_AIN_SM_SUBTYPE_LYRSTA                  BP_AIN_SM_STS_OPSUBTYPE_BASE + 4
#define BP_AIN_SM_SUBTYPE_ATTSTA                  BP_AIN_SM_STS_OPSUBTYPE_BASE + 5
#define BP_AIN_SM_SUBTYPE_PSSTA                   BP_AIN_SM_STS_OPSUBTYPE_BASE + 6
#define BP_AIN_SM_SUBTYPE_PSPSTA                  BP_AIN_SM_STS_OPSUBTYPE_BASE + 7
#define BP_AIN_SM_SUBTYPE_DRKSTA                  BP_AIN_SM_STS_OPSUBTYPE_BASE + 8
#define BP_AIN_SM_SUBTYPE_ASSSTA                  BP_AIN_SM_STS_OPSUBTYPE_BASE + 9
#define BP_AIN_SM_SUBTYPE_DSTSTA                  BP_AIN_SM_STS_OPSUBTYPE_BASE + 10
#define BP_AIN_SM_SUBTYPE_STA_LINK                BP_AIN_SM_STS_OPSUBTYPE_BASE + 11
#define BP_AIN_SM_SUBTYPE_STA_LINKSET             BP_AIN_SM_STS_OPSUBTYPE_BASE + 12
#define BP_AIN_SM_SUBTYPE_STA_ROUTE               BP_AIN_SM_STS_OPSUBTYPE_BASE + 13
#define BP_AIN_SM_SUBTYPE_STA_PS                  BP_AIN_SM_STS_OPSUBTYPE_BASE + 14
#define BP_AIN_SM_SUBTYPE_STA_PSP                 BP_AIN_SM_STS_OPSUBTYPE_BASE + 15
#define BP_AIN_SM_SUBTYPE_STA_NODE                BP_AIN_SM_STS_OPSUBTYPE_BASE + 16
#define BP_AIN_SM_SUBTYPE_STS                     BP_AIN_SM_STS_OPSUBTYPE_BASE + 17
                                                                    
#define BP_AIN_SM_STA_OPSUBTYPE_BASE              BP_AIN_SM_STS_OPSUBTYPE_BASE + 100                            
//statistics related
#define BP_AIN_SM_SUBTYPE_GENSTS                  BP_AIN_SM_STA_OPSUBTYPE_BASE + 1
#define BP_AIN_SM_SUBTYPE_USPSTS                  BP_AIN_SM_STA_OPSUBTYPE_BASE + 2
#define BP_AIN_SM_SUBTYPE_LSPSTS                  BP_AIN_SM_STA_OPSUBTYPE_BASE + 3
#define BP_AIN_SM_SUBTYPE_RTESTS                  BP_AIN_SM_STA_OPSUBTYPE_BASE + 4
#define BP_AIN_SM_SUBTYPE_PSPSTS                  BP_AIN_SM_STA_OPSUBTYPE_BASE + 5

#define BP_AIN_SM_SUBTYPE_LNKSTS                  BP_AIN_SM_STA_OPSUBTYPE_BASE + 6
#define BP_AIN_SM_SUBTYPE_LSESTS                  BP_AIN_SM_STA_OPSUBTYPE_BASE + 7
#define BP_AIN_SM_SUBTYPE_SGPSTS                  BP_AIN_SM_STA_OPSUBTYPE_BASE + 8




/***********************************************************************
 * PSP States available
 *
 *            State Diagram will be,
 *
 *                DOWN
 *                /  ^
 *          ESTAS|    \
 *               \     |TRMASS
 *                v   /
 *                ESTASS
 *                /  ^
 *          ASPUP|    \
 *               \     | ASPDN
 *                v   /
 *               ASP-UP
 *                /  ^
 *         ASPAC |    \
 *               \     | ASPIA
 *                v   /
 *                ASP-AC
 *
 * Note : The state flow will happen in forward direction only.
 *        eg, sending ESTASS in ASP-UP will not bring it to ESTASS state.
 *
 *
 *
 *
 ***********************************************************************/

#define BP_AIN_SM_PSP_STATE_BASELINE 200

#define BP_AIN_SM_PSP_ST_DOWN        BP_AIN_SM_PSP_STATE_BASELINE + 1
#define BP_AIN_SM_PSP_ST_ESTASS      BP_AIN_SM_PSP_STATE_BASELINE + 2
#define BP_AIN_SM_PSP_ST_ASPUP       BP_AIN_SM_PSP_STATE_BASELINE + 3
#define BP_AIN_SM_PSP_ST_ASPAC       BP_AIN_SM_PSP_STATE_BASELINE + 4




/***********************************************************************
** ERROR CODES -- begin
***********************************************************************/

#define BP_AIN_SM_ERR_BASE    0  

#define BP_AIN_SM_ERR_SW_ERR             BP_AIN_SM_ERR_BASE + 1
#define BP_AIN_SM_ERR_RESOURCE_ERR       BP_AIN_SM_ERR_BASE + 2
#define BP_AIN_SM_ERR_CONFIG_ERR         BP_AIN_SM_ERR_BASE + 3
#define BP_AIN_SM_ERR_OPER_ERR           BP_AIN_SM_ERR_BASE + 4
#define BP_AIN_SM_ERR_PROTO_EP_DN        BP_AIN_SM_ERR_BASE + 5
#define BP_AIN_SM_ERR_PROTO_EP_UP        BP_AIN_SM_ERR_BASE + 6
#define BP_AIN_SM_ERR_PROTO_TMR_EXP      BP_AIN_SM_ERR_BASE + 7
                                       
// M3UA layer specific alarms.         
#define BP_AIN_SM_ERR_M3_MODE_ACT        BP_AIN_SM_ERR_BASE + 10
#define BP_AIN_SM_ERR_M3_MODE_INACT      BP_AIN_SM_ERR_BASE + 11
#define BP_AIN_SM_ERR_M3_MTP_RST_BEG     BP_AIN_SM_ERR_BASE + 12
#define BP_AIN_SM_ERR_M3_MTP_RST_END     BP_AIN_SM_ERR_BASE + 13
#define BP_AIN_SM_ERR_M3_PC_PROH         BP_AIN_SM_ERR_BASE + 14
#define BP_AIN_SM_ERR_M3_PC_AVL          BP_AIN_SM_ERR_BASE + 15
#define BP_AIN_SM_ERR_M3_PC_REST         BP_AIN_SM_ERR_BASE + 16
#define BP_AIN_SM_ERR_M3_PC_CONG         BP_AIN_SM_ERR_BASE + 17
#define BP_AIN_SM_ERR_M3_UPU             BP_AIN_SM_ERR_BASE + 18
                                         
// SCCP layer specific alarms.           
#define BP_AIN_SM_ERR_SC_RCVD_MSG_ERR    BP_AIN_SM_ERR_BASE + 20
#define BP_AIN_SM_ERR_SC_RMT_USR_UNEQ    BP_AIN_SM_ERR_BASE + 21
#define BP_AIN_SM_ERR_SC_ROUTING_ERR     BP_AIN_SM_ERR_BASE + 22
                                         
// TCAP layer specific alarms.           
#define BP_AIN_SM_ERR_TC_ENCDEC_ERR      BP_AIN_SM_ERR_BASE + 30
#define BP_AIN_SM_ERR_TC_MSG_BAD_ST      BP_AIN_SM_ERR_BASE + 31
#define BP_AIN_SM_ERR_TC_UNCFG_OK        BP_AIN_SM_ERR_BASE + 32
#define BP_AIN_SM_ERR_TC_BAD_COMPO       BP_AIN_SM_ERR_BASE + 33
                                         
// INAP layer specific alarms.           
#define BP_AIN_SM_ERR_IN_MAX_DIALOGS     BP_AIN_SM_ERR_BASE + 40
#define BP_AIN_SM_ERR_IN_MAX_OPERS       BP_AIN_SM_ERR_BASE + 41
                                         
// SCTP layer specific alarms.           
#define BP_AIN_SM_ERR_SCTP_NONE          BP_AIN_SM_ERR_BASE + 50  /* not used */

// TUCL layer specific alarms.
#define BP_AIN_SM_ERR_TUCL_DRC_START     BP_AIN_SM_ERR_BASE + 60
#define BP_AIN_SM_ERR_TUCL_DRC_DROP      BP_AIN_SM_ERR_BASE + 61
#define BP_AIN_SM_ERR_TUCL_DRC_END       BP_AIN_SM_ERR_BASE + 62
#define BP_AIN_SM_ERR_TUCL_NW_BUF_CONG   BP_AIN_SM_ERR_BASE + 63
#define BP_AIN_SM_ERR_TUCL_XTRM_CONG     BP_AIN_SM_ERR_BASE + 64
#define BP_AIN_SM_ERR_TUCL_DAT_XMIT_ERR  BP_AIN_SM_ERR_BASE + 65
#define BP_AIN_SM_ERR_TUCL_DAT_RECV_ERR  BP_AIN_SM_ERR_BASE + 66
#define BP_AIN_SM_ERR_TUCL_MAX_CONN      BP_AIN_SM_ERR_BASE + 67

/***********************************************************************
** ERROR CODES -- end
***********************************************************************/

/***********************************************************************
 * define the predefined transaction ids
 ***********************************************************************/

#define BP_AIN_SM_STS_TRANSID      3
#define BP_AIN_SM_DIST_TRANSID     4
#define BP_AIN_SM_MTP2_TRANSID     2
#define BP_AIN_SM_SG_TRANSID       5
#define BP_AIN_SM_AUDIT_TRANSID    6


/***********************************************************************
 * define the OIDs used in configure or oidChanged from CCM
 ***********************************************************************/

#define SM_SELF_PC                    ainSELF_POINTCODES
#define SM_SELF_ASPID                 ainSELF_ASP_ID
#define SM_SELF_NWTYPE                ainSELF_NWAPPEAR_LIST
#define SM_SELF_ADDRESS               ainSELF_IP_PORT_LIST
#define SM_SELF_SSN                   ainSELF_SSN_LIST
#define SM_PEER_ADDRESS               ainREMOTE_IP_PORT_LIST
#define SM_CCM_DBG_LEVEL              ainSS7STK_ALM_SWITCH
#define SM_CCM_TRC_LEVEL              ainSS7STK_TRCGEN_SWITCH
#define SM_CCM_STS_LEVEL              ainSTATS_COLL_LEVEL
#define SM_CCM_STS_TIMER              ainSS7STK_STATS_COLL_TMR
#define SM_ASP_RTE_CHANGE             ainSS7_RTE_CHNG_TRIGGER
#define SM_PDU_LOG                    ainSS7_PDU_TRC_FILE
#define SM_XML_FILE                   ainSS7_INITCFG_FILE
#define SM_ASP_SWITCHOVER             ainASP_SWITCHOVER

// these also need to go into imOid.h sometime, as they are expected
// from EMS.
#define SM_CCM_ALM_LEVEL              "8.8.11"
#define SM_CCM_ASP_UP                 "8.8.12"
#define SM_CCM_ASP_ACTIVE             "8.8.13"
#define SM_CCM_EST_ASS                "8.8.14"
// gap in oids
#define SM_CCM_ASP_INACTIVE           "8.8.26"
#define SM_CCM_ASP_DOWN               "8.8.27"
#define SM_CCM_TRM_ASS                "8.8.28"
#define SM_TIMER_RES                  "8.8.29"
#define SM_MONITOR_INTERVAL           "8.8.30"
#define SM_STACK_OUTFILE              "8.8.31"
#define SM_CCM_DUMP_MEMORY            "8.8.666"



/**
 * PDU flow direction (for Trace logging)
 */
#define BP_AIN_SM_TRCDIR_RX   0   // receive
#define BP_AIN_SM_TRCDIR_TX   1   // transmit


/*
 * Typedefs
 */

#define INGwSmGetHiByte(w)   (((U16)(w) >> 8) & 0xff)      /* get hi byte from word */
#define INGwSmGetLoByte(w)   ((U16)(w) & 0xff)             /* get lo byte from word */
#define INGwSmGetHiWord(l)   (((U32)(l) >> 16) & 0xffffL)  /* get hi word of long */
#define INGwSmGetLoWord(l)   ((U32)(l) & 0xffffL)          /* get lo word of long */

typedef int INGwSmPeerId;

typedef struct
{
  INGwSmPeerId peerId;
  long address;
  int port;
} INGwSmAddress;

typedef std::vector<INGwSmAddress*> AddressVector;

typedef int INGwSmPc;

typedef int INGwSmSsn;

typedef struct {
  INGwSmSsn ssn;
  int ssnStatus;
  int ssnBackup;
} INGwSmDestRoute;

typedef struct _PspState {
  int state;
  int monitor;
} INGwSmPspState;

typedef int INGwSmPsId;

typedef int INGwSmPspId;

//oid structure used in statistics
typedef struct {
  char oidString[20];
  int  layer;
  int  operation;
  int  element;
  int  level;
  int  index;
  long  stsValue;
  long  prevValue;
} INGwSmStsOid;


typedef std::vector<INGwSmStsOid*> INGwSmStsOidList;

typedef std::vector<int> INGwSmIntVector;

#if 0
//the context used for blocking the thread to make the operation
//synchronous. The return Value is set by the INGwSmRequest.
typedef struct {
  int returnValue;
  int requestId; //cud be the threadId
} INGwSmBlockingContext;
#endif

/*
 * This structure will have the request Context like PSP id etc
 * and is passed from Distributor to the INGwSmRequest Object
 */
typedef struct _INGwSmRequestContext {
  int pspId;
} INGwSmRequestContext;

struct INGwSmLinkInfo
{
  int sapId;
  int opc;
  int dpc;
  int channelNum;
  int linkSetId;
  int devId;
};


/**
 * this structure encapsulates the PDU trace information
 * NOTE: this is a variable length structure
 */
typedef struct _INGwSmTrcInfo {

  int miLayerId;      // layer generating PDU trace
  int miSubLayerId;   // sublayer generating PDU trace
  int miDir;          // RX/TX

  unsigned char hour; // generation time stamp
  unsigned char min;
  unsigned char sec;
  unsigned char tenth;

  int   miTrcLen;     // length of trace info
  char  maTrcBuf[1];  // variable length trace buffer array

} INGwSmTrcInfo;

#endif /* __BP_AINSMCOMMON_H__ */
