
package com.agnity.win.asngenerated;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1BoxedType ( name = "AddService" )
    public class AddService implements IASN1PreparedElement {
                
        

       @ASN1PreparedElement
       @ASN1Sequence ( name = "AddService" , isSet = true )
       public static class AddServiceSequenceType implements IASN1PreparedElement {
                
        @ASN1Element ( name = "cdmaConnectionReferenceList", isOptional =  true , hasTag =  true, tag = 212 , hasDefaultValue =  false  )
    
	private CDMAConnectionReferenceList cdmaConnectionReferenceList = null;
                
  
        @ASN1Element ( name = "cdmaServiceOptionList", isOptional =  true , hasTag =  true, tag = 176 , hasDefaultValue =  false  )
    
	private CDMAServiceOptionList cdmaServiceOptionList = null;
                
  
        @ASN1Element ( name = "digits", isOptional =  true , hasTag =  true, tag = 4 , hasDefaultValue =  false  )
    
	private Digits digits = null;
                
  
        @ASN1Element ( name = "interMSCCircuitID", isOptional =  true , hasTag =  true, tag = 6 , hasDefaultValue =  false  )
    
	private InterMSCCircuitID interMSCCircuitID = null;
                
  
        @ASN1Element ( name = "imsi", isOptional =  true , hasTag =  true, tag = 242 , hasDefaultValue =  false  )
    
	private IMSI imsi = null;
                
  
        @ASN1Element ( name = "mobileIdentificationNumber", isOptional =  true , hasTag =  true, tag = 8 , hasDefaultValue =  false  )
    
	private MobileIdentificationNumber mobileIdentificationNumber = null;
                
  
        
        public CDMAConnectionReferenceList getCdmaConnectionReferenceList () {
            return this.cdmaConnectionReferenceList;
        }

        
        public boolean isCdmaConnectionReferenceListPresent () {
            return this.cdmaConnectionReferenceList != null;
        }
        

        public void setCdmaConnectionReferenceList (CDMAConnectionReferenceList value) {
            this.cdmaConnectionReferenceList = value;
        }
        
  
        
        public CDMAServiceOptionList getCdmaServiceOptionList () {
            return this.cdmaServiceOptionList;
        }

        
        public boolean isCdmaServiceOptionListPresent () {
            return this.cdmaServiceOptionList != null;
        }
        

        public void setCdmaServiceOptionList (CDMAServiceOptionList value) {
            this.cdmaServiceOptionList = value;
        }
        
  
        
        public Digits getDigits () {
            return this.digits;
        }

        
        public boolean isDigitsPresent () {
            return this.digits != null;
        }
        

        public void setDigits (Digits value) {
            this.digits = value;
        }
        
  
        
        public InterMSCCircuitID getInterMSCCircuitID () {
            return this.interMSCCircuitID;
        }

        
        public boolean isInterMSCCircuitIDPresent () {
            return this.interMSCCircuitID != null;
        }
        

        public void setInterMSCCircuitID (InterMSCCircuitID value) {
            this.interMSCCircuitID = value;
        }
        
  
        
        public IMSI getImsi () {
            return this.imsi;
        }

        
        public boolean isImsiPresent () {
            return this.imsi != null;
        }
        

        public void setImsi (IMSI value) {
            this.imsi = value;
        }
        
  
        
        public MobileIdentificationNumber getMobileIdentificationNumber () {
            return this.mobileIdentificationNumber;
        }

        
        public boolean isMobileIdentificationNumberPresent () {
            return this.mobileIdentificationNumber != null;
        }
        

        public void setMobileIdentificationNumber (MobileIdentificationNumber value) {
            this.mobileIdentificationNumber = value;
        }
        
  
                
                
        public void initWithDefaults() {
            
        }

        public IASN1PreparedElementData getPreparedData() {
            return preparedData_AddServiceSequenceType;
        }

       private static IASN1PreparedElementData preparedData_AddServiceSequenceType = CoderFactory.getInstance().newPreparedElementData(AddServiceSequenceType.class);
                
       }

       
                
        @ASN1Element ( name = "AddService", isOptional =  false , hasTag =  true, tag = 18, 
        tagClass =  TagClass.Private  , hasDefaultValue =  false  )
    
        private AddServiceSequenceType  value;        

        
        
        public AddService () {
        }
        
        
        
        public void setValue(AddServiceSequenceType value) {
            this.value = value;
        }
        
        
        
        public AddServiceSequenceType getValue() {
            return this.value;
        }            
        

	    public void initWithDefaults() {
	    }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(AddService.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            