
package com.agnity.win.asngenerated;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Sequence ( name = "AnnouncementList", isSet = false )
    public class AnnouncementList implements IASN1PreparedElement {
            
        @ASN1Element ( name = "announcementCode1", isOptional =  false , hasTag =  true, tag = 76 , hasDefaultValue =  false  )
    
	private AnnouncementCode announcementCode1 = null;
                
  
        @ASN1Element ( name = "announcementCode2", isOptional =  true , hasTag =  true, tag = 76 , hasDefaultValue =  false  )
    
	private AnnouncementCode announcementCode2 = null;
                
  
        
        public AnnouncementCode getAnnouncementCode1 () {
            return this.announcementCode1;
        }

        

        public void setAnnouncementCode1 (AnnouncementCode value) {
            this.announcementCode1 = value;
        }
        
  
        
        public AnnouncementCode getAnnouncementCode2 () {
            return this.announcementCode2;
        }

        
        public boolean isAnnouncementCode2Present () {
            return this.announcementCode2 != null;
        }
        

        public void setAnnouncementCode2 (AnnouncementCode value) {
            this.announcementCode2 = value;
        }
        
  
                    
        
        public void initWithDefaults() {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(AnnouncementList.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            