
package com.agnity.win.asngenerated;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1BoxedType ( name = "BulkDeregistration" )
    public class BulkDeregistration implements IASN1PreparedElement {
                
        

       @ASN1PreparedElement
       @ASN1Sequence ( name = "BulkDeregistration" , isSet = true )
       public static class BulkDeregistrationSequenceType implements IASN1PreparedElement {
                
        @ASN1Element ( name = "senderIdentificationNumber", isOptional =  true , hasTag =  true, tag = 103 , hasDefaultValue =  false  )
    
	private SenderIdentificationNumber senderIdentificationNumber = null;
                
  
        
        public SenderIdentificationNumber getSenderIdentificationNumber () {
            return this.senderIdentificationNumber;
        }

        
        public boolean isSenderIdentificationNumberPresent () {
            return this.senderIdentificationNumber != null;
        }
        

        public void setSenderIdentificationNumber (SenderIdentificationNumber value) {
            this.senderIdentificationNumber = value;
        }
        
  
                
                
        public void initWithDefaults() {
            
        }

        public IASN1PreparedElementData getPreparedData() {
            return preparedData_BulkDeregistrationSequenceType;
        }

       private static IASN1PreparedElementData preparedData_BulkDeregistrationSequenceType = CoderFactory.getInstance().newPreparedElementData(BulkDeregistrationSequenceType.class);
                
       }

       
                
        @ASN1Element ( name = "BulkDeregistration", isOptional =  false , hasTag =  true, tag = 18, 
        tagClass =  TagClass.Private  , hasDefaultValue =  false  )
    
        private BulkDeregistrationSequenceType  value;        

        
        
        public BulkDeregistration () {
        }
        
        
        
        public void setValue(BulkDeregistrationSequenceType value) {
            this.value = value;
        }
        
        
        
        public BulkDeregistrationSequenceType getValue() {
            return this.value;
        }            
        

	    public void initWithDefaults() {
	    }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(BulkDeregistration.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            