
package com.agnity.win.asngenerated;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Sequence ( name = "CDMATargetMAHOInformation", isSet = false )
    public class CDMATargetMAHOInformation implements IASN1PreparedElement {
            
        @ASN1Element ( name = "targetCellID", isOptional =  false , hasTag =  true, tag = 3 , hasDefaultValue =  false  )
    
	private TargetCellID targetCellID = null;
                
  
        @ASN1Element ( name = "cdmaPilotStrength", isOptional =  false , hasTag =  true, tag = 65 , hasDefaultValue =  false  )
    
	private CDMAPilotStrength cdmaPilotStrength = null;
                
  
        @ASN1Element ( name = "cdmaTargetOneWayDelay", isOptional =  false , hasTag =  true, tag = 61 , hasDefaultValue =  false  )
    
	private CDMATargetOneWayDelay cdmaTargetOneWayDelay = null;
                
  
        
        public TargetCellID getTargetCellID () {
            return this.targetCellID;
        }

        

        public void setTargetCellID (TargetCellID value) {
            this.targetCellID = value;
        }
        
  
        
        public CDMAPilotStrength getCdmaPilotStrength () {
            return this.cdmaPilotStrength;
        }

        

        public void setCdmaPilotStrength (CDMAPilotStrength value) {
            this.cdmaPilotStrength = value;
        }
        
  
        
        public CDMATargetOneWayDelay getCdmaTargetOneWayDelay () {
            return this.cdmaTargetOneWayDelay;
        }

        

        public void setCdmaTargetOneWayDelay (CDMATargetOneWayDelay value) {
            this.cdmaTargetOneWayDelay = value;
        }
        
  
                    
        
        public void initWithDefaults() {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(CDMATargetMAHOInformation.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            