
package com.agnity.win.asngenerated;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1BoxedType ( name = "DataAccessElementList" )
    public class DataAccessElementList implements IASN1PreparedElement {
                
            

       @ASN1PreparedElement
       @ASN1Sequence ( name = "DataAccessElementList" , isSet = false )
       public static class DataAccessElementListSequenceType implements IASN1PreparedElement {
                
        @ASN1Element ( name = "dataAccessElement1", isOptional =  false , hasTag =  true, tag = 249 , hasDefaultValue =  false  )
    
	private DataAccessElement dataAccessElement1 = null;
                
  
        @ASN1Element ( name = "dataAccessElement2", isOptional =  true , hasTag =  true, tag = 249 , hasDefaultValue =  false  )
    
	private DataAccessElement dataAccessElement2 = null;
                
  
        
        public DataAccessElement getDataAccessElement1 () {
            return this.dataAccessElement1;
        }

        

        public void setDataAccessElement1 (DataAccessElement value) {
            this.dataAccessElement1 = value;
        }
        
  
        
        public DataAccessElement getDataAccessElement2 () {
            return this.dataAccessElement2;
        }

        
        public boolean isDataAccessElement2Present () {
            return this.dataAccessElement2 != null;
        }
        

        public void setDataAccessElement2 (DataAccessElement value) {
            this.dataAccessElement2 = value;
        }
        
  
                
                
        public void initWithDefaults() {
            
        }

        public IASN1PreparedElementData getPreparedData() {
            return preparedData_DataAccessElementListSequenceType;
        }

       private static IASN1PreparedElementData preparedData_DataAccessElementListSequenceType = CoderFactory.getInstance().newPreparedElementData(DataAccessElementListSequenceType.class);
                
       }

       
                
            @ASN1SequenceOf( name = "DataAccessElementList" , isSetOf = false)
	    private java.util.Collection<DataAccessElementListSequenceType> value = null; 
    
            public DataAccessElementList () {
            }
        
            public DataAccessElementList ( java.util.Collection<DataAccessElementListSequenceType> value ) {
                setValue(value);
            }
                        
            public void setValue(java.util.Collection<DataAccessElementListSequenceType> value) {
                this.value = value;
            }
            
            public java.util.Collection<DataAccessElementListSequenceType> getValue() {
                return this.value;
            }            
            
            public void initValue() {
                setValue(new java.util.LinkedList<DataAccessElementListSequenceType>()); 
            }
            
            public void add(DataAccessElementListSequenceType item) {
                value.add(item);
            }

	    public void initWithDefaults() {
	    }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(DataAccessElementList.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }


    }
            