
package com.agnity.win.asngenerated;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1BoxedType ( name = "FacilitiesRelease" )
    public class FacilitiesRelease implements IASN1PreparedElement {
                
        

       @ASN1PreparedElement
       @ASN1Sequence ( name = "FacilitiesRelease" , isSet = true )
       public static class FacilitiesReleaseSequenceType implements IASN1PreparedElement {
                
        @ASN1Element ( name = "interMSCCircuitID", isOptional =  false , hasTag =  true, tag = 6 , hasDefaultValue =  false  )
    
	private InterMSCCircuitID interMSCCircuitID = null;
                
  
        @ASN1Element ( name = "releaseReason", isOptional =  false , hasTag =  true, tag = 10 , hasDefaultValue =  false  )
    
	private ReleaseReason releaseReason = null;
                
  
        @ASN1Element ( name = "billingID", isOptional =  true , hasTag =  true, tag = 1 , hasDefaultValue =  false  )
    
	private BillingID billingID = null;
                
  
        @ASN1Element ( name = "mobileIdentificationNumber", isOptional =  true , hasTag =  true, tag = 8 , hasDefaultValue =  false  )
    
	private MobileIdentificationNumber mobileIdentificationNumber = null;
                
  
        
        public InterMSCCircuitID getInterMSCCircuitID () {
            return this.interMSCCircuitID;
        }

        

        public void setInterMSCCircuitID (InterMSCCircuitID value) {
            this.interMSCCircuitID = value;
        }
        
  
        
        public ReleaseReason getReleaseReason () {
            return this.releaseReason;
        }

        

        public void setReleaseReason (ReleaseReason value) {
            this.releaseReason = value;
        }
        
  
        
        public BillingID getBillingID () {
            return this.billingID;
        }

        
        public boolean isBillingIDPresent () {
            return this.billingID != null;
        }
        

        public void setBillingID (BillingID value) {
            this.billingID = value;
        }
        
  
        
        public MobileIdentificationNumber getMobileIdentificationNumber () {
            return this.mobileIdentificationNumber;
        }

        
        public boolean isMobileIdentificationNumberPresent () {
            return this.mobileIdentificationNumber != null;
        }
        

        public void setMobileIdentificationNumber (MobileIdentificationNumber value) {
            this.mobileIdentificationNumber = value;
        }
        
  
                
                
        public void initWithDefaults() {
            
        }

        public IASN1PreparedElementData getPreparedData() {
            return preparedData_FacilitiesReleaseSequenceType;
        }

       private static IASN1PreparedElementData preparedData_FacilitiesReleaseSequenceType = CoderFactory.getInstance().newPreparedElementData(FacilitiesReleaseSequenceType.class);
                
       }

       
                
        @ASN1Element ( name = "FacilitiesRelease", isOptional =  false , hasTag =  true, tag = 18, 
        tagClass =  TagClass.Private  , hasDefaultValue =  false  )
    
        private FacilitiesReleaseSequenceType  value;        

        
        
        public FacilitiesRelease () {
        }
        
        
        
        public void setValue(FacilitiesReleaseSequenceType value) {
            this.value = value;
        }
        
        
        
        public FacilitiesReleaseSequenceType getValue() {
            return this.value;
        }            
        

	    public void initWithDefaults() {
	    }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(FacilitiesRelease.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            