
package com.agnity.win.asngenerated;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1BoxedType ( name = "ODisconnect" )
    public class ODisconnect implements IASN1PreparedElement {
                
        

       @ASN1PreparedElement
       @ASN1Sequence ( name = "ODisconnect" , isSet = true )
       public static class ODisconnectSequenceType implements IASN1PreparedElement {
                
        @ASN1Element ( name = "billingID", isOptional =  false , hasTag =  true, tag = 1 , hasDefaultValue =  false  )
    
	private BillingID billingID = null;
                
  
        @ASN1Element ( name = "electronicSerialNumber", isOptional =  true , hasTag =  true, tag = 9 , hasDefaultValue =  false  )
    
	private ElectronicSerialNumber electronicSerialNumber = null;
                
  
        @ASN1Element ( name = "mscid", isOptional =  false , hasTag =  true, tag = 21 , hasDefaultValue =  false  )
    
	private MSCID mscid = null;
                
  
        @ASN1Element ( name = "msid", isOptional =  true , hasTag =  false  , hasDefaultValue =  false  )
    
	private MSID msid = null;
                
  
        @ASN1Element ( name = "releaseCause", isOptional =  true , hasTag =  true, tag = 308 , hasDefaultValue =  false  )
    
	private ReleaseCause releaseCause = null;
                
  
        @ASN1Element ( name = "timeDateOffset", isOptional =  true , hasTag =  true, tag = 275 , hasDefaultValue =  false  )
    
	private TimeDateOffset timeDateOffset = null;
                
  
        @ASN1Element ( name = "timeOfDay", isOptional =  false , hasTag =  true, tag = 309 , hasDefaultValue =  false  )
    
	private TimeOfDay timeOfDay = null;
                
  
        @ASN1Element ( name = "transactionCapability", isOptional =  false , hasTag =  true, tag = 123 , hasDefaultValue =  false  )
    
	private TransactionCapability transactionCapability = null;
                
  
        @ASN1Element ( name = "winCapability", isOptional =  false , hasTag =  true, tag = 280 , hasDefaultValue =  false  )
    
	private WINCapability winCapability = null;
                
  
        @ASN1Element ( name = "triggerType", isOptional =  false , hasTag =  true, tag = 279 , hasDefaultValue =  false  )
    
	private TriggerType triggerType = null;
                
  
        @ASN1Element ( name = "locationAreaID", isOptional =  true , hasTag =  true, tag = 33 , hasDefaultValue =  false  )
    
	private LocationAreaID locationAreaID = null;
                
  
        @ASN1Element ( name = "mobileDirectoryNumber", isOptional =  true , hasTag =  true, tag = 93 , hasDefaultValue =  false  )
    
	private MobileDirectoryNumber mobileDirectoryNumber = null;
                
  
        @ASN1Element ( name = "mSCIdentificationNumber", isOptional =  true , hasTag =  true, tag = 94 , hasDefaultValue =  false  )
    
	private MSCIdentificationNumber mSCIdentificationNumber = null;
                
  
        @ASN1Element ( name = "servingCellID", isOptional =  true , hasTag =  true, tag = 2 , hasDefaultValue =  false  )
    
	private ServingCellID servingCellID = null;
                
  
        @ASN1Element ( name = "systemMyTypeCode", isOptional =  true , hasTag =  true, tag = 22 , hasDefaultValue =  false  )
    
	private SystemMyTypeCode systemMyTypeCode = null;
                
  
        
        public BillingID getBillingID () {
            return this.billingID;
        }

        

        public void setBillingID (BillingID value) {
            this.billingID = value;
        }
        
  
        
        public ElectronicSerialNumber getElectronicSerialNumber () {
            return this.electronicSerialNumber;
        }

        
        public boolean isElectronicSerialNumberPresent () {
            return this.electronicSerialNumber != null;
        }
        

        public void setElectronicSerialNumber (ElectronicSerialNumber value) {
            this.electronicSerialNumber = value;
        }
        
  
        
        public MSCID getMscid () {
            return this.mscid;
        }

        

        public void setMscid (MSCID value) {
            this.mscid = value;
        }
        
  
        
        public MSID getMsid () {
            return this.msid;
        }

        
        public boolean isMsidPresent () {
            return this.msid != null;
        }
        

        public void setMsid (MSID value) {
            this.msid = value;
        }
        
  
        
        public ReleaseCause getReleaseCause () {
            return this.releaseCause;
        }

        
        public boolean isReleaseCausePresent () {
            return this.releaseCause != null;
        }
        

        public void setReleaseCause (ReleaseCause value) {
            this.releaseCause = value;
        }
        
  
        
        public TimeDateOffset getTimeDateOffset () {
            return this.timeDateOffset;
        }

        
        public boolean isTimeDateOffsetPresent () {
            return this.timeDateOffset != null;
        }
        

        public void setTimeDateOffset (TimeDateOffset value) {
            this.timeDateOffset = value;
        }
        
  
        
        public TimeOfDay getTimeOfDay () {
            return this.timeOfDay;
        }

        

        public void setTimeOfDay (TimeOfDay value) {
            this.timeOfDay = value;
        }
        
  
        
        public TransactionCapability getTransactionCapability () {
            return this.transactionCapability;
        }

        

        public void setTransactionCapability (TransactionCapability value) {
            this.transactionCapability = value;
        }
        
  
        
        public WINCapability getWinCapability () {
            return this.winCapability;
        }

        

        public void setWinCapability (WINCapability value) {
            this.winCapability = value;
        }
        
  
        
        public TriggerType getTriggerType () {
            return this.triggerType;
        }

        

        public void setTriggerType (TriggerType value) {
            this.triggerType = value;
        }
        
  
        
        public LocationAreaID getLocationAreaID () {
            return this.locationAreaID;
        }

        
        public boolean isLocationAreaIDPresent () {
            return this.locationAreaID != null;
        }
        

        public void setLocationAreaID (LocationAreaID value) {
            this.locationAreaID = value;
        }
        
  
        
        public MobileDirectoryNumber getMobileDirectoryNumber () {
            return this.mobileDirectoryNumber;
        }

        
        public boolean isMobileDirectoryNumberPresent () {
            return this.mobileDirectoryNumber != null;
        }
        

        public void setMobileDirectoryNumber (MobileDirectoryNumber value) {
            this.mobileDirectoryNumber = value;
        }
        
  
        
        public MSCIdentificationNumber getMSCIdentificationNumber () {
            return this.mSCIdentificationNumber;
        }

        
        public boolean isMSCIdentificationNumberPresent () {
            return this.mSCIdentificationNumber != null;
        }
        

        public void setMSCIdentificationNumber (MSCIdentificationNumber value) {
            this.mSCIdentificationNumber = value;
        }
        
  
        
        public ServingCellID getServingCellID () {
            return this.servingCellID;
        }

        
        public boolean isServingCellIDPresent () {
            return this.servingCellID != null;
        }
        

        public void setServingCellID (ServingCellID value) {
            this.servingCellID = value;
        }
        
  
        
        public SystemMyTypeCode getSystemMyTypeCode () {
            return this.systemMyTypeCode;
        }

        
        public boolean isSystemMyTypeCodePresent () {
            return this.systemMyTypeCode != null;
        }
        

        public void setSystemMyTypeCode (SystemMyTypeCode value) {
            this.systemMyTypeCode = value;
        }
        
  
                
                
        public void initWithDefaults() {
            
        }

        public IASN1PreparedElementData getPreparedData() {
            return preparedData_ODisconnectSequenceType;
        }

       private static IASN1PreparedElementData preparedData_ODisconnectSequenceType = CoderFactory.getInstance().newPreparedElementData(ODisconnectSequenceType.class);
                
       }

       
                
        @ASN1Element ( name = "ODisconnect", isOptional =  false , hasTag =  true, tag = 18, 
        tagClass =  TagClass.Private  , hasDefaultValue =  false  )
    
        private ODisconnectSequenceType  value;        

        
        
        public ODisconnect () {
        }
        
        
        
        public void setValue(ODisconnectSequenceType value) {
            this.value = value;
        }
        
        
        
        public ODisconnectSequenceType getValue() {
            return this.value;
        }            
        

	    public void initWithDefaults() {
	    }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(ODisconnect.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            