
package com.agnity.win.asngenerated;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1BoxedType ( name = "ONoAnswer" )
    public class ONoAnswer implements IASN1PreparedElement {
                
        

       @ASN1PreparedElement
       @ASN1Sequence ( name = "ONoAnswer" , isSet = true )
       public static class ONoAnswerSequenceType implements IASN1PreparedElement {
                
        @ASN1Element ( name = "billingID", isOptional =  false , hasTag =  true, tag = 1 , hasDefaultValue =  false  )
    
	private BillingID billingID = null;
                
  
        @ASN1Element ( name = "electronicSerialNumber", isOptional =  true , hasTag =  true, tag = 9 , hasDefaultValue =  false  )
    
	private ElectronicSerialNumber electronicSerialNumber = null;
                
  
        @ASN1Element ( name = "mscid", isOptional =  false , hasTag =  true, tag = 21 , hasDefaultValue =  false  )
    
	private MSCID mscid = null;
                
  
        @ASN1Element ( name = "msid", isOptional =  true , hasTag =  false  , hasDefaultValue =  false  )
    
	private MSID msid = null;
                
  
        @ASN1Element ( name = "transactionCapability", isOptional =  false , hasTag =  true, tag = 123 , hasDefaultValue =  false  )
    
	private TransactionCapability transactionCapability = null;
                
  
        @ASN1Element ( name = "triggerType", isOptional =  false , hasTag =  true, tag = 279 , hasDefaultValue =  false  )
    
	private TriggerType triggerType = null;
                
  
        @ASN1Element ( name = "winCapability", isOptional =  false , hasTag =  true, tag = 280 , hasDefaultValue =  false  )
    
	private WINCapability winCapability = null;
                
  
        @ASN1Element ( name = "callingPartyName", isOptional =  true , hasTag =  true, tag = 243 , hasDefaultValue =  false  )
    
	private CallingPartyName callingPartyName = null;
                
  
        @ASN1Element ( name = "callingPartyNumberDigits1", isOptional =  true , hasTag =  true, tag = 80 , hasDefaultValue =  false  )
    
	private CallingPartyNumberDigits1 callingPartyNumberDigits1 = null;
                
  
        @ASN1Element ( name = "callingPartyNumberDigits2", isOptional =  true , hasTag =  true, tag = 81 , hasDefaultValue =  false  )
    
	private CallingPartyNumberDigits2 callingPartyNumberDigits2 = null;
                
  
        @ASN1Element ( name = "callingPartySubaddress", isOptional =  true , hasTag =  true, tag = 84 , hasDefaultValue =  false  )
    
	private CallingPartySubaddress callingPartySubaddress = null;
                
  
        @ASN1Element ( name = "carrierDigits", isOptional =  true , hasTag =  true, tag = 86 , hasDefaultValue =  false  )
    
	private CarrierDigits carrierDigits = null;
                
  
        @ASN1Element ( name = "destinationDigits", isOptional =  true , hasTag =  true, tag = 87 , hasDefaultValue =  false  )
    
	private DestinationDigits destinationDigits = null;
                
  
        @ASN1Element ( name = "digits", isOptional =  true , hasTag =  true, tag = 4 , hasDefaultValue =  false  )
    
	private Digits digits = null;
                
  
        @ASN1Element ( name = "locationAreaID", isOptional =  true , hasTag =  true, tag = 33 , hasDefaultValue =  false  )
    
	private LocationAreaID locationAreaID = null;
                
  
        @ASN1Element ( name = "mobileDirectoryNumber", isOptional =  true , hasTag =  true, tag = 93 , hasDefaultValue =  false  )
    
	private MobileDirectoryNumber mobileDirectoryNumber = null;
                
  
        @ASN1Element ( name = "mSCIdentificationNumber", isOptional =  true , hasTag =  true, tag = 94 , hasDefaultValue =  false  )
    
	private MSCIdentificationNumber mSCIdentificationNumber = null;
                
  
        @ASN1Element ( name = "pc-ssn", isOptional =  true , hasTag =  true, tag = 32 , hasDefaultValue =  false  )
    
	private PC_SSN pc_ssn = null;
                
  
        @ASN1Element ( name = "redirectingNumberDigits", isOptional =  true , hasTag =  true, tag = 100 , hasDefaultValue =  false  )
    
	private RedirectingNumberDigits redirectingNumberDigits = null;
                
  
        @ASN1Element ( name = "redirectingPartyName", isOptional =  true , hasTag =  true, tag = 245 , hasDefaultValue =  false  )
    
	private RedirectingPartyName redirectingPartyName = null;
                
  
        @ASN1Element ( name = "routingDigits", isOptional =  true , hasTag =  true, tag = 150 , hasDefaultValue =  false  )
    
	private RoutingDigits routingDigits = null;
                
  
        @ASN1Element ( name = "servingCellID", isOptional =  true , hasTag =  true, tag = 2 , hasDefaultValue =  false  )
    
	private ServingCellID servingCellID = null;
                
  
        
        public BillingID getBillingID () {
            return this.billingID;
        }

        

        public void setBillingID (BillingID value) {
            this.billingID = value;
        }
        
  
        
        public ElectronicSerialNumber getElectronicSerialNumber () {
            return this.electronicSerialNumber;
        }

        
        public boolean isElectronicSerialNumberPresent () {
            return this.electronicSerialNumber != null;
        }
        

        public void setElectronicSerialNumber (ElectronicSerialNumber value) {
            this.electronicSerialNumber = value;
        }
        
  
        
        public MSCID getMscid () {
            return this.mscid;
        }

        

        public void setMscid (MSCID value) {
            this.mscid = value;
        }
        
  
        
        public MSID getMsid () {
            return this.msid;
        }

        
        public boolean isMsidPresent () {
            return this.msid != null;
        }
        

        public void setMsid (MSID value) {
            this.msid = value;
        }
        
  
        
        public TransactionCapability getTransactionCapability () {
            return this.transactionCapability;
        }

        

        public void setTransactionCapability (TransactionCapability value) {
            this.transactionCapability = value;
        }
        
  
        
        public TriggerType getTriggerType () {
            return this.triggerType;
        }

        

        public void setTriggerType (TriggerType value) {
            this.triggerType = value;
        }
        
  
        
        public WINCapability getWinCapability () {
            return this.winCapability;
        }

        

        public void setWinCapability (WINCapability value) {
            this.winCapability = value;
        }
        
  
        
        public CallingPartyName getCallingPartyName () {
            return this.callingPartyName;
        }

        
        public boolean isCallingPartyNamePresent () {
            return this.callingPartyName != null;
        }
        

        public void setCallingPartyName (CallingPartyName value) {
            this.callingPartyName = value;
        }
        
  
        
        public CallingPartyNumberDigits1 getCallingPartyNumberDigits1 () {
            return this.callingPartyNumberDigits1;
        }

        
        public boolean isCallingPartyNumberDigits1Present () {
            return this.callingPartyNumberDigits1 != null;
        }
        

        public void setCallingPartyNumberDigits1 (CallingPartyNumberDigits1 value) {
            this.callingPartyNumberDigits1 = value;
        }
        
  
        
        public CallingPartyNumberDigits2 getCallingPartyNumberDigits2 () {
            return this.callingPartyNumberDigits2;
        }

        
        public boolean isCallingPartyNumberDigits2Present () {
            return this.callingPartyNumberDigits2 != null;
        }
        

        public void setCallingPartyNumberDigits2 (CallingPartyNumberDigits2 value) {
            this.callingPartyNumberDigits2 = value;
        }
        
  
        
        public CallingPartySubaddress getCallingPartySubaddress () {
            return this.callingPartySubaddress;
        }

        
        public boolean isCallingPartySubaddressPresent () {
            return this.callingPartySubaddress != null;
        }
        

        public void setCallingPartySubaddress (CallingPartySubaddress value) {
            this.callingPartySubaddress = value;
        }
        
  
        
        public CarrierDigits getCarrierDigits () {
            return this.carrierDigits;
        }

        
        public boolean isCarrierDigitsPresent () {
            return this.carrierDigits != null;
        }
        

        public void setCarrierDigits (CarrierDigits value) {
            this.carrierDigits = value;
        }
        
  
        
        public DestinationDigits getDestinationDigits () {
            return this.destinationDigits;
        }

        
        public boolean isDestinationDigitsPresent () {
            return this.destinationDigits != null;
        }
        

        public void setDestinationDigits (DestinationDigits value) {
            this.destinationDigits = value;
        }
        
  
        
        public Digits getDigits () {
            return this.digits;
        }

        
        public boolean isDigitsPresent () {
            return this.digits != null;
        }
        

        public void setDigits (Digits value) {
            this.digits = value;
        }
        
  
        
        public LocationAreaID getLocationAreaID () {
            return this.locationAreaID;
        }

        
        public boolean isLocationAreaIDPresent () {
            return this.locationAreaID != null;
        }
        

        public void setLocationAreaID (LocationAreaID value) {
            this.locationAreaID = value;
        }
        
  
        
        public MobileDirectoryNumber getMobileDirectoryNumber () {
            return this.mobileDirectoryNumber;
        }

        
        public boolean isMobileDirectoryNumberPresent () {
            return this.mobileDirectoryNumber != null;
        }
        

        public void setMobileDirectoryNumber (MobileDirectoryNumber value) {
            this.mobileDirectoryNumber = value;
        }
        
  
        
        public MSCIdentificationNumber getMSCIdentificationNumber () {
            return this.mSCIdentificationNumber;
        }

        
        public boolean isMSCIdentificationNumberPresent () {
            return this.mSCIdentificationNumber != null;
        }
        

        public void setMSCIdentificationNumber (MSCIdentificationNumber value) {
            this.mSCIdentificationNumber = value;
        }
        
  
        
        public PC_SSN getPc_ssn () {
            return this.pc_ssn;
        }

        
        public boolean isPc_ssnPresent () {
            return this.pc_ssn != null;
        }
        

        public void setPc_ssn (PC_SSN value) {
            this.pc_ssn = value;
        }
        
  
        
        public RedirectingNumberDigits getRedirectingNumberDigits () {
            return this.redirectingNumberDigits;
        }

        
        public boolean isRedirectingNumberDigitsPresent () {
            return this.redirectingNumberDigits != null;
        }
        

        public void setRedirectingNumberDigits (RedirectingNumberDigits value) {
            this.redirectingNumberDigits = value;
        }
        
  
        
        public RedirectingPartyName getRedirectingPartyName () {
            return this.redirectingPartyName;
        }

        
        public boolean isRedirectingPartyNamePresent () {
            return this.redirectingPartyName != null;
        }
        

        public void setRedirectingPartyName (RedirectingPartyName value) {
            this.redirectingPartyName = value;
        }
        
  
        
        public RoutingDigits getRoutingDigits () {
            return this.routingDigits;
        }

        
        public boolean isRoutingDigitsPresent () {
            return this.routingDigits != null;
        }
        

        public void setRoutingDigits (RoutingDigits value) {
            this.routingDigits = value;
        }
        
  
        
        public ServingCellID getServingCellID () {
            return this.servingCellID;
        }

        
        public boolean isServingCellIDPresent () {
            return this.servingCellID != null;
        }
        

        public void setServingCellID (ServingCellID value) {
            this.servingCellID = value;
        }
        
  
                
                
        public void initWithDefaults() {
            
        }

        public IASN1PreparedElementData getPreparedData() {
            return preparedData_ONoAnswerSequenceType;
        }

       private static IASN1PreparedElementData preparedData_ONoAnswerSequenceType = CoderFactory.getInstance().newPreparedElementData(ONoAnswerSequenceType.class);
                
       }

       
                
        @ASN1Element ( name = "ONoAnswer", isOptional =  false , hasTag =  true, tag = 18, 
        tagClass =  TagClass.Private  , hasDefaultValue =  false  )
    
        private ONoAnswerSequenceType  value;        

        
        
        public ONoAnswer () {
        }
        
        
        
        public void setValue(ONoAnswerSequenceType value) {
            this.value = value;
        }
        
        
        
        public ONoAnswerSequenceType getValue() {
            return this.value;
        }            
        

	    public void initWithDefaults() {
	    }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(ONoAnswer.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            