
package com.agnity.win.asngenerated;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1BoxedType ( name = "OTASPRequest" )
    public class OTASPRequest implements IASN1PreparedElement {
                
        

       @ASN1PreparedElement
       @ASN1Sequence ( name = "OTASPRequest" , isSet = true )
       public static class OTASPRequestSequenceType implements IASN1PreparedElement {
                
        @ASN1Element ( name = "actionCode", isOptional =  true , hasTag =  true, tag = 128 , hasDefaultValue =  false  )
    
	private ActionCode actionCode = null;
                
  
        @ASN1Element ( name = "aKeyProtocolVersion", isOptional =  true , hasTag =  true, tag = 181 , hasDefaultValue =  false  )
    
	private AKeyProtocolVersion aKeyProtocolVersion = null;
                
  
        @ASN1Element ( name = "authenticationData", isOptional =  true , hasTag =  true, tag = 161 , hasDefaultValue =  false  )
    
	private AuthenticationData authenticationData = null;
                
  
        @ASN1Element ( name = "authenticationResponse", isOptional =  true , hasTag =  true, tag = 35 , hasDefaultValue =  false  )
    
	private AuthenticationResponse authenticationResponse = null;
                
  
        @ASN1Element ( name = "callHistoryCount", isOptional =  true , hasTag =  true, tag = 38 , hasDefaultValue =  false  )
    
	private CallHistoryCount callHistoryCount = null;
                
  
        @ASN1Element ( name = "electronicSerialNumber", isOptional =  true , hasTag =  true, tag = 9 , hasDefaultValue =  false  )
    
	private ElectronicSerialNumber electronicSerialNumber = null;
                
  
        @ASN1Element ( name = "msid", isOptional =  true , hasTag =  false  , hasDefaultValue =  false  )
    
	private MSID msid = null;
                
  
        @ASN1Element ( name = "mobileStationMSID", isOptional =  true , hasTag =  false  , hasDefaultValue =  false  )
    
	private MobileStationMSID mobileStationMSID = null;
                
  
        @ASN1Element ( name = "mobileStationPartialKey", isOptional =  true , hasTag =  true, tag = 185 , hasDefaultValue =  false  )
    
	private MobileStationPartialKey mobileStationPartialKey = null;
                
  
        @ASN1Element ( name = "mscid", isOptional =  true , hasTag =  true, tag = 21 , hasDefaultValue =  false  )
    
	private MSCID mscid = null;
                
  
        @ASN1Element ( name = "newlyAssignedMSID", isOptional =  true , hasTag =  false  , hasDefaultValue =  false  )
    
	private NewlyAssignedMSID newlyAssignedMSID = null;
                
  
        @ASN1Element ( name = "randomVariable", isOptional =  true , hasTag =  true, tag = 40 , hasDefaultValue =  false  )
    
	private RandomVariable randomVariable = null;
                
  
        @ASN1Element ( name = "randomVariableBaseStation", isOptional =  false , hasTag =  true, tag = 41 , hasDefaultValue =  false  )
    
	private RandomVariableBaseStation randomVariableBaseStation = null;
                
  
        @ASN1Element ( name = "serviceIndicator", isOptional =  true , hasTag =  true, tag = 193 , hasDefaultValue =  false  )
    
	private ServiceIndicator serviceIndicator = null;
                
  
        @ASN1Element ( name = "systemCapabilities", isOptional =  true , hasTag =  true, tag = 49 , hasDefaultValue =  false  )
    
	private SystemCapabilities systemCapabilities = null;
                
  
        @ASN1Element ( name = "terminalType", isOptional =  true , hasTag =  true, tag = 47 , hasDefaultValue =  false  )
    
	private TerminalType terminalType = null;
                
  
        @ASN1Element ( name = "meid", isOptional =  true , hasTag =  true, tag = 390 , hasDefaultValue =  false  )
    
	private MEID meid = null;
                
  
        
        public ActionCode getActionCode () {
            return this.actionCode;
        }

        
        public boolean isActionCodePresent () {
            return this.actionCode != null;
        }
        

        public void setActionCode (ActionCode value) {
            this.actionCode = value;
        }
        
  
        
        public AKeyProtocolVersion getAKeyProtocolVersion () {
            return this.aKeyProtocolVersion;
        }

        
        public boolean isAKeyProtocolVersionPresent () {
            return this.aKeyProtocolVersion != null;
        }
        

        public void setAKeyProtocolVersion (AKeyProtocolVersion value) {
            this.aKeyProtocolVersion = value;
        }
        
  
        
        public AuthenticationData getAuthenticationData () {
            return this.authenticationData;
        }

        
        public boolean isAuthenticationDataPresent () {
            return this.authenticationData != null;
        }
        

        public void setAuthenticationData (AuthenticationData value) {
            this.authenticationData = value;
        }
        
  
        
        public AuthenticationResponse getAuthenticationResponse () {
            return this.authenticationResponse;
        }

        
        public boolean isAuthenticationResponsePresent () {
            return this.authenticationResponse != null;
        }
        

        public void setAuthenticationResponse (AuthenticationResponse value) {
            this.authenticationResponse = value;
        }
        
  
        
        public CallHistoryCount getCallHistoryCount () {
            return this.callHistoryCount;
        }

        
        public boolean isCallHistoryCountPresent () {
            return this.callHistoryCount != null;
        }
        

        public void setCallHistoryCount (CallHistoryCount value) {
            this.callHistoryCount = value;
        }
        
  
        
        public ElectronicSerialNumber getElectronicSerialNumber () {
            return this.electronicSerialNumber;
        }

        
        public boolean isElectronicSerialNumberPresent () {
            return this.electronicSerialNumber != null;
        }
        

        public void setElectronicSerialNumber (ElectronicSerialNumber value) {
            this.electronicSerialNumber = value;
        }
        
  
        
        public MSID getMsid () {
            return this.msid;
        }

        
        public boolean isMsidPresent () {
            return this.msid != null;
        }
        

        public void setMsid (MSID value) {
            this.msid = value;
        }
        
  
        
        public MobileStationMSID getMobileStationMSID () {
            return this.mobileStationMSID;
        }

        
        public boolean isMobileStationMSIDPresent () {
            return this.mobileStationMSID != null;
        }
        

        public void setMobileStationMSID (MobileStationMSID value) {
            this.mobileStationMSID = value;
        }
        
  
        
        public MobileStationPartialKey getMobileStationPartialKey () {
            return this.mobileStationPartialKey;
        }

        
        public boolean isMobileStationPartialKeyPresent () {
            return this.mobileStationPartialKey != null;
        }
        

        public void setMobileStationPartialKey (MobileStationPartialKey value) {
            this.mobileStationPartialKey = value;
        }
        
  
        
        public MSCID getMscid () {
            return this.mscid;
        }

        
        public boolean isMscidPresent () {
            return this.mscid != null;
        }
        

        public void setMscid (MSCID value) {
            this.mscid = value;
        }
        
  
        
        public NewlyAssignedMSID getNewlyAssignedMSID () {
            return this.newlyAssignedMSID;
        }

        
        public boolean isNewlyAssignedMSIDPresent () {
            return this.newlyAssignedMSID != null;
        }
        

        public void setNewlyAssignedMSID (NewlyAssignedMSID value) {
            this.newlyAssignedMSID = value;
        }
        
  
        
        public RandomVariable getRandomVariable () {
            return this.randomVariable;
        }

        
        public boolean isRandomVariablePresent () {
            return this.randomVariable != null;
        }
        

        public void setRandomVariable (RandomVariable value) {
            this.randomVariable = value;
        }
        
  
        
        public RandomVariableBaseStation getRandomVariableBaseStation () {
            return this.randomVariableBaseStation;
        }

        

        public void setRandomVariableBaseStation (RandomVariableBaseStation value) {
            this.randomVariableBaseStation = value;
        }
        
  
        
        public ServiceIndicator getServiceIndicator () {
            return this.serviceIndicator;
        }

        
        public boolean isServiceIndicatorPresent () {
            return this.serviceIndicator != null;
        }
        

        public void setServiceIndicator (ServiceIndicator value) {
            this.serviceIndicator = value;
        }
        
  
        
        public SystemCapabilities getSystemCapabilities () {
            return this.systemCapabilities;
        }

        
        public boolean isSystemCapabilitiesPresent () {
            return this.systemCapabilities != null;
        }
        

        public void setSystemCapabilities (SystemCapabilities value) {
            this.systemCapabilities = value;
        }
        
  
        
        public TerminalType getTerminalType () {
            return this.terminalType;
        }

        
        public boolean isTerminalTypePresent () {
            return this.terminalType != null;
        }
        

        public void setTerminalType (TerminalType value) {
            this.terminalType = value;
        }
        
  
        
        public MEID getMeid () {
            return this.meid;
        }

        
        public boolean isMeidPresent () {
            return this.meid != null;
        }
        

        public void setMeid (MEID value) {
            this.meid = value;
        }
        
  
                
                
        public void initWithDefaults() {
            
        }

        public IASN1PreparedElementData getPreparedData() {
            return preparedData_OTASPRequestSequenceType;
        }

       private static IASN1PreparedElementData preparedData_OTASPRequestSequenceType = CoderFactory.getInstance().newPreparedElementData(OTASPRequestSequenceType.class);
                
       }

       
                
        @ASN1Element ( name = "OTASPRequest", isOptional =  false , hasTag =  true, tag = 18, 
        tagClass =  TagClass.Private  , hasDefaultValue =  false  )
    
        private OTASPRequestSequenceType  value;        

        
        
        public OTASPRequest () {
        }
        
        
        
        public void setValue(OTASPRequestSequenceType value) {
            this.value = value;
        }
        
        
        
        public OTASPRequestSequenceType getValue() {
            return this.value;
        }            
        

	    public void initWithDefaults() {
	    }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(OTASPRequest.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            