
package com.agnity.win.asngenerated;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1BoxedType ( name = "ResetCircuit" )
    public class ResetCircuit implements IASN1PreparedElement {
                
        

       @ASN1PreparedElement
       @ASN1Sequence ( name = "ResetCircuit" , isSet = true )
       public static class ResetCircuitSequenceType implements IASN1PreparedElement {
                
        @ASN1Element ( name = "interMSCCircuitID", isOptional =  false , hasTag =  true, tag = 6 , hasDefaultValue =  false  )
    
	private InterMSCCircuitID interMSCCircuitID = null;
                
  
        
        public InterMSCCircuitID getInterMSCCircuitID () {
            return this.interMSCCircuitID;
        }

        

        public void setInterMSCCircuitID (InterMSCCircuitID value) {
            this.interMSCCircuitID = value;
        }
        
  
                
                
        public void initWithDefaults() {
            
        }

        public IASN1PreparedElementData getPreparedData() {
            return preparedData_ResetCircuitSequenceType;
        }

       private static IASN1PreparedElementData preparedData_ResetCircuitSequenceType = CoderFactory.getInstance().newPreparedElementData(ResetCircuitSequenceType.class);
                
       }

       
                
        @ASN1Element ( name = "ResetCircuit", isOptional =  false , hasTag =  true, tag = 18, 
        tagClass =  TagClass.Private  , hasDefaultValue =  false  )
    
        private ResetCircuitSequenceType  value;        

        
        
        public ResetCircuit () {
        }
        
        
        
        public void setValue(ResetCircuitSequenceType value) {
            this.value = value;
        }
        
        
        
        public ResetCircuitSequenceType getValue() {
            return this.value;
        }            
        

	    public void initWithDefaults() {
	    }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(ResetCircuit.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            