
package com.agnity.win.asngenerated;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1BoxedType ( name = "RoutingRequest" )
    public class RoutingRequest implements IASN1PreparedElement {
                
        

       @ASN1PreparedElement
       @ASN1Sequence ( name = "RoutingRequest" , isSet = true )
       public static class RoutingRequestSequenceType implements IASN1PreparedElement {
                
        @ASN1Element ( name = "billingID", isOptional =  false , hasTag =  true, tag = 1 , hasDefaultValue =  false  )
    
	private BillingID billingID = null;
                
  
        @ASN1Element ( name = "electronicSerialNumber", isOptional =  false , hasTag =  true, tag = 9 , hasDefaultValue =  false  )
    
	private ElectronicSerialNumber electronicSerialNumber = null;
                
  
        @ASN1Element ( name = "mscid", isOptional =  false , hasTag =  true, tag = 21 , hasDefaultValue =  false  )
    
	private MSCID mscid = null;
                
  
        @ASN1Element ( name = "systemMyTypeCode", isOptional =  false , hasTag =  true, tag = 22 , hasDefaultValue =  false  )
    
	private SystemMyTypeCode systemMyTypeCode = null;
                
  
        @ASN1Element ( name = "alertCode", isOptional =  true , hasTag =  true, tag = 75 , hasDefaultValue =  false  )
    
	private AlertCode alertCode = null;
                
  
        @ASN1Element ( name = "callingPartyName", isOptional =  true , hasTag =  true, tag = 243 , hasDefaultValue =  false  )
    
	private CallingPartyName callingPartyName = null;
                
  
        @ASN1Element ( name = "callingPartyNumberDigits1", isOptional =  true , hasTag =  true, tag = 80 , hasDefaultValue =  false  )
    
	private CallingPartyNumberDigits1 callingPartyNumberDigits1 = null;
                
  
        @ASN1Element ( name = "callingPartyNumberDigits2", isOptional =  true , hasTag =  true, tag = 81 , hasDefaultValue =  false  )
    
	private CallingPartyNumberDigits2 callingPartyNumberDigits2 = null;
                
  
        @ASN1Element ( name = "callingPartyNumberString1", isOptional =  true , hasTag =  true, tag = 82 , hasDefaultValue =  false  )
    
	private CallingPartyNumberString1 callingPartyNumberString1 = null;
                
  
        @ASN1Element ( name = "callingPartyNumberString2", isOptional =  true , hasTag =  true, tag = 83 , hasDefaultValue =  false  )
    
	private CallingPartyNumberString2 callingPartyNumberString2 = null;
                
  
        @ASN1Element ( name = "callingPartySubaddress", isOptional =  true , hasTag =  true, tag = 84 , hasDefaultValue =  false  )
    
	private CallingPartySubaddress callingPartySubaddress = null;
                
  
        @ASN1Element ( name = "cdmaServiceOption", isOptional =  true , hasTag =  true, tag = 175 , hasDefaultValue =  false  )
    
	private CDMAServiceOption cdmaServiceOption = null;
                
  
        @ASN1Element ( name = "controlChannelMode", isOptional =  true , hasTag =  true, tag = 199 , hasDefaultValue =  false  )
    
	private ControlChannelMode controlChannelMode = null;
                
  
        @ASN1Element ( name = "destinationDigits", isOptional =  true , hasTag =  true, tag = 87 , hasDefaultValue =  false  )
    
	private DestinationDigits destinationDigits = null;
                
  
        @ASN1Element ( name = "displayText", isOptional =  true , hasTag =  true, tag = 244 , hasDefaultValue =  false  )
    
	private DisplayText displayText = null;
                
  
        @ASN1Element ( name = "displayText2", isOptional =  true , hasTag =  true, tag = 299 , hasDefaultValue =  false  )
    
	private DisplayText2 displayText2 = null;
                
  
        @ASN1Element ( name = "dmh-AccountCodeDigits", isOptional =  true , hasTag =  true, tag = 140 , hasDefaultValue =  false  )
    
	private DMH_AccountCodeDigits dmh_AccountCodeDigits = null;
                
  
        @ASN1Element ( name = "dmh-AlternateBillingDigits", isOptional =  true , hasTag =  true, tag = 141 , hasDefaultValue =  false  )
    
	private DMH_AlternateBillingDigits dmh_AlternateBillingDigits = null;
                
  
        @ASN1Element ( name = "dmh-BillingDigits", isOptional =  true , hasTag =  true, tag = 142 , hasDefaultValue =  false  )
    
	private DMH_BillingDigits dmh_BillingDigits = null;
                
  
        @ASN1Element ( name = "legInformation", isOptional =  true , hasTag =  true, tag = 144 , hasDefaultValue =  false  )
    
	private LegInformation legInformation = null;
                
  
        @ASN1Element ( name = "locationAreaID", isOptional =  true , hasTag =  true, tag = 33 , hasDefaultValue =  false  )
    
	private LocationAreaID locationAreaID = null;
                
  
        @ASN1Element ( name = "mobileDirectoryNumber", isOptional =  true , hasTag =  true, tag = 93 , hasDefaultValue =  false  )
    
	private MobileDirectoryNumber mobileDirectoryNumber = null;
                
  
        @ASN1Element ( name = "msid", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private MSID msid = null;
                
  
        @ASN1Element ( name = "mSCIdentificationNumber", isOptional =  true , hasTag =  true, tag = 94 , hasDefaultValue =  false  )
    
	private MSCIdentificationNumber mSCIdentificationNumber = null;
                
  
        @ASN1Element ( name = "noAnswerTime", isOptional =  true , hasTag =  true, tag = 96 , hasDefaultValue =  false  )
    
	private NoAnswerTime noAnswerTime = null;
                
  
        @ASN1Element ( name = "oneTimeFeatureIndicator", isOptional =  true , hasTag =  true, tag = 97 , hasDefaultValue =  false  )
    
	private OneTimeFeatureIndicator oneTimeFeatureIndicator = null;
                
  
        @ASN1Element ( name = "pc-ssn", isOptional =  true , hasTag =  true, tag = 32 , hasDefaultValue =  false  )
    
	private PC_SSN pc_ssn = null;
                
  
        @ASN1Element ( name = "pilotBillingID", isOptional =  true , hasTag =  true, tag = 169 , hasDefaultValue =  false  )
    
	private PilotBillingID pilotBillingID = null;
                
  
        @ASN1Element ( name = "pilotNumber", isOptional =  true , hasTag =  true, tag = 168 , hasDefaultValue =  false  )
    
	private PilotNumber pilotNumber = null;
                
  
        @ASN1Element ( name = "redirectingNumberDigits", isOptional =  true , hasTag =  true, tag = 100 , hasDefaultValue =  false  )
    
	private RedirectingNumberDigits redirectingNumberDigits = null;
                
  
        @ASN1Element ( name = "redirectingNumberString", isOptional =  true , hasTag =  true, tag = 101 , hasDefaultValue =  false  )
    
	private RedirectingNumberString redirectingNumberString = null;
                
  
        @ASN1Element ( name = "redirectingPartyName", isOptional =  true , hasTag =  true, tag = 245 , hasDefaultValue =  false  )
    
	private RedirectingPartyName redirectingPartyName = null;
                
  
        @ASN1Element ( name = "redirectingSubaddress", isOptional =  true , hasTag =  true, tag = 102 , hasDefaultValue =  false  )
    
	private RedirectingSubaddress redirectingSubaddress = null;
                
  
        @ASN1Element ( name = "senderIdentificationNumber", isOptional =  true , hasTag =  true, tag = 103 , hasDefaultValue =  false  )
    
	private SenderIdentificationNumber senderIdentificationNumber = null;
                
  
        @ASN1Element ( name = "tdmaServiceCode", isOptional =  true , hasTag =  true, tag = 178 , hasDefaultValue =  false  )
    
	private TDMAServiceCode tdmaServiceCode = null;
                
  
        @ASN1Element ( name = "terminationTreatment", isOptional =  true , hasTag =  true, tag = 121 , hasDefaultValue =  false  )
    
	private TerminationTreatment terminationTreatment = null;
                
  
        @ASN1Element ( name = "terminationTriggers", isOptional =  true , hasTag =  true, tag = 122 , hasDefaultValue =  false  )
    
	private TerminationTriggers terminationTriggers = null;
                
  
        @ASN1Element ( name = "triggerAddressList", isOptional =  true , hasTag =  true, tag = 276 , hasDefaultValue =  false  )
    
	private TriggerAddressList triggerAddressList = null;
                
  
        @ASN1Element ( name = "userGroup", isOptional =  true , hasTag =  true, tag = 208 , hasDefaultValue =  false  )
    
	private UserGroup userGroup = null;
                
  
        @ASN1Element ( name = "transactionCapability", isOptional =  true , hasTag =  true, tag = 123 , hasDefaultValue =  false  )
    
	private TransactionCapability transactionCapability = null;
                
  
        @ASN1Element ( name = "voiceMailboxNumber", isOptional =  true , hasTag =  true, tag = 160 , hasDefaultValue =  false  )
    
	private VoiceMailboxNumber voiceMailboxNumber = null;
                
  
        @ASN1Element ( name = "voiceMailboxPIN", isOptional =  true , hasTag =  true, tag = 159 , hasDefaultValue =  false  )
    
	private VoiceMailboxPIN voiceMailboxPIN = null;
                
  
        
        public BillingID getBillingID () {
            return this.billingID;
        }

        

        public void setBillingID (BillingID value) {
            this.billingID = value;
        }
        
  
        
        public ElectronicSerialNumber getElectronicSerialNumber () {
            return this.electronicSerialNumber;
        }

        

        public void setElectronicSerialNumber (ElectronicSerialNumber value) {
            this.electronicSerialNumber = value;
        }
        
  
        
        public MSCID getMscid () {
            return this.mscid;
        }

        

        public void setMscid (MSCID value) {
            this.mscid = value;
        }
        
  
        
        public SystemMyTypeCode getSystemMyTypeCode () {
            return this.systemMyTypeCode;
        }

        

        public void setSystemMyTypeCode (SystemMyTypeCode value) {
            this.systemMyTypeCode = value;
        }
        
  
        
        public AlertCode getAlertCode () {
            return this.alertCode;
        }

        
        public boolean isAlertCodePresent () {
            return this.alertCode != null;
        }
        

        public void setAlertCode (AlertCode value) {
            this.alertCode = value;
        }
        
  
        
        public CallingPartyName getCallingPartyName () {
            return this.callingPartyName;
        }

        
        public boolean isCallingPartyNamePresent () {
            return this.callingPartyName != null;
        }
        

        public void setCallingPartyName (CallingPartyName value) {
            this.callingPartyName = value;
        }
        
  
        
        public CallingPartyNumberDigits1 getCallingPartyNumberDigits1 () {
            return this.callingPartyNumberDigits1;
        }

        
        public boolean isCallingPartyNumberDigits1Present () {
            return this.callingPartyNumberDigits1 != null;
        }
        

        public void setCallingPartyNumberDigits1 (CallingPartyNumberDigits1 value) {
            this.callingPartyNumberDigits1 = value;
        }
        
  
        
        public CallingPartyNumberDigits2 getCallingPartyNumberDigits2 () {
            return this.callingPartyNumberDigits2;
        }

        
        public boolean isCallingPartyNumberDigits2Present () {
            return this.callingPartyNumberDigits2 != null;
        }
        

        public void setCallingPartyNumberDigits2 (CallingPartyNumberDigits2 value) {
            this.callingPartyNumberDigits2 = value;
        }
        
  
        
        public CallingPartyNumberString1 getCallingPartyNumberString1 () {
            return this.callingPartyNumberString1;
        }

        
        public boolean isCallingPartyNumberString1Present () {
            return this.callingPartyNumberString1 != null;
        }
        

        public void setCallingPartyNumberString1 (CallingPartyNumberString1 value) {
            this.callingPartyNumberString1 = value;
        }
        
  
        
        public CallingPartyNumberString2 getCallingPartyNumberString2 () {
            return this.callingPartyNumberString2;
        }

        
        public boolean isCallingPartyNumberString2Present () {
            return this.callingPartyNumberString2 != null;
        }
        

        public void setCallingPartyNumberString2 (CallingPartyNumberString2 value) {
            this.callingPartyNumberString2 = value;
        }
        
  
        
        public CallingPartySubaddress getCallingPartySubaddress () {
            return this.callingPartySubaddress;
        }

        
        public boolean isCallingPartySubaddressPresent () {
            return this.callingPartySubaddress != null;
        }
        

        public void setCallingPartySubaddress (CallingPartySubaddress value) {
            this.callingPartySubaddress = value;
        }
        
  
        
        public CDMAServiceOption getCdmaServiceOption () {
            return this.cdmaServiceOption;
        }

        
        public boolean isCdmaServiceOptionPresent () {
            return this.cdmaServiceOption != null;
        }
        

        public void setCdmaServiceOption (CDMAServiceOption value) {
            this.cdmaServiceOption = value;
        }
        
  
        
        public ControlChannelMode getControlChannelMode () {
            return this.controlChannelMode;
        }

        
        public boolean isControlChannelModePresent () {
            return this.controlChannelMode != null;
        }
        

        public void setControlChannelMode (ControlChannelMode value) {
            this.controlChannelMode = value;
        }
        
  
        
        public DestinationDigits getDestinationDigits () {
            return this.destinationDigits;
        }

        
        public boolean isDestinationDigitsPresent () {
            return this.destinationDigits != null;
        }
        

        public void setDestinationDigits (DestinationDigits value) {
            this.destinationDigits = value;
        }
        
  
        
        public DisplayText getDisplayText () {
            return this.displayText;
        }

        
        public boolean isDisplayTextPresent () {
            return this.displayText != null;
        }
        

        public void setDisplayText (DisplayText value) {
            this.displayText = value;
        }
        
  
        
        public DisplayText2 getDisplayText2 () {
            return this.displayText2;
        }

        
        public boolean isDisplayText2Present () {
            return this.displayText2 != null;
        }
        

        public void setDisplayText2 (DisplayText2 value) {
            this.displayText2 = value;
        }
        
  
        
        public DMH_AccountCodeDigits getDmh_AccountCodeDigits () {
            return this.dmh_AccountCodeDigits;
        }

        
        public boolean isDmh_AccountCodeDigitsPresent () {
            return this.dmh_AccountCodeDigits != null;
        }
        

        public void setDmh_AccountCodeDigits (DMH_AccountCodeDigits value) {
            this.dmh_AccountCodeDigits = value;
        }
        
  
        
        public DMH_AlternateBillingDigits getDmh_AlternateBillingDigits () {
            return this.dmh_AlternateBillingDigits;
        }

        
        public boolean isDmh_AlternateBillingDigitsPresent () {
            return this.dmh_AlternateBillingDigits != null;
        }
        

        public void setDmh_AlternateBillingDigits (DMH_AlternateBillingDigits value) {
            this.dmh_AlternateBillingDigits = value;
        }
        
  
        
        public DMH_BillingDigits getDmh_BillingDigits () {
            return this.dmh_BillingDigits;
        }

        
        public boolean isDmh_BillingDigitsPresent () {
            return this.dmh_BillingDigits != null;
        }
        

        public void setDmh_BillingDigits (DMH_BillingDigits value) {
            this.dmh_BillingDigits = value;
        }
        
  
        
        public LegInformation getLegInformation () {
            return this.legInformation;
        }

        
        public boolean isLegInformationPresent () {
            return this.legInformation != null;
        }
        

        public void setLegInformation (LegInformation value) {
            this.legInformation = value;
        }
        
  
        
        public LocationAreaID getLocationAreaID () {
            return this.locationAreaID;
        }

        
        public boolean isLocationAreaIDPresent () {
            return this.locationAreaID != null;
        }
        

        public void setLocationAreaID (LocationAreaID value) {
            this.locationAreaID = value;
        }
        
  
        
        public MobileDirectoryNumber getMobileDirectoryNumber () {
            return this.mobileDirectoryNumber;
        }

        
        public boolean isMobileDirectoryNumberPresent () {
            return this.mobileDirectoryNumber != null;
        }
        

        public void setMobileDirectoryNumber (MobileDirectoryNumber value) {
            this.mobileDirectoryNumber = value;
        }
        
  
        
        public MSID getMsid () {
            return this.msid;
        }

        

        public void setMsid (MSID value) {
            this.msid = value;
        }
        
  
        
        public MSCIdentificationNumber getMSCIdentificationNumber () {
            return this.mSCIdentificationNumber;
        }

        
        public boolean isMSCIdentificationNumberPresent () {
            return this.mSCIdentificationNumber != null;
        }
        

        public void setMSCIdentificationNumber (MSCIdentificationNumber value) {
            this.mSCIdentificationNumber = value;
        }
        
  
        
        public NoAnswerTime getNoAnswerTime () {
            return this.noAnswerTime;
        }

        
        public boolean isNoAnswerTimePresent () {
            return this.noAnswerTime != null;
        }
        

        public void setNoAnswerTime (NoAnswerTime value) {
            this.noAnswerTime = value;
        }
        
  
        
        public OneTimeFeatureIndicator getOneTimeFeatureIndicator () {
            return this.oneTimeFeatureIndicator;
        }

        
        public boolean isOneTimeFeatureIndicatorPresent () {
            return this.oneTimeFeatureIndicator != null;
        }
        

        public void setOneTimeFeatureIndicator (OneTimeFeatureIndicator value) {
            this.oneTimeFeatureIndicator = value;
        }
        
  
        
        public PC_SSN getPc_ssn () {
            return this.pc_ssn;
        }

        
        public boolean isPc_ssnPresent () {
            return this.pc_ssn != null;
        }
        

        public void setPc_ssn (PC_SSN value) {
            this.pc_ssn = value;
        }
        
  
        
        public PilotBillingID getPilotBillingID () {
            return this.pilotBillingID;
        }

        
        public boolean isPilotBillingIDPresent () {
            return this.pilotBillingID != null;
        }
        

        public void setPilotBillingID (PilotBillingID value) {
            this.pilotBillingID = value;
        }
        
  
        
        public PilotNumber getPilotNumber () {
            return this.pilotNumber;
        }

        
        public boolean isPilotNumberPresent () {
            return this.pilotNumber != null;
        }
        

        public void setPilotNumber (PilotNumber value) {
            this.pilotNumber = value;
        }
        
  
        
        public RedirectingNumberDigits getRedirectingNumberDigits () {
            return this.redirectingNumberDigits;
        }

        
        public boolean isRedirectingNumberDigitsPresent () {
            return this.redirectingNumberDigits != null;
        }
        

        public void setRedirectingNumberDigits (RedirectingNumberDigits value) {
            this.redirectingNumberDigits = value;
        }
        
  
        
        public RedirectingNumberString getRedirectingNumberString () {
            return this.redirectingNumberString;
        }

        
        public boolean isRedirectingNumberStringPresent () {
            return this.redirectingNumberString != null;
        }
        

        public void setRedirectingNumberString (RedirectingNumberString value) {
            this.redirectingNumberString = value;
        }
        
  
        
        public RedirectingPartyName getRedirectingPartyName () {
            return this.redirectingPartyName;
        }

        
        public boolean isRedirectingPartyNamePresent () {
            return this.redirectingPartyName != null;
        }
        

        public void setRedirectingPartyName (RedirectingPartyName value) {
            this.redirectingPartyName = value;
        }
        
  
        
        public RedirectingSubaddress getRedirectingSubaddress () {
            return this.redirectingSubaddress;
        }

        
        public boolean isRedirectingSubaddressPresent () {
            return this.redirectingSubaddress != null;
        }
        

        public void setRedirectingSubaddress (RedirectingSubaddress value) {
            this.redirectingSubaddress = value;
        }
        
  
        
        public SenderIdentificationNumber getSenderIdentificationNumber () {
            return this.senderIdentificationNumber;
        }

        
        public boolean isSenderIdentificationNumberPresent () {
            return this.senderIdentificationNumber != null;
        }
        

        public void setSenderIdentificationNumber (SenderIdentificationNumber value) {
            this.senderIdentificationNumber = value;
        }
        
  
        
        public TDMAServiceCode getTdmaServiceCode () {
            return this.tdmaServiceCode;
        }

        
        public boolean isTdmaServiceCodePresent () {
            return this.tdmaServiceCode != null;
        }
        

        public void setTdmaServiceCode (TDMAServiceCode value) {
            this.tdmaServiceCode = value;
        }
        
  
        
        public TerminationTreatment getTerminationTreatment () {
            return this.terminationTreatment;
        }

        
        public boolean isTerminationTreatmentPresent () {
            return this.terminationTreatment != null;
        }
        

        public void setTerminationTreatment (TerminationTreatment value) {
            this.terminationTreatment = value;
        }
        
  
        
        public TerminationTriggers getTerminationTriggers () {
            return this.terminationTriggers;
        }

        
        public boolean isTerminationTriggersPresent () {
            return this.terminationTriggers != null;
        }
        

        public void setTerminationTriggers (TerminationTriggers value) {
            this.terminationTriggers = value;
        }
        
  
        
        public TriggerAddressList getTriggerAddressList () {
            return this.triggerAddressList;
        }

        
        public boolean isTriggerAddressListPresent () {
            return this.triggerAddressList != null;
        }
        

        public void setTriggerAddressList (TriggerAddressList value) {
            this.triggerAddressList = value;
        }
        
  
        
        public UserGroup getUserGroup () {
            return this.userGroup;
        }

        
        public boolean isUserGroupPresent () {
            return this.userGroup != null;
        }
        

        public void setUserGroup (UserGroup value) {
            this.userGroup = value;
        }
        
  
        
        public TransactionCapability getTransactionCapability () {
            return this.transactionCapability;
        }

        
        public boolean isTransactionCapabilityPresent () {
            return this.transactionCapability != null;
        }
        

        public void setTransactionCapability (TransactionCapability value) {
            this.transactionCapability = value;
        }
        
  
        
        public VoiceMailboxNumber getVoiceMailboxNumber () {
            return this.voiceMailboxNumber;
        }

        
        public boolean isVoiceMailboxNumberPresent () {
            return this.voiceMailboxNumber != null;
        }
        

        public void setVoiceMailboxNumber (VoiceMailboxNumber value) {
            this.voiceMailboxNumber = value;
        }
        
  
        
        public VoiceMailboxPIN getVoiceMailboxPIN () {
            return this.voiceMailboxPIN;
        }

        
        public boolean isVoiceMailboxPINPresent () {
            return this.voiceMailboxPIN != null;
        }
        

        public void setVoiceMailboxPIN (VoiceMailboxPIN value) {
            this.voiceMailboxPIN = value;
        }
        
  
                
                
        public void initWithDefaults() {
            
        }

        public IASN1PreparedElementData getPreparedData() {
            return preparedData_RoutingRequestSequenceType;
        }

       private static IASN1PreparedElementData preparedData_RoutingRequestSequenceType = CoderFactory.getInstance().newPreparedElementData(RoutingRequestSequenceType.class);
                
       }

       
                
        @ASN1Element ( name = "RoutingRequest", isOptional =  false , hasTag =  true, tag = 18, 
        tagClass =  TagClass.Private  , hasDefaultValue =  false  )
    
        private RoutingRequestSequenceType  value;        

        
        
        public RoutingRequest () {
        }
        
        
        
        public void setValue(RoutingRequestSequenceType value) {
            this.value = value;
        }
        
        
        
        public RoutingRequestSequenceType getValue() {
            return this.value;
        }            
        

	    public void initWithDefaults() {
	    }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(RoutingRequest.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            