
package com.agnity.win.asngenerated;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1BoxedType ( name = "ServiceRequest" )
    public class ServiceRequest implements IASN1PreparedElement {
                
        

       @ASN1PreparedElement
       @ASN1Sequence ( name = "ServiceRequest" , isSet = true )
       public static class ServiceRequestSequenceType implements IASN1PreparedElement {
                
        @ASN1Element ( name = "serviceID", isOptional =  false , hasTag =  true, tag = 246 , hasDefaultValue =  false  )
    
	private ServiceID serviceID = null;
                
  
        @ASN1Element ( name = "accessDeniedReason", isOptional =  true , hasTag =  true, tag = 20 , hasDefaultValue =  false  )
    
	private AccessDeniedReason accessDeniedReason = null;
                
  
        @ASN1Element ( name = "acgencountered", isOptional =  true , hasTag =  true, tag = 340 , hasDefaultValue =  false  )
    
	private ACGEncountered acgencountered = null;
                
  
        @ASN1Element ( name = "availabilityType", isOptional =  true , hasTag =  true, tag = 90 , hasDefaultValue =  false  )
    
	private AvailabilityType availabilityType = null;
                
  
        @ASN1Element ( name = "billingID", isOptional =  true , hasTag =  true, tag = 1 , hasDefaultValue =  false  )
    
	private BillingID billingID = null;
                
  
        @ASN1Element ( name = "callingPartyName", isOptional =  true , hasTag =  true, tag = 243 , hasDefaultValue =  false  )
    
	private CallingPartyName callingPartyName = null;
                
  
        @ASN1Element ( name = "callingPartyNumberDigits1", isOptional =  true , hasTag =  true, tag = 80 , hasDefaultValue =  false  )
    
	private CallingPartyNumberDigits1 callingPartyNumberDigits1 = null;
                
  
        @ASN1Element ( name = "callingPartyNumberDigits2", isOptional =  true , hasTag =  true, tag = 81 , hasDefaultValue =  false  )
    
	private CallingPartyNumberDigits2 callingPartyNumberDigits2 = null;
                
  
        @ASN1Element ( name = "callingPartySubaddress", isOptional =  true , hasTag =  true, tag = 84 , hasDefaultValue =  false  )
    
	private CallingPartySubaddress callingPartySubaddress = null;
                
  
        @ASN1Element ( name = "carrierDigits", isOptional =  true , hasTag =  true, tag = 86 , hasDefaultValue =  false  )
    
	private CarrierDigits carrierDigits = null;
                
  
        @ASN1Element ( name = "conditionallyDeniedReason", isOptional =  true , hasTag =  true, tag = 162 , hasDefaultValue =  false  )
    
	private ConditionallyDeniedReason conditionallyDeniedReason = null;
                
  
        @ASN1Element ( name = "dataAccessElementList", isOptional =  true , hasTag =  true, tag = 250 , hasDefaultValue =  false  )
    
	private DataAccessElementList dataAccessElementList = null;
                
  
        @ASN1Element ( name = "destinationDigits", isOptional =  true , hasTag =  true, tag = 87 , hasDefaultValue =  false  )
    
	private DestinationDigits destinationDigits = null;
                
  
        @ASN1Element ( name = "digits", isOptional =  true , hasTag =  true, tag = 4 , hasDefaultValue =  false  )
    
	private Digits digits = null;
                
  
        @ASN1Element ( name = "dmh-RedirectionIndicator", isOptional =  true , hasTag =  true, tag = 88 , hasDefaultValue =  false  )
    
	private DMH_RedirectionIndicator dmh_RedirectionIndicator = null;
                
  
        @ASN1Element ( name = "dmh-ServiceID", isOptional =  true , hasTag =  true, tag = 305 , hasDefaultValue =  false  )
    
	private DMH_ServiceID dmh_ServiceID = null;
                
  
        @ASN1Element ( name = "electronicSerialNumber", isOptional =  true , hasTag =  true, tag = 9 , hasDefaultValue =  false  )
    
	private ElectronicSerialNumber electronicSerialNumber = null;
                
  
        @ASN1Element ( name = "extendedMSCID", isOptional =  true , hasTag =  true, tag = 53 , hasDefaultValue =  false  )
    
	private ExtendedMSCID extendedMSCID = null;
                
  
        @ASN1Element ( name = "featureIndicator", isOptional =  true , hasTag =  true, tag = 306 , hasDefaultValue =  false  )
    
	private FeatureIndicator featureIndicator = null;
                
  
        @ASN1Element ( name = "groupInformation", isOptional =  true , hasTag =  true, tag = 163 , hasDefaultValue =  false  )
    
	private GroupInformation groupInformation = null;
                
  
        @ASN1Element ( name = "legInformation", isOptional =  true , hasTag =  true, tag = 144 , hasDefaultValue =  false  )
    
	private LegInformation legInformation = null;
                
  
        @ASN1Element ( name = "locationAreaID", isOptional =  true , hasTag =  true, tag = 33 , hasDefaultValue =  false  )
    
	private LocationAreaID locationAreaID = null;
                
  
        @ASN1Element ( name = "mobileDirectoryNumber", isOptional =  true , hasTag =  true, tag = 93 , hasDefaultValue =  false  )
    
	private MobileDirectoryNumber mobileDirectoryNumber = null;
                
  
        @ASN1Element ( name = "mscid", isOptional =  true , hasTag =  true, tag = 21 , hasDefaultValue =  false  )
    
	private MSCID mscid = null;
                
  
        @ASN1Element ( name = "mSCIdentificationNumber", isOptional =  true , hasTag =  true, tag = 94 , hasDefaultValue =  false  )
    
	private MSCIdentificationNumber mSCIdentificationNumber = null;
                
  
        @ASN1Element ( name = "msid", isOptional =  true , hasTag =  false  , hasDefaultValue =  false  )
    
	private MSID msid = null;
                
  
        @ASN1Element ( name = "pc-ssn", isOptional =  true , hasTag =  true, tag = 32 , hasDefaultValue =  false  )
    
	private PC_SSN pc_ssn = null;
                
  
        @ASN1Element ( name = "pilotBillingID", isOptional =  true , hasTag =  true, tag = 169 , hasDefaultValue =  false  )
    
	private PilotBillingID pilotBillingID = null;
                
  
        @ASN1Element ( name = "pilotNumber", isOptional =  true , hasTag =  true, tag = 168 , hasDefaultValue =  false  )
    
	private PilotNumber pilotNumber = null;
                
  
        @ASN1Element ( name = "preferredLanguageIndicator", isOptional =  true , hasTag =  true, tag = 147 , hasDefaultValue =  false  )
    
	private PreferredLanguageIndicator preferredLanguageIndicator = null;
                
  
        @ASN1Element ( name = "redirectingPartyName", isOptional =  true , hasTag =  true, tag = 245 , hasDefaultValue =  false  )
    
	private RedirectingPartyName redirectingPartyName = null;
                
  
        @ASN1Element ( name = "redirectingNumberDigits", isOptional =  true , hasTag =  true, tag = 100 , hasDefaultValue =  false  )
    
	private RedirectingNumberDigits redirectingNumberDigits = null;
                
  
        @ASN1Element ( name = "redirectingSubaddress", isOptional =  true , hasTag =  true, tag = 102 , hasDefaultValue =  false  )
    
	private RedirectingSubaddress redirectingSubaddress = null;
                
  
        @ASN1Element ( name = "redirectionReason", isOptional =  true , hasTag =  true, tag = 19 , hasDefaultValue =  false  )
    
	private RedirectionReason redirectionReason = null;
                
  
        @ASN1Element ( name = "routingDigits", isOptional =  true , hasTag =  true, tag = 150 , hasDefaultValue =  false  )
    
	private RoutingDigits routingDigits = null;
                
  
        @ASN1Element ( name = "senderIdentificationNumber", isOptional =  true , hasTag =  true, tag = 103 , hasDefaultValue =  false  )
    
	private SenderIdentificationNumber senderIdentificationNumber = null;
                
  
        @ASN1Element ( name = "servingCellID", isOptional =  true , hasTag =  true, tag = 2 , hasDefaultValue =  false  )
    
	private ServingCellID servingCellID = null;
                
  
        @ASN1Element ( name = "systemMyTypeCode", isOptional =  true , hasTag =  true, tag = 22 , hasDefaultValue =  false  )
    
	private SystemMyTypeCode systemMyTypeCode = null;
                
  
        @ASN1Element ( name = "terminationAccessType", isOptional =  true , hasTag =  true, tag = 119 , hasDefaultValue =  false  )
    
	private TerminationAccessType terminationAccessType = null;
                
  
        @ASN1Element ( name = "timeDateOffset", isOptional =  true , hasTag =  true, tag = 275 , hasDefaultValue =  false  )
    
	private TimeDateOffset timeDateOffset = null;
                
  
        @ASN1Element ( name = "timeOfDay", isOptional =  true , hasTag =  true, tag = 309 , hasDefaultValue =  false  )
    
	private TimeOfDay timeOfDay = null;
                
  
        @ASN1Element ( name = "transactionCapability", isOptional =  true , hasTag =  true, tag = 123 , hasDefaultValue =  false  )
    
	private TransactionCapability transactionCapability = null;
                
  
        @ASN1Element ( name = "triggerType", isOptional =  true , hasTag =  true, tag = 279 , hasDefaultValue =  false  )
    
	private TriggerType triggerType = null;
                
  
        @ASN1Element ( name = "winCapability", isOptional =  true , hasTag =  true, tag = 280 , hasDefaultValue =  false  )
    
	private WINCapability winCapability = null;
                
  
        
        public ServiceID getServiceID () {
            return this.serviceID;
        }

        

        public void setServiceID (ServiceID value) {
            this.serviceID = value;
        }
        
  
        
        public AccessDeniedReason getAccessDeniedReason () {
            return this.accessDeniedReason;
        }

        
        public boolean isAccessDeniedReasonPresent () {
            return this.accessDeniedReason != null;
        }
        

        public void setAccessDeniedReason (AccessDeniedReason value) {
            this.accessDeniedReason = value;
        }
        
  
        
        public ACGEncountered getAcgencountered () {
            return this.acgencountered;
        }

        
        public boolean isAcgencounteredPresent () {
            return this.acgencountered != null;
        }
        

        public void setAcgencountered (ACGEncountered value) {
            this.acgencountered = value;
        }
        
  
        
        public AvailabilityType getAvailabilityType () {
            return this.availabilityType;
        }

        
        public boolean isAvailabilityTypePresent () {
            return this.availabilityType != null;
        }
        

        public void setAvailabilityType (AvailabilityType value) {
            this.availabilityType = value;
        }
        
  
        
        public BillingID getBillingID () {
            return this.billingID;
        }

        
        public boolean isBillingIDPresent () {
            return this.billingID != null;
        }
        

        public void setBillingID (BillingID value) {
            this.billingID = value;
        }
        
  
        
        public CallingPartyName getCallingPartyName () {
            return this.callingPartyName;
        }

        
        public boolean isCallingPartyNamePresent () {
            return this.callingPartyName != null;
        }
        

        public void setCallingPartyName (CallingPartyName value) {
            this.callingPartyName = value;
        }
        
  
        
        public CallingPartyNumberDigits1 getCallingPartyNumberDigits1 () {
            return this.callingPartyNumberDigits1;
        }

        
        public boolean isCallingPartyNumberDigits1Present () {
            return this.callingPartyNumberDigits1 != null;
        }
        

        public void setCallingPartyNumberDigits1 (CallingPartyNumberDigits1 value) {
            this.callingPartyNumberDigits1 = value;
        }
        
  
        
        public CallingPartyNumberDigits2 getCallingPartyNumberDigits2 () {
            return this.callingPartyNumberDigits2;
        }

        
        public boolean isCallingPartyNumberDigits2Present () {
            return this.callingPartyNumberDigits2 != null;
        }
        

        public void setCallingPartyNumberDigits2 (CallingPartyNumberDigits2 value) {
            this.callingPartyNumberDigits2 = value;
        }
        
  
        
        public CallingPartySubaddress getCallingPartySubaddress () {
            return this.callingPartySubaddress;
        }

        
        public boolean isCallingPartySubaddressPresent () {
            return this.callingPartySubaddress != null;
        }
        

        public void setCallingPartySubaddress (CallingPartySubaddress value) {
            this.callingPartySubaddress = value;
        }
        
  
        
        public CarrierDigits getCarrierDigits () {
            return this.carrierDigits;
        }

        
        public boolean isCarrierDigitsPresent () {
            return this.carrierDigits != null;
        }
        

        public void setCarrierDigits (CarrierDigits value) {
            this.carrierDigits = value;
        }
        
  
        
        public ConditionallyDeniedReason getConditionallyDeniedReason () {
            return this.conditionallyDeniedReason;
        }

        
        public boolean isConditionallyDeniedReasonPresent () {
            return this.conditionallyDeniedReason != null;
        }
        

        public void setConditionallyDeniedReason (ConditionallyDeniedReason value) {
            this.conditionallyDeniedReason = value;
        }
        
  
        
        public DataAccessElementList getDataAccessElementList () {
            return this.dataAccessElementList;
        }

        
        public boolean isDataAccessElementListPresent () {
            return this.dataAccessElementList != null;
        }
        

        public void setDataAccessElementList (DataAccessElementList value) {
            this.dataAccessElementList = value;
        }
        
  
        
        public DestinationDigits getDestinationDigits () {
            return this.destinationDigits;
        }

        
        public boolean isDestinationDigitsPresent () {
            return this.destinationDigits != null;
        }
        

        public void setDestinationDigits (DestinationDigits value) {
            this.destinationDigits = value;
        }
        
  
        
        public Digits getDigits () {
            return this.digits;
        }

        
        public boolean isDigitsPresent () {
            return this.digits != null;
        }
        

        public void setDigits (Digits value) {
            this.digits = value;
        }
        
  
        
        public DMH_RedirectionIndicator getDmh_RedirectionIndicator () {
            return this.dmh_RedirectionIndicator;
        }

        
        public boolean isDmh_RedirectionIndicatorPresent () {
            return this.dmh_RedirectionIndicator != null;
        }
        

        public void setDmh_RedirectionIndicator (DMH_RedirectionIndicator value) {
            this.dmh_RedirectionIndicator = value;
        }
        
  
        
        public DMH_ServiceID getDmh_ServiceID () {
            return this.dmh_ServiceID;
        }

        
        public boolean isDmh_ServiceIDPresent () {
            return this.dmh_ServiceID != null;
        }
        

        public void setDmh_ServiceID (DMH_ServiceID value) {
            this.dmh_ServiceID = value;
        }
        
  
        
        public ElectronicSerialNumber getElectronicSerialNumber () {
            return this.electronicSerialNumber;
        }

        
        public boolean isElectronicSerialNumberPresent () {
            return this.electronicSerialNumber != null;
        }
        

        public void setElectronicSerialNumber (ElectronicSerialNumber value) {
            this.electronicSerialNumber = value;
        }
        
  
        
        public ExtendedMSCID getExtendedMSCID () {
            return this.extendedMSCID;
        }

        
        public boolean isExtendedMSCIDPresent () {
            return this.extendedMSCID != null;
        }
        

        public void setExtendedMSCID (ExtendedMSCID value) {
            this.extendedMSCID = value;
        }
        
  
        
        public FeatureIndicator getFeatureIndicator () {
            return this.featureIndicator;
        }

        
        public boolean isFeatureIndicatorPresent () {
            return this.featureIndicator != null;
        }
        

        public void setFeatureIndicator (FeatureIndicator value) {
            this.featureIndicator = value;
        }
        
  
        
        public GroupInformation getGroupInformation () {
            return this.groupInformation;
        }

        
        public boolean isGroupInformationPresent () {
            return this.groupInformation != null;
        }
        

        public void setGroupInformation (GroupInformation value) {
            this.groupInformation = value;
        }
        
  
        
        public LegInformation getLegInformation () {
            return this.legInformation;
        }

        
        public boolean isLegInformationPresent () {
            return this.legInformation != null;
        }
        

        public void setLegInformation (LegInformation value) {
            this.legInformation = value;
        }
        
  
        
        public LocationAreaID getLocationAreaID () {
            return this.locationAreaID;
        }

        
        public boolean isLocationAreaIDPresent () {
            return this.locationAreaID != null;
        }
        

        public void setLocationAreaID (LocationAreaID value) {
            this.locationAreaID = value;
        }
        
  
        
        public MobileDirectoryNumber getMobileDirectoryNumber () {
            return this.mobileDirectoryNumber;
        }

        
        public boolean isMobileDirectoryNumberPresent () {
            return this.mobileDirectoryNumber != null;
        }
        

        public void setMobileDirectoryNumber (MobileDirectoryNumber value) {
            this.mobileDirectoryNumber = value;
        }
        
  
        
        public MSCID getMscid () {
            return this.mscid;
        }

        
        public boolean isMscidPresent () {
            return this.mscid != null;
        }
        

        public void setMscid (MSCID value) {
            this.mscid = value;
        }
        
  
        
        public MSCIdentificationNumber getMSCIdentificationNumber () {
            return this.mSCIdentificationNumber;
        }

        
        public boolean isMSCIdentificationNumberPresent () {
            return this.mSCIdentificationNumber != null;
        }
        

        public void setMSCIdentificationNumber (MSCIdentificationNumber value) {
            this.mSCIdentificationNumber = value;
        }
        
  
        
        public MSID getMsid () {
            return this.msid;
        }

        
        public boolean isMsidPresent () {
            return this.msid != null;
        }
        

        public void setMsid (MSID value) {
            this.msid = value;
        }
        
  
        
        public PC_SSN getPc_ssn () {
            return this.pc_ssn;
        }

        
        public boolean isPc_ssnPresent () {
            return this.pc_ssn != null;
        }
        

        public void setPc_ssn (PC_SSN value) {
            this.pc_ssn = value;
        }
        
  
        
        public PilotBillingID getPilotBillingID () {
            return this.pilotBillingID;
        }

        
        public boolean isPilotBillingIDPresent () {
            return this.pilotBillingID != null;
        }
        

        public void setPilotBillingID (PilotBillingID value) {
            this.pilotBillingID = value;
        }
        
  
        
        public PilotNumber getPilotNumber () {
            return this.pilotNumber;
        }

        
        public boolean isPilotNumberPresent () {
            return this.pilotNumber != null;
        }
        

        public void setPilotNumber (PilotNumber value) {
            this.pilotNumber = value;
        }
        
  
        
        public PreferredLanguageIndicator getPreferredLanguageIndicator () {
            return this.preferredLanguageIndicator;
        }

        
        public boolean isPreferredLanguageIndicatorPresent () {
            return this.preferredLanguageIndicator != null;
        }
        

        public void setPreferredLanguageIndicator (PreferredLanguageIndicator value) {
            this.preferredLanguageIndicator = value;
        }
        
  
        
        public RedirectingPartyName getRedirectingPartyName () {
            return this.redirectingPartyName;
        }

        
        public boolean isRedirectingPartyNamePresent () {
            return this.redirectingPartyName != null;
        }
        

        public void setRedirectingPartyName (RedirectingPartyName value) {
            this.redirectingPartyName = value;
        }
        
  
        
        public RedirectingNumberDigits getRedirectingNumberDigits () {
            return this.redirectingNumberDigits;
        }

        
        public boolean isRedirectingNumberDigitsPresent () {
            return this.redirectingNumberDigits != null;
        }
        

        public void setRedirectingNumberDigits (RedirectingNumberDigits value) {
            this.redirectingNumberDigits = value;
        }
        
  
        
        public RedirectingSubaddress getRedirectingSubaddress () {
            return this.redirectingSubaddress;
        }

        
        public boolean isRedirectingSubaddressPresent () {
            return this.redirectingSubaddress != null;
        }
        

        public void setRedirectingSubaddress (RedirectingSubaddress value) {
            this.redirectingSubaddress = value;
        }
        
  
        
        public RedirectionReason getRedirectionReason () {
            return this.redirectionReason;
        }

        
        public boolean isRedirectionReasonPresent () {
            return this.redirectionReason != null;
        }
        

        public void setRedirectionReason (RedirectionReason value) {
            this.redirectionReason = value;
        }
        
  
        
        public RoutingDigits getRoutingDigits () {
            return this.routingDigits;
        }

        
        public boolean isRoutingDigitsPresent () {
            return this.routingDigits != null;
        }
        

        public void setRoutingDigits (RoutingDigits value) {
            this.routingDigits = value;
        }
        
  
        
        public SenderIdentificationNumber getSenderIdentificationNumber () {
            return this.senderIdentificationNumber;
        }

        
        public boolean isSenderIdentificationNumberPresent () {
            return this.senderIdentificationNumber != null;
        }
        

        public void setSenderIdentificationNumber (SenderIdentificationNumber value) {
            this.senderIdentificationNumber = value;
        }
        
  
        
        public ServingCellID getServingCellID () {
            return this.servingCellID;
        }

        
        public boolean isServingCellIDPresent () {
            return this.servingCellID != null;
        }
        

        public void setServingCellID (ServingCellID value) {
            this.servingCellID = value;
        }
        
  
        
        public SystemMyTypeCode getSystemMyTypeCode () {
            return this.systemMyTypeCode;
        }

        
        public boolean isSystemMyTypeCodePresent () {
            return this.systemMyTypeCode != null;
        }
        

        public void setSystemMyTypeCode (SystemMyTypeCode value) {
            this.systemMyTypeCode = value;
        }
        
  
        
        public TerminationAccessType getTerminationAccessType () {
            return this.terminationAccessType;
        }

        
        public boolean isTerminationAccessTypePresent () {
            return this.terminationAccessType != null;
        }
        

        public void setTerminationAccessType (TerminationAccessType value) {
            this.terminationAccessType = value;
        }
        
  
        
        public TimeDateOffset getTimeDateOffset () {
            return this.timeDateOffset;
        }

        
        public boolean isTimeDateOffsetPresent () {
            return this.timeDateOffset != null;
        }
        

        public void setTimeDateOffset (TimeDateOffset value) {
            this.timeDateOffset = value;
        }
        
  
        
        public TimeOfDay getTimeOfDay () {
            return this.timeOfDay;
        }

        
        public boolean isTimeOfDayPresent () {
            return this.timeOfDay != null;
        }
        

        public void setTimeOfDay (TimeOfDay value) {
            this.timeOfDay = value;
        }
        
  
        
        public TransactionCapability getTransactionCapability () {
            return this.transactionCapability;
        }

        
        public boolean isTransactionCapabilityPresent () {
            return this.transactionCapability != null;
        }
        

        public void setTransactionCapability (TransactionCapability value) {
            this.transactionCapability = value;
        }
        
  
        
        public TriggerType getTriggerType () {
            return this.triggerType;
        }

        
        public boolean isTriggerTypePresent () {
            return this.triggerType != null;
        }
        

        public void setTriggerType (TriggerType value) {
            this.triggerType = value;
        }
        
  
        
        public WINCapability getWinCapability () {
            return this.winCapability;
        }

        
        public boolean isWinCapabilityPresent () {
            return this.winCapability != null;
        }
        

        public void setWinCapability (WINCapability value) {
            this.winCapability = value;
        }
        
  
                
                
        public void initWithDefaults() {
            
        }

        public IASN1PreparedElementData getPreparedData() {
            return preparedData_ServiceRequestSequenceType;
        }

       private static IASN1PreparedElementData preparedData_ServiceRequestSequenceType = CoderFactory.getInstance().newPreparedElementData(ServiceRequestSequenceType.class);
                
       }

       
                
        @ASN1Element ( name = "ServiceRequest", isOptional =  false , hasTag =  true, tag = 18, 
        tagClass =  TagClass.Private  , hasDefaultValue =  false  )
    
        private ServiceRequestSequenceType  value;        

        
        
        public ServiceRequest () {
        }
        
        
        
        public void setValue(ServiceRequestSequenceType value) {
            this.value = value;
        }
        
        
        
        public ServiceRequestSequenceType getValue() {
            return this.value;
        }            
        

	    public void initWithDefaults() {
	    }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(ServiceRequest.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            