
package asnGenerated.v2;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Choice ( name = "CAMEL_SCIBillingChargingCharacteristics" )
    public class CAMEL_SCIBillingChargingCharacteristics implements IASN1PreparedElement {
            
        @ASN1Element ( name = "aOCBeforeAnswer", isOptional =  false , hasTag =  true, tag = 0 , hasDefaultValue =  false  )
    
	private AOCBeforeAnswer aOCBeforeAnswer = null;
                
  
        @ASN1Element ( name = "aOCAfterAnswer", isOptional =  false , hasTag =  true, tag = 1 , hasDefaultValue =  false  )
    
	private AOCSubsequent aOCAfterAnswer = null;
                
  
        
        public AOCBeforeAnswer getAOCBeforeAnswer () {
            return this.aOCBeforeAnswer;
        }

        public boolean isAOCBeforeAnswerSelected () {
            return this.aOCBeforeAnswer != null;
        }

        private void setAOCBeforeAnswer (AOCBeforeAnswer value) {
            this.aOCBeforeAnswer = value;
        }

        
        public void selectAOCBeforeAnswer (AOCBeforeAnswer value) {
            this.aOCBeforeAnswer = value;
            
                    setAOCAfterAnswer(null);
                            
        }

        
  
        
        public AOCSubsequent getAOCAfterAnswer () {
            return this.aOCAfterAnswer;
        }

        public boolean isAOCAfterAnswerSelected () {
            return this.aOCAfterAnswer != null;
        }

        private void setAOCAfterAnswer (AOCSubsequent value) {
            this.aOCAfterAnswer = value;
        }

        
        public void selectAOCAfterAnswer (AOCSubsequent value) {
            this.aOCAfterAnswer = value;
            
                    setAOCBeforeAnswer(null);
                            
        }

        
  

	    public void initWithDefaults() {
	    }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(CAMEL_SCIBillingChargingCharacteristics.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }


    }
            