
package asnGenerated.v2;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1BoxedType ( name = "RequestedInformationTypeList" )
    public class RequestedInformationTypeList implements IASN1PreparedElement {
                
            @ASN1ValueRangeConstraint ( 
		
		min = 1L, 
		
		max = 4L 
		
	   )
	   
            @ASN1SequenceOf( name = "RequestedInformationTypeList" , isSetOf = false)
	    private java.util.Collection<RequestedInformationType> value = null; 
    
            public RequestedInformationTypeList () {
            }
        
            public RequestedInformationTypeList ( java.util.Collection<RequestedInformationType> value ) {
                setValue(value);
            }
                        
            public void setValue(java.util.Collection<RequestedInformationType> value) {
                this.value = value;
            }
            
            public java.util.Collection<RequestedInformationType> getValue() {
                return this.value;
            }            
            
            public void initValue() {
                setValue(new java.util.LinkedList<RequestedInformationType>()); 
            }
            
            public void add(RequestedInformationType item) {
                value.add(item);
            }

	    public void initWithDefaults() {
	    }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(RequestedInformationTypeList.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }


    }
            