
package asnGenerated.v2;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Sequence ( name = "ResetTimerArg", isSet = false )
    public class ResetTimerArg implements IASN1PreparedElement {
            
        @ASN1Element ( name = "timerID", isOptional =  false , hasTag =  true, tag = 0 , hasDefaultValue =  true  )
    
	private TimerID timerID = null;
                
  
        @ASN1Element ( name = "timervalue", isOptional =  false , hasTag =  true, tag = 1 , hasDefaultValue =  false  )
    
	private TimerValue timervalue = null;
                
  
@ASN1SequenceOf( name = "extensions", isSetOf = false ) 

    @ASN1ValueRangeConstraint ( 
		
		min = 1L, 
		
		max = 10L 
		
	   )
	   
        @ASN1Element ( name = "extensions", isOptional =  true , hasTag =  true, tag = 2 , hasDefaultValue =  false  )
    
	private java.util.Collection<ExtensionField>  extensions = null;
                
  
        
        public TimerID getTimerID () {
            return this.timerID;
        }

        

        public void setTimerID (TimerID value) {
            this.timerID = value;
        }
        
  
        
        public TimerValue getTimervalue () {
            return this.timervalue;
        }

        

        public void setTimervalue (TimerValue value) {
            this.timervalue = value;
        }
        
  
        
        public java.util.Collection<ExtensionField>  getExtensions () {
            return this.extensions;
        }

        
        public boolean isExtensionsPresent () {
            return this.extensions != null;
        }
        

        public void setExtensions (java.util.Collection<ExtensionField>  value) {
            this.extensions = value;
        }
        
  

        public void initWithDefaults() {
            TimerID param_TimerID = new TimerID();
            param_TimerID.setValue(TimerID.EnumType.tssf);
            setTimerID(param_TimerID);
        }
                    
        //asn auto genreted
       /* public void initWithDefaults() {
            TimerID param_TimerID =         
            ;
        setTimerID(param_TimerID);
    
        }*/

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(ResetTimerArg.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            