
package com.agnity.inapitutcs2.asngenerated;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Enum (
        name = "Media"
    )
    public class Media implements IASN1PreparedElement {        
        public enum EnumType {
            
            @ASN1EnumItem ( name = "voiceMail", hasTag = true , tag = 0 )
            voiceMail , 
            @ASN1EnumItem ( name = "faxGroup3", hasTag = true , tag = 1 )
            faxGroup3 , 
            @ASN1EnumItem ( name = "faxGroup4", hasTag = true , tag = 2 )
            faxGroup4 , 
        }
        
        private EnumType value;
        private Integer integerForm;
        
        public EnumType getValue() {
            return this.value;
        }
        
        public void setValue(EnumType value) {
            this.value = value;
        }
        
        public Integer getIntegerForm() {
            return integerForm;
        }
        
        public void setIntegerForm(Integer value) {
            integerForm = value;
        }

	    public void initWithDefaults() {
	    }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(Media.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }


    }
            