
package com.agnity.inapitutcs2.asngenerated;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Sequence ( name = "MidCallInfoType", isSet = false )
    public class MidCallInfoType implements IASN1PreparedElement {
            
        @ASN1Element ( name = "iNServiceControlCodeLow", isOptional =  false , hasTag =  true, tag = 0 , hasDefaultValue =  false  )
    
	private Digits iNServiceControlCodeLow = null;
                
  
        @ASN1Element ( name = "iNServiceControlCodeHigh", isOptional =  true , hasTag =  true, tag = 1 , hasDefaultValue =  false  )
    
	private Digits iNServiceControlCodeHigh = null;
                
  
        
        public Digits getINServiceControlCodeLow () {
            return this.iNServiceControlCodeLow;
        }

        

        public void setINServiceControlCodeLow (Digits value) {
            this.iNServiceControlCodeLow = value;
        }
        
  
        
        public Digits getINServiceControlCodeHigh () {
            return this.iNServiceControlCodeHigh;
        }

        
        public boolean isINServiceControlCodeHighPresent () {
            return this.iNServiceControlCodeHigh != null;
        }
        

        public void setINServiceControlCodeHigh (Digits value) {
            this.iNServiceControlCodeHigh = value;
        }
        
  
                    
        
        public void initWithDefaults() {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(MidCallInfoType.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            