
package com.agnity.inapitutcs2.asngenerated;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Enum (
        name = "Notification"
    )
    public class Notification implements IASN1PreparedElement {        
        public enum EnumType {
            
            @ASN1EnumItem ( name = "userAbandon", hasTag = true , tag = 0 )
            userAbandon , 
            @ASN1EnumItem ( name = "callFailure", hasTag = true , tag = 1 )
            callFailure , 
            @ASN1EnumItem ( name = "noReply", hasTag = true , tag = 2 )
            noReply , 
            @ASN1EnumItem ( name = "callRelease", hasTag = true , tag = 3 )
            callRelease , 
            @ASN1EnumItem ( name = "ssInvocation", hasTag = true , tag = 4 )
            ssInvocation , 
            @ASN1EnumItem ( name = "creditLimitReached", hasTag = true , tag = 5 )
            creditLimitReached , 
            @ASN1EnumItem ( name = "callDuration", hasTag = true , tag = 6 )
            callDuration , 
            @ASN1EnumItem ( name = "calledNumber", hasTag = true , tag = 7 )
            calledNumber , 
            @ASN1EnumItem ( name = "answeredCall", hasTag = true , tag = 8 )
            answeredCall , 
        }
        
        private EnumType value;
        private Integer integerForm;
        
        public EnumType getValue() {
            return this.value;
        }
        
        public void setValue(EnumType value) {
            this.value = value;
        }
        
        public Integer getIntegerForm() {
            return integerForm;
        }
        
        public void setIntegerForm(Integer value) {
            integerForm = value;
        }

	    public void initWithDefaults() {
	    }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(Notification.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }


    }
            