
package com.agnity.inapitutcs2.asngenerated;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Sequence ( name = "ServiceInteractionIndicatorsTwo", isSet = false )
    public class ServiceInteractionIndicatorsTwo implements IASN1PreparedElement {
            
        @ASN1Element ( name = "forwardServiceInteractionInd", isOptional =  true , hasTag =  true, tag = 0 , hasDefaultValue =  false  )
    
	private ForwardServiceInteractionInd forwardServiceInteractionInd = null;
                
  
        @ASN1Element ( name = "backwardServiceInteractionInd", isOptional =  true , hasTag =  true, tag = 1 , hasDefaultValue =  false  )
    
	private BackwardServiceInteractionInd backwardServiceInteractionInd = null;
                
  
        @ASN1Element ( name = "bothwayThroughConnectionInd", isOptional =  true , hasTag =  true, tag = 2 , hasDefaultValue =  false  )
    
	private BothwayThroughConnectionInd bothwayThroughConnectionInd = null;
                
  
        @ASN1Element ( name = "suspendTimer", isOptional =  true , hasTag =  true, tag = 3 , hasDefaultValue =  false  )
    
	private SuspendTimer suspendTimer = null;
                
  
        @ASN1Element ( name = "connectedNumberTreatmentInd", isOptional =  true , hasTag =  true, tag = 4 , hasDefaultValue =  false  )
    
	private ConnectedNumberTreatmentInd connectedNumberTreatmentInd = null;
                
  @ASN1Boolean( name = "" )
    
        @ASN1Element ( name = "suppressCallDiversionNotification", isOptional =  true , hasTag =  true, tag = 5 , hasDefaultValue =  false  )
    
	private Boolean suppressCallDiversionNotification = null;
                
  @ASN1Boolean( name = "" )
    
        @ASN1Element ( name = "suppressCallTransferNotification", isOptional =  true , hasTag =  true, tag = 6 , hasDefaultValue =  false  )
    
	private Boolean suppressCallTransferNotification = null;
                
  @ASN1Boolean( name = "" )
    
        @ASN1Element ( name = "allowCdINNoPresentationInd", isOptional =  true , hasTag =  true, tag = 7 , hasDefaultValue =  false  )
    
	private Boolean allowCdINNoPresentationInd = null;
                
  @ASN1Boolean( name = "" )
    
        @ASN1Element ( name = "userDialogueDurationInd", isOptional =  false , hasTag =  true, tag = 8 , hasDefaultValue =  true  )
    
	private Boolean userDialogueDurationInd = null;
                
  
        
        public ForwardServiceInteractionInd getForwardServiceInteractionInd () {
            return this.forwardServiceInteractionInd;
        }

        
        public boolean isForwardServiceInteractionIndPresent () {
            return this.forwardServiceInteractionInd != null;
        }
        

        public void setForwardServiceInteractionInd (ForwardServiceInteractionInd value) {
            this.forwardServiceInteractionInd = value;
        }
        
  
        
        public BackwardServiceInteractionInd getBackwardServiceInteractionInd () {
            return this.backwardServiceInteractionInd;
        }

        
        public boolean isBackwardServiceInteractionIndPresent () {
            return this.backwardServiceInteractionInd != null;
        }
        

        public void setBackwardServiceInteractionInd (BackwardServiceInteractionInd value) {
            this.backwardServiceInteractionInd = value;
        }
        
  
        
        public BothwayThroughConnectionInd getBothwayThroughConnectionInd () {
            return this.bothwayThroughConnectionInd;
        }

        
        public boolean isBothwayThroughConnectionIndPresent () {
            return this.bothwayThroughConnectionInd != null;
        }
        

        public void setBothwayThroughConnectionInd (BothwayThroughConnectionInd value) {
            this.bothwayThroughConnectionInd = value;
        }
        
  
        
        public SuspendTimer getSuspendTimer () {
            return this.suspendTimer;
        }

        
        public boolean isSuspendTimerPresent () {
            return this.suspendTimer != null;
        }
        

        public void setSuspendTimer (SuspendTimer value) {
            this.suspendTimer = value;
        }
        
  
        
        public ConnectedNumberTreatmentInd getConnectedNumberTreatmentInd () {
            return this.connectedNumberTreatmentInd;
        }

        
        public boolean isConnectedNumberTreatmentIndPresent () {
            return this.connectedNumberTreatmentInd != null;
        }
        

        public void setConnectedNumberTreatmentInd (ConnectedNumberTreatmentInd value) {
            this.connectedNumberTreatmentInd = value;
        }
        
  
        
        public Boolean getSuppressCallDiversionNotification () {
            return this.suppressCallDiversionNotification;
        }

        
        public boolean isSuppressCallDiversionNotificationPresent () {
            return this.suppressCallDiversionNotification != null;
        }
        

        public void setSuppressCallDiversionNotification (Boolean value) {
            this.suppressCallDiversionNotification = value;
        }
        
  
        
        public Boolean getSuppressCallTransferNotification () {
            return this.suppressCallTransferNotification;
        }

        
        public boolean isSuppressCallTransferNotificationPresent () {
            return this.suppressCallTransferNotification != null;
        }
        

        public void setSuppressCallTransferNotification (Boolean value) {
            this.suppressCallTransferNotification = value;
        }
        
  
        
        public Boolean getAllowCdINNoPresentationInd () {
            return this.allowCdINNoPresentationInd;
        }

        
        public boolean isAllowCdINNoPresentationIndPresent () {
            return this.allowCdINNoPresentationInd != null;
        }
        

        public void setAllowCdINNoPresentationInd (Boolean value) {
            this.allowCdINNoPresentationInd = value;
        }
        
  
        
        public Boolean getUserDialogueDurationInd () {
            return this.userDialogueDurationInd;
        }

        

        public void setUserDialogueDurationInd (Boolean value) {
            this.userDialogueDurationInd = value;
        }
        
  
                    
        
        public void initWithDefaults() {
            Boolean param_UserDialogueDurationInd =         
            null;
        setUserDialogueDurationInd(param_UserDialogueDurationInd);
    
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(ServiceInteractionIndicatorsTwo.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            