CREATE TABLE CDR_DATA_TBL (
SWITCH_CODE VARCHAR2(20),
STATUS_IND_ATTMPTD_CALL VARCHAR2(20),
STATUS_IND_FAILED_CALL VARCHAR2(20),
STATUS_IND_INTRMDT_CALL VARCHAR2(20),
STATUS_IND_NON_CHRGD_CALL VARCHAR2(20),
CHARGE_TABLE_TYPE VARCHAR2(20),
CALLING_ID_MA VARCHAR2(40),
CALLED_ID VARCHAR2(40),
START_TIME  VARCHAR2(40),
ANSWER_TIME VARCHAR2(40),
DISCONNECT_TIME VARCHAR2(40),
TERM_INTERWORKING_IND VARCHAR2(20),
ORIG_INTERWORKING_IND VARCHAR2(20),
TERM_ISUP1_LINK_IND VARCHAR2(20),
ORIG_ISUP1_LINK_IND VARCHAR2(20),
TERM_ISDN_ACCESS_IND VARCHAR2(20),
ORIG_ISDN_ACCESS_IND VARCHAR2(20),
CHARGE_INDICATOR VARCHAR2(20),
CALLING_PARTY_CATEGORY VARCHAR2(20),
CHARGE_ID_OPTION VARCHAR2(30),
RECEIVED_INFORMATION_OPTION VARCHAR2(70),
SERVICE_INDICATOR VARCHAR2(30),
ATTEMPTED_OPTION VARCHAR2(60),
CALLING_ID_OPTION VARCHAR2(40),
SIGNALING_NW_USAGE_OPTION VARCHAR2(30),
VPN_OPTION VARCHAR2(120),
ORIG_TERM_CA_OPTION VARCHAR2(40),
FW_DIR_CIT_INFORMATION VARCHAR2(120),
BW_DIR_CIT_INFORMATION VARCHAR2(120),
UAN_OPTION VARCHAR2(50),
FILENAME VARCHAR2(50),
IS_SFTPED NUMBER(1) DEFAULT 0,
CREATED_ON TIMESTAMP DEFAULT TO_TIMESTAMP(SYSDATE),
CONSTRAINT CDR_DATA_TBL_UK UNIQUE (CALLING_ID_MA, CALLED_ID, START_TIME, STATUS_IND_INTRMDT_CALL)
);	
ALTER TABLE CDR_DATA_TBL ADD SENT_FILENAME VARCHAR2(50);
ALTER TABLE CDR_DATA_TBL ADD CDR_CNT VARCHAR2(10);
ALTER TABLE CDR_DATA_TBL ADD CALL_IDENTIFIER VARCHAR2(200);
ALTER TABLE CDR_DATA_TBL MODIFY CREATED_ON TIMESTAMP DEFAULT SYSDATE;
ALTER TABLE CDR_DATA_TBL DROP CONSTRAINT CDR_DATA_TBL_UK ;
ALTER TABLE CDR_DATA_TBL ADD CONSTRAINT CDR_DATA_TBL_UK UNIQUE (CALL_IDENTIFIER, CDR_CNT, START_TIME);
CREATE INDEX IDX_FILENAME ON CDR_DATA_TBL(FILENAME);
CREATE INDEX IDX_IS_SFTPED ON CDR_DATA_TBL(IS_SFTPED);
CREATE INDEX IDX_CREATED_ON ON CDR_DATA_TBL(CREATED_ON);
CREATE INDEX IDX_SENT_FILENAME ON CDR_DATA_TBL(SENT_FILENAME);
ALTER TABLE CDR_DATA_TBL ADD ACPC VARCHAR2(40);
