
package com.agnity.ain.asngenerated;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1BoxedType ( name = "ACGGlobalOverride" )
    public class ACGGlobalOverride implements IASN1PreparedElement {
                
        

    @ASN1PreparedElement
    @ASN1Enum (
        name = "ACGGlobalOverrideEnumType"
    )
    public static class ACGGlobalOverrideEnumType implements IASN1PreparedElement {        
        public enum EnumType {
            
            @ASN1EnumItem ( name = "allItems", hasTag = true , tag = 0 )
            allItems , 
            @ASN1EnumItem ( name = "scpOverloadItems", hasTag = true , tag = 1 )
            scpOverloadItems , 
            @ASN1EnumItem ( name = "smsInitCntrlExceptZeroGap", hasTag = true , tag = 2 )
            smsInitCntrlExceptZeroGap , 
            @ASN1EnumItem ( name = "smsInitCntrl", hasTag = true , tag = 3 )
            smsInitCntrl , 
            @ASN1EnumItem ( name = "ntmOSInitCntrlExceptZeroGap", hasTag = true , tag = 4 )
            ntmOSInitCntrlExceptZeroGap , 
            @ASN1EnumItem ( name = "ntmOSInitCntrl", hasTag = true , tag = 5 )
            ntmOSInitCntrl , 
            @ASN1EnumItem ( name = "craftInitCntrlExceptZeroGap", hasTag = true , tag = 6 )
            craftInitCntrlExceptZeroGap , 
            @ASN1EnumItem ( name = "craftInitCntrl", hasTag = true , tag = 7 )
            craftInitCntrl , 
        }
        
        private EnumType value;
        private Integer integerForm;
        
        public EnumType getValue() {
            return this.value;
        }
        
        public void setValue(EnumType value) {
            this.value = value;
        }
        
        public Integer getIntegerForm() {
            return integerForm;
        }
        
        public void setIntegerForm(Integer value) {
            integerForm = value;
        }

	    public void initWithDefaults() {
	    }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(ACGGlobalOverrideEnumType.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

    }
                
        @ASN1Element ( name = "ACGGlobalOverride", isOptional =  false , hasTag =  true, tag = 110 , hasDefaultValue =  false  )
    
        private ACGGlobalOverrideEnumType  value;        

        
        
        public ACGGlobalOverride () {
        }
        
        
        
        public void setValue(ACGGlobalOverrideEnumType value) {
            this.value = value;
        }
        
        
        
        public ACGGlobalOverrideEnumType getValue() {
            return this.value;
        }            
        

	    public void initWithDefaults() {
	    }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(ACGGlobalOverride.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            