
package com.agnity.ain.asngenerated;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1BoxedType ( name = "AnswerIndicator" )
    public class AnswerIndicator implements IASN1PreparedElement {
                
        
        @ASN1Null ( name = "AnswerIndicator" ) 
    
        @ASN1Element ( name = "AnswerIndicator", isOptional =  false , hasTag =  true, tag = 12 , hasDefaultValue =  false  )
    
        private org.bn.types.NullObject  value;        

        

	    public void initWithDefaults() {
	    }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(AnswerIndicator.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            