
package com.agnity.ain.asngenerated;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1BoxedType ( name = "ForwardToDn" )
    public class ForwardToDn implements IASN1PreparedElement {
                
        
        @ASN1Element ( name = "ForwardToDn", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
        private Dn  value;        

        
        
        public ForwardToDn () {
        }
        
        
        
        public void setValue(Dn value) {
            this.value = value;
        }
        
        
        
        public Dn getValue() {
            return this.value;
        }            
        

	    public void initWithDefaults() {
	    }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(ForwardToDn.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            