
package com.agnity.ain.asngenerated;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Sequence ( name = "FurnishAMAInformationArg", isSet = false )
    public class FurnishAMAInformationArg implements IASN1PreparedElement {
            
        @ASN1Element ( name = "aMABAFModules", isOptional =  true , hasTag =  false  , hasDefaultValue =  false  )
    
	private AMABAFModules aMABAFModules = null;
                
  
        @ASN1Element ( name = "aMASetHexABIndicator", isOptional =  true , hasTag =  false  , hasDefaultValue =  false  )
    
	private AMASetHexABIndicator aMASetHexABIndicator = null;
                
  
        @ASN1Element ( name = "extensionParameter", isOptional =  true , hasTag =  false  , hasDefaultValue =  false  )
    
	private ExtensionParameter extensionParameter = null;
                
  
        
        public AMABAFModules getAMABAFModules () {
            return this.aMABAFModules;
        }

        
        public boolean isAMABAFModulesPresent () {
            return this.aMABAFModules != null;
        }
        

        public void setAMABAFModules (AMABAFModules value) {
            this.aMABAFModules = value;
        }
        
  
        
        public AMASetHexABIndicator getAMASetHexABIndicator () {
            return this.aMASetHexABIndicator;
        }

        
        public boolean isAMASetHexABIndicatorPresent () {
            return this.aMASetHexABIndicator != null;
        }
        

        public void setAMASetHexABIndicator (AMASetHexABIndicator value) {
            this.aMASetHexABIndicator = value;
        }
        
  
        
        public ExtensionParameter getExtensionParameter () {
            return this.extensionParameter;
        }

        
        public boolean isExtensionParameterPresent () {
            return this.extensionParameter != null;
        }
        

        public void setExtensionParameter (ExtensionParameter value) {
            this.extensionParameter = value;
        }
        
  
                    
        
        public void initWithDefaults() {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(FurnishAMAInformationArg.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            