
package com.agnity.ain.asngenerated;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Choice ( name = "IPStrParameterBlock" )
    public class IPStrParameterBlock implements IASN1PreparedElement {
            
        @ASN1Element ( name = "announcementBlock", isOptional =  false , hasTag =  true, tag = 0 , hasDefaultValue =  false  )
    
	private AnnouncementBlock announcementBlock = null;
                
  
        @ASN1Element ( name = "announcementDigitBlock", isOptional =  false , hasTag =  true, tag = 1 , hasDefaultValue =  false  )
    
	private AnnouncementDigitBlock announcementDigitBlock = null;
                
  
        @ASN1Element ( name = "textSpeechBlock", isOptional =  false , hasTag =  true, tag = 2 , hasDefaultValue =  false  )
    
	private TextSpeechBlock textSpeechBlock = null;
                
  
        @ASN1Element ( name = "textSpeechDigitBlock", isOptional =  false , hasTag =  true, tag = 3 , hasDefaultValue =  false  )
    
	private TextSpeechDigitBlock textSpeechDigitBlock = null;
                
  
        @ASN1Element ( name = "voiceConnectionBlock", isOptional =  false , hasTag =  true, tag = 4 , hasDefaultValue =  false  )
    
	private VoiceConnectionBlock voiceConnectionBlock = null;
                
  
        @ASN1Element ( name = "playAppRequestParam", isOptional =  false , hasTag =  true, tag = 254 , hasDefaultValue =  false  )
    
	private PlayAppRequestParam playAppRequestParam = null;
                
  
        
        public AnnouncementBlock getAnnouncementBlock () {
            return this.announcementBlock;
        }

        public boolean isAnnouncementBlockSelected () {
            return this.announcementBlock != null;
        }

        private void setAnnouncementBlock (AnnouncementBlock value) {
            this.announcementBlock = value;
        }

        
        public void selectAnnouncementBlock (AnnouncementBlock value) {
            this.announcementBlock = value;
            
                    setAnnouncementDigitBlock(null);
                
                    setTextSpeechBlock(null);
                
                    setTextSpeechDigitBlock(null);
                
                    setVoiceConnectionBlock(null);
                
                    setPlayAppRequestParam(null);
                            
        }

        
  
        
        public AnnouncementDigitBlock getAnnouncementDigitBlock () {
            return this.announcementDigitBlock;
        }

        public boolean isAnnouncementDigitBlockSelected () {
            return this.announcementDigitBlock != null;
        }

        private void setAnnouncementDigitBlock (AnnouncementDigitBlock value) {
            this.announcementDigitBlock = value;
        }

        
        public void selectAnnouncementDigitBlock (AnnouncementDigitBlock value) {
            this.announcementDigitBlock = value;
            
                    setAnnouncementBlock(null);
                
                    setTextSpeechBlock(null);
                
                    setTextSpeechDigitBlock(null);
                
                    setVoiceConnectionBlock(null);
                
                    setPlayAppRequestParam(null);
                            
        }

        
  
        
        public TextSpeechBlock getTextSpeechBlock () {
            return this.textSpeechBlock;
        }

        public boolean isTextSpeechBlockSelected () {
            return this.textSpeechBlock != null;
        }

        private void setTextSpeechBlock (TextSpeechBlock value) {
            this.textSpeechBlock = value;
        }

        
        public void selectTextSpeechBlock (TextSpeechBlock value) {
            this.textSpeechBlock = value;
            
                    setAnnouncementBlock(null);
                
                    setAnnouncementDigitBlock(null);
                
                    setTextSpeechDigitBlock(null);
                
                    setVoiceConnectionBlock(null);
                
                    setPlayAppRequestParam(null);
                            
        }

        
  
        
        public TextSpeechDigitBlock getTextSpeechDigitBlock () {
            return this.textSpeechDigitBlock;
        }

        public boolean isTextSpeechDigitBlockSelected () {
            return this.textSpeechDigitBlock != null;
        }

        private void setTextSpeechDigitBlock (TextSpeechDigitBlock value) {
            this.textSpeechDigitBlock = value;
        }

        
        public void selectTextSpeechDigitBlock (TextSpeechDigitBlock value) {
            this.textSpeechDigitBlock = value;
            
                    setAnnouncementBlock(null);
                
                    setAnnouncementDigitBlock(null);
                
                    setTextSpeechBlock(null);
                
                    setVoiceConnectionBlock(null);
                
                    setPlayAppRequestParam(null);
                            
        }

        
  
        
        public VoiceConnectionBlock getVoiceConnectionBlock () {
            return this.voiceConnectionBlock;
        }

        public boolean isVoiceConnectionBlockSelected () {
            return this.voiceConnectionBlock != null;
        }

        private void setVoiceConnectionBlock (VoiceConnectionBlock value) {
            this.voiceConnectionBlock = value;
        }

        
        public void selectVoiceConnectionBlock (VoiceConnectionBlock value) {
            this.voiceConnectionBlock = value;
            
                    setAnnouncementBlock(null);
                
                    setAnnouncementDigitBlock(null);
                
                    setTextSpeechBlock(null);
                
                    setTextSpeechDigitBlock(null);
                
                    setPlayAppRequestParam(null);
                            
        }

        
  
        
        public PlayAppRequestParam getPlayAppRequestParam () {
            return this.playAppRequestParam;
        }

        public boolean isPlayAppRequestParamSelected () {
            return this.playAppRequestParam != null;
        }

        private void setPlayAppRequestParam (PlayAppRequestParam value) {
            this.playAppRequestParam = value;
        }

        
        public void selectPlayAppRequestParam (PlayAppRequestParam value) {
            this.playAppRequestParam = value;
            
                    setAnnouncementBlock(null);
                
                    setAnnouncementDigitBlock(null);
                
                    setTextSpeechBlock(null);
                
                    setTextSpeechDigitBlock(null);
                
                    setVoiceConnectionBlock(null);
                            
        }

        
  

	    public void initWithDefaults() {
	    }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(IPStrParameterBlock.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }


    }
            