
package com.agnity.ain.asngenerated;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1BoxedType ( name = "PartyID" )
    public class PartyID implements IASN1PreparedElement {
                
        

    @ASN1PreparedElement
    @ASN1Enum (
        name = "PartyIDEnumType"
    )
    public static class PartyIDEnumType implements IASN1PreparedElement {        
        public enum EnumType {
            
            @ASN1EnumItem ( name = "callingParty", hasTag = true , tag = 0 )
            callingParty , 
            @ASN1EnumItem ( name = "calledParty", hasTag = true , tag = 1 )
            calledParty , 
            @ASN1EnumItem ( name = "bothParties", hasTag = true , tag = 2 )
            bothParties , 
        }
        
        private EnumType value;
        private Integer integerForm;
        
        public EnumType getValue() {
            return this.value;
        }
        
        public void setValue(EnumType value) {
            this.value = value;
        }
        
        public Integer getIntegerForm() {
            return integerForm;
        }
        
        public void setIntegerForm(Integer value) {
            integerForm = value;
        }

	    public void initWithDefaults() {
	    }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(PartyIDEnumType.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

    }
                
        @ASN1Element ( name = "PartyID", isOptional =  false , hasTag =  true, tag = 159 , hasDefaultValue =  false  )
    
        private PartyIDEnumType  value;        

        
        
        public PartyID () {
        }
        
        
        
        public void setValue(PartyIDEnumType value) {
            this.value = value;
        }
        
        
        
        public PartyIDEnumType getValue() {
            return this.value;
        }            
        

	    public void initWithDefaults() {
	    }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(PartyID.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            