
package com.agnity.ain.asngenerated;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Sequence ( name = "PlayAppSubParam", isSet = false )
    public class PlayAppSubParam implements IASN1PreparedElement {
            
        @ASN1Element ( name = "playAppSubParamId", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private PlayAppSubParamId playAppSubParamId = null;
                
  
        @ASN1Element ( name = "playAppSubParamValue", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private PlayAppSubParamValue playAppSubParamValue = null;
                
  
        
        public PlayAppSubParamId getPlayAppSubParamId () {
            return this.playAppSubParamId;
        }

        

        public void setPlayAppSubParamId (PlayAppSubParamId value) {
            this.playAppSubParamId = value;
        }
        
  
        
        public PlayAppSubParamValue getPlayAppSubParamValue () {
            return this.playAppSubParamValue;
        }

        

        public void setPlayAppSubParamValue (PlayAppSubParamValue value) {
            this.playAppSubParamValue = value;
        }
        
  
                    
        
        public void initWithDefaults() {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(PlayAppSubParam.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            