
package com.agnity.ain.asngenerated;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Sequence ( name = "RequestGroup5", isSet = false )
    public class RequestGroup5 implements IASN1PreparedElement {
            
        @ASN1Element ( name = "service5", isOptional =  false , hasTag =  true, tag = 1 , hasDefaultValue =  false  )
    
	private Service5 service5 = null;
                
  
        @ASN1Element ( name = "request5", isOptional =  false , hasTag =  true, tag = 2 , hasDefaultValue =  false  )
    
	private Request5 request5 = null;
                
  
        
        public Service5 getService5 () {
            return this.service5;
        }

        

        public void setService5 (Service5 value) {
            this.service5 = value;
        }
        
  
        
        public Request5 getRequest5 () {
            return this.request5;
        }

        

        public void setRequest5 (Request5 value) {
            this.request5 = value;
        }
        
  
                    
        
        public void initWithDefaults() {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(RequestGroup5.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            