
package com.agnity.ain.asngenerated;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Sequence ( name = "RequestGroup4", isSet = false )
    public class RequestGroup4 implements IASN1PreparedElement {
            
        @ASN1Element ( name = "service4", isOptional =  false , hasTag =  true, tag = 1 , hasDefaultValue =  false  )
    
	private Service4 service4 = null;
                
  
        @ASN1Element ( name = "request4", isOptional =  false , hasTag =  true, tag = 2 , hasDefaultValue =  false  )
    
	private Request4 request4 = null;
                
  
        
        public Service4 getService4 () {
            return this.service4;
        }

        

        public void setService4 (Service4 value) {
            this.service4 = value;
        }
        
  
        
        public Request4 getRequest4 () {
            return this.request4;
        }

        

        public void setRequest4 (Request4 value) {
            this.request4 = value;
        }
        
  
                    
        
        public void initWithDefaults() {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(RequestGroup4.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            