
package com.agnity.ain.asngenerated;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Sequence ( name = "TerminationNotificationArg", isSet = false )
    public class TerminationNotificationArg implements IASN1PreparedElement {
            
        @ASN1Element ( name = "echoData", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private EchoData echoData = null;
                
  
        @ASN1Element ( name = "terminationIndicator", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private TerminationIndicator terminationIndicator = null;
                
  
        @ASN1Element ( name = "connectTime", isOptional =  true , hasTag =  false  , hasDefaultValue =  false  )
    
	private ConnectTime connectTime = null;
                
  
        @ASN1Element ( name = "busyCause", isOptional =  true , hasTag =  false  , hasDefaultValue =  false  )
    
	private BusyCause busyCause = null;
                
  
        @ASN1Element ( name = "amp1", isOptional =  true , hasTag =  false  , hasDefaultValue =  false  )
    
	private Amp1 amp1 = null;
                
  
        @ASN1Element ( name = "amp2", isOptional =  true , hasTag =  false  , hasDefaultValue =  false  )
    
	private Amp2 amp2 = null;
                
  
        @ASN1Element ( name = "extensionParameter", isOptional =  true , hasTag =  false  , hasDefaultValue =  false  )
    
	private ExtensionParameter extensionParameter = null;
                
  
        
        public EchoData getEchoData () {
            return this.echoData;
        }

        

        public void setEchoData (EchoData value) {
            this.echoData = value;
        }
        
  
        
        public TerminationIndicator getTerminationIndicator () {
            return this.terminationIndicator;
        }

        

        public void setTerminationIndicator (TerminationIndicator value) {
            this.terminationIndicator = value;
        }
        
  
        
        public ConnectTime getConnectTime () {
            return this.connectTime;
        }

        
        public boolean isConnectTimePresent () {
            return this.connectTime != null;
        }
        

        public void setConnectTime (ConnectTime value) {
            this.connectTime = value;
        }
        
  
        
        public BusyCause getBusyCause () {
            return this.busyCause;
        }

        
        public boolean isBusyCausePresent () {
            return this.busyCause != null;
        }
        

        public void setBusyCause (BusyCause value) {
            this.busyCause = value;
        }
        
  
        
        public Amp1 getAmp1 () {
            return this.amp1;
        }

        
        public boolean isAmp1Present () {
            return this.amp1 != null;
        }
        

        public void setAmp1 (Amp1 value) {
            this.amp1 = value;
        }
        
  
        
        public Amp2 getAmp2 () {
            return this.amp2;
        }

        
        public boolean isAmp2Present () {
            return this.amp2 != null;
        }
        

        public void setAmp2 (Amp2 value) {
            this.amp2 = value;
        }
        
  
        
        public ExtensionParameter getExtensionParameter () {
            return this.extensionParameter;
        }

        
        public boolean isExtensionParameterPresent () {
            return this.extensionParameter != null;
        }
        

        public void setExtensionParameter (ExtensionParameter value) {
            this.extensionParameter = value;
        }
        
  
                    
        
        public void initWithDefaults() {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(TerminationNotificationArg.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            