
package com.agnity.ain.asngenerated;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Choice ( name = "TextElement" )
    public class TextElement implements IASN1PreparedElement {
            
        @ASN1Element ( name = "plainText", isOptional =  false , hasTag =  true, tag = 0 , hasDefaultValue =  false  )
    
	private PlainText plainText = null;
                
  
        @ASN1Element ( name = "dTMFPlainText", isOptional =  false , hasTag =  true, tag = 1 , hasDefaultValue =  false  )
    
	private DTMFPlainText dTMFPlainText = null;
                
  
        @ASN1Element ( name = "intPlainText", isOptional =  false , hasTag =  true, tag = 2 , hasDefaultValue =  false  )
    
	private IntPlainText intPlainText = null;
                
  
        @ASN1Element ( name = "prestoredTextID", isOptional =  false , hasTag =  true, tag = 3 , hasDefaultValue =  false  )
    
	private PrestoredTextID prestoredTextID = null;
                
  
        @ASN1Element ( name = "dTMFPrestoredTextID", isOptional =  false , hasTag =  true, tag = 4 , hasDefaultValue =  false  )
    
	private DTMFPrestoredTextID dTMFPrestoredTextID = null;
                
  
        @ASN1Element ( name = "intPrestoredTextID", isOptional =  false , hasTag =  true, tag = 5 , hasDefaultValue =  false  )
    
	private IntPrestoredTextID intPrestoredTextID = null;
                
  
        @ASN1Element ( name = "announceElement", isOptional =  false , hasTag =  true, tag = 6 , hasDefaultValue =  false  )
    
	private AnnounceElement announceElement = null;
                
  
        @ASN1Element ( name = "dTMFAnnounceElement", isOptional =  false , hasTag =  true, tag = 7 , hasDefaultValue =  false  )
    
	private DTMFAnnounceElement dTMFAnnounceElement = null;
                
  
        @ASN1Element ( name = "intAnnounceElement", isOptional =  false , hasTag =  true, tag = 8 , hasDefaultValue =  false  )
    
	private IntAnnounceElement intAnnounceElement = null;
                
  
        
        public PlainText getPlainText () {
            return this.plainText;
        }

        public boolean isPlainTextSelected () {
            return this.plainText != null;
        }

        private void setPlainText (PlainText value) {
            this.plainText = value;
        }

        
        public void selectPlainText (PlainText value) {
            this.plainText = value;
            
                    setDTMFPlainText(null);
                
                    setIntPlainText(null);
                
                    setPrestoredTextID(null);
                
                    setDTMFPrestoredTextID(null);
                
                    setIntPrestoredTextID(null);
                
                    setAnnounceElement(null);
                
                    setDTMFAnnounceElement(null);
                
                    setIntAnnounceElement(null);
                            
        }

        
  
        
        public DTMFPlainText getDTMFPlainText () {
            return this.dTMFPlainText;
        }

        public boolean isDTMFPlainTextSelected () {
            return this.dTMFPlainText != null;
        }

        private void setDTMFPlainText (DTMFPlainText value) {
            this.dTMFPlainText = value;
        }

        
        public void selectDTMFPlainText (DTMFPlainText value) {
            this.dTMFPlainText = value;
            
                    setPlainText(null);
                
                    setIntPlainText(null);
                
                    setPrestoredTextID(null);
                
                    setDTMFPrestoredTextID(null);
                
                    setIntPrestoredTextID(null);
                
                    setAnnounceElement(null);
                
                    setDTMFAnnounceElement(null);
                
                    setIntAnnounceElement(null);
                            
        }

        
  
        
        public IntPlainText getIntPlainText () {
            return this.intPlainText;
        }

        public boolean isIntPlainTextSelected () {
            return this.intPlainText != null;
        }

        private void setIntPlainText (IntPlainText value) {
            this.intPlainText = value;
        }

        
        public void selectIntPlainText (IntPlainText value) {
            this.intPlainText = value;
            
                    setPlainText(null);
                
                    setDTMFPlainText(null);
                
                    setPrestoredTextID(null);
                
                    setDTMFPrestoredTextID(null);
                
                    setIntPrestoredTextID(null);
                
                    setAnnounceElement(null);
                
                    setDTMFAnnounceElement(null);
                
                    setIntAnnounceElement(null);
                            
        }

        
  
        
        public PrestoredTextID getPrestoredTextID () {
            return this.prestoredTextID;
        }

        public boolean isPrestoredTextIDSelected () {
            return this.prestoredTextID != null;
        }

        private void setPrestoredTextID (PrestoredTextID value) {
            this.prestoredTextID = value;
        }

        
        public void selectPrestoredTextID (PrestoredTextID value) {
            this.prestoredTextID = value;
            
                    setPlainText(null);
                
                    setDTMFPlainText(null);
                
                    setIntPlainText(null);
                
                    setDTMFPrestoredTextID(null);
                
                    setIntPrestoredTextID(null);
                
                    setAnnounceElement(null);
                
                    setDTMFAnnounceElement(null);
                
                    setIntAnnounceElement(null);
                            
        }

        
  
        
        public DTMFPrestoredTextID getDTMFPrestoredTextID () {
            return this.dTMFPrestoredTextID;
        }

        public boolean isDTMFPrestoredTextIDSelected () {
            return this.dTMFPrestoredTextID != null;
        }

        private void setDTMFPrestoredTextID (DTMFPrestoredTextID value) {
            this.dTMFPrestoredTextID = value;
        }

        
        public void selectDTMFPrestoredTextID (DTMFPrestoredTextID value) {
            this.dTMFPrestoredTextID = value;
            
                    setPlainText(null);
                
                    setDTMFPlainText(null);
                
                    setIntPlainText(null);
                
                    setPrestoredTextID(null);
                
                    setIntPrestoredTextID(null);
                
                    setAnnounceElement(null);
                
                    setDTMFAnnounceElement(null);
                
                    setIntAnnounceElement(null);
                            
        }

        
  
        
        public IntPrestoredTextID getIntPrestoredTextID () {
            return this.intPrestoredTextID;
        }

        public boolean isIntPrestoredTextIDSelected () {
            return this.intPrestoredTextID != null;
        }

        private void setIntPrestoredTextID (IntPrestoredTextID value) {
            this.intPrestoredTextID = value;
        }

        
        public void selectIntPrestoredTextID (IntPrestoredTextID value) {
            this.intPrestoredTextID = value;
            
                    setPlainText(null);
                
                    setDTMFPlainText(null);
                
                    setIntPlainText(null);
                
                    setPrestoredTextID(null);
                
                    setDTMFPrestoredTextID(null);
                
                    setAnnounceElement(null);
                
                    setDTMFAnnounceElement(null);
                
                    setIntAnnounceElement(null);
                            
        }

        
  
        
        public AnnounceElement getAnnounceElement () {
            return this.announceElement;
        }

        public boolean isAnnounceElementSelected () {
            return this.announceElement != null;
        }

        private void setAnnounceElement (AnnounceElement value) {
            this.announceElement = value;
        }

        
        public void selectAnnounceElement (AnnounceElement value) {
            this.announceElement = value;
            
                    setPlainText(null);
                
                    setDTMFPlainText(null);
                
                    setIntPlainText(null);
                
                    setPrestoredTextID(null);
                
                    setDTMFPrestoredTextID(null);
                
                    setIntPrestoredTextID(null);
                
                    setDTMFAnnounceElement(null);
                
                    setIntAnnounceElement(null);
                            
        }

        
  
        
        public DTMFAnnounceElement getDTMFAnnounceElement () {
            return this.dTMFAnnounceElement;
        }

        public boolean isDTMFAnnounceElementSelected () {
            return this.dTMFAnnounceElement != null;
        }

        private void setDTMFAnnounceElement (DTMFAnnounceElement value) {
            this.dTMFAnnounceElement = value;
        }

        
        public void selectDTMFAnnounceElement (DTMFAnnounceElement value) {
            this.dTMFAnnounceElement = value;
            
                    setPlainText(null);
                
                    setDTMFPlainText(null);
                
                    setIntPlainText(null);
                
                    setPrestoredTextID(null);
                
                    setDTMFPrestoredTextID(null);
                
                    setIntPrestoredTextID(null);
                
                    setAnnounceElement(null);
                
                    setIntAnnounceElement(null);
                            
        }

        
  
        
        public IntAnnounceElement getIntAnnounceElement () {
            return this.intAnnounceElement;
        }

        public boolean isIntAnnounceElementSelected () {
            return this.intAnnounceElement != null;
        }

        private void setIntAnnounceElement (IntAnnounceElement value) {
            this.intAnnounceElement = value;
        }

        
        public void selectIntAnnounceElement (IntAnnounceElement value) {
            this.intAnnounceElement = value;
            
                    setPlainText(null);
                
                    setDTMFPlainText(null);
                
                    setIntPlainText(null);
                
                    setPrestoredTextID(null);
                
                    setDTMFPrestoredTextID(null);
                
                    setIntPrestoredTextID(null);
                
                    setAnnounceElement(null);
                
                    setDTMFAnnounceElement(null);
                            
        }

        
  

	    public void initWithDefaults() {
	    }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(TextElement.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }


    }
            