
package com.agnity.ain.asngenerated;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1BoxedType ( name = "TimerUpdated" )
    public class TimerUpdated implements IASN1PreparedElement {
                
        

    @ASN1PreparedElement
    @ASN1Enum (
        name = "TimerUpdatedEnumType"
    )
    public static class TimerUpdatedEnumType implements IASN1PreparedElement {        
        public enum EnumType {
            
            @ASN1EnumItem ( name = "success", hasTag = true , tag = 0 )
            success , 
            @ASN1EnumItem ( name = "failure", hasTag = true , tag = 1 )
            failure , 
            @ASN1EnumItem ( name = "transactionalreadyclosed", hasTag = true , tag = 2 )
            transactionalreadyclosed , 
        }
        
        private EnumType value;
        private Integer integerForm;
        
        public EnumType getValue() {
            return this.value;
        }
        
        public void setValue(EnumType value) {
            this.value = value;
        }
        
        public Integer getIntegerForm() {
            return integerForm;
        }
        
        public void setIntegerForm(Integer value) {
            integerForm = value;
        }

	    public void initWithDefaults() {
	    }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(TimerUpdatedEnumType.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

    }
                
        @ASN1Element ( name = "TimerUpdated", isOptional =  false , hasTag =  true, tag = 167 , hasDefaultValue =  false  )
    
        private TimerUpdatedEnumType  value;        

        
        
        public TimerUpdated () {
        }
        
        
        
        public void setValue(TimerUpdatedEnumType value) {
            this.value = value;
        }
        
        
        
        public TimerUpdatedEnumType getValue() {
            return this.value;
        }            
        

	    public void initWithDefaults() {
	    }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(TimerUpdated.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            