
package com.agnity.ain.asngenerated;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Sequence ( name = "UpdateGroup6", isSet = false )
    public class UpdateGroup6 implements IASN1PreparedElement {
            
        @ASN1Element ( name = "service6", isOptional =  false , hasTag =  true, tag = 1 , hasDefaultValue =  false  )
    
	private Service6 service6 = null;
                
  
        @ASN1Element ( name = "action6", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private Action6 action6 = null;
                
  
        
        public Service6 getService6 () {
            return this.service6;
        }

        

        public void setService6 (Service6 value) {
            this.service6 = value;
        }
        
  
        
        public Action6 getAction6 () {
            return this.action6;
        }

        

        public void setAction6 (Action6 value) {
            this.action6 = value;
        }
        
  
                    
        
        public void initWithDefaults() {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(UpdateGroup6.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            