package com.agnity.cap.v2.datatypes.enumType;

public enum NumberQualifierIndicatorCapV2Enum {
	
	RESERVED_DIALLEDDIGITS(0),ADDITIONAL_CALLEDNUMBER(1), RESERVED_SUPPLEMENTAL_UMBER_FAILEDNETWORK(2),
	RESERVED_SUPPLEMENTALNUMBER_NOTSCREENED(3),RESERVED_REDIRECTINGTERMINATINGNUMBER(4),
	ADDITIONAL_CONNECTEDNUMBER(5),ADDITIONAL_CALLINGPARTYNUMBER(6),
	RESERVED_ADDITIONALORIGINALCALLEDNUMBER(7),RESERVED_ADDITIONALREDIRECTINGNUMBER(8)
	,RESERVED_FORADDITIONALREDIRECTINGNUMBER(9),RESERVED_USEDIN1992VERSION(10);
//	,SPARE(11-127),RESERVEDFORNATIONALUSE(128-254)	,
//	RESERVEDFOREXPANSION(255);
	
	private int code;
	
	private NumberQualifierIndicatorCapV2Enum(int code){
		this.code = code;
	}
	
	public int getcode()
	{
		return code;
	}
		
   public static NumberQualifierIndicatorCapV2Enum getValue(int tag){
		switch (tag) {
		case 0: return RESERVED_DIALLEDDIGITS; 
		case 1: return ADDITIONAL_CALLEDNUMBER; 
		case 2: return RESERVED_SUPPLEMENTAL_UMBER_FAILEDNETWORK; 
		case 3: return RESERVED_SUPPLEMENTALNUMBER_NOTSCREENED;
		case 4: return RESERVED_REDIRECTINGTERMINATINGNUMBER; 
		case 5: return ADDITIONAL_CONNECTEDNUMBER; 
		case 6: return ADDITIONAL_CALLINGPARTYNUMBER;
		case 7: return RESERVED_ADDITIONALORIGINALCALLEDNUMBER;
		case 8: return RESERVED_ADDITIONALREDIRECTINGNUMBER;
		case 9: return RESERVED_FORADDITIONALREDIRECTINGNUMBER;
		case 10: return RESERVED_USEDIN1992VERSION;
		
		default: return null;
		}
	}
  /* public static int gettag(NumberQualifierIndicatorEnum NQIE)
   {
	   switch (NQIE) {
		case RESERVED_DIALLEDDIGITS: return 0; 
		case ADDITIONAL_CALLEDNUMBER: return 1; 
		case RESERVED_SUPPLEMENTAL_UMBER_FAILEDNETWORK: return 2; 
		case RESERVED_SUPPLEMENTALNUMBER_NOTSCREENED: return 3;
		case RESERVED_REDIRECTINGTERMINATINGNUMBER: return 4; 
		case ADDITIONAL_CONNECTEDNUMBER: return 5; 
		case ADDITIONAL_CALLINGPARTYNUMBER: return 6;
		case RESERVED_ADDITIONALORIGINALCALLEDNUMBER: return 7;
		case RESERVED_ADDITIONALREDIRECTINGNUMBER: return 8;
		case RESERVED_FORADDITIONALREDIRECTINGNUMBER: return 9;
		case RESERVED_USEDIN1992VERSION: return 10;
		
		default: return 00;
		} 
   }*/
}
