
package com.agnity.map.asngenerated;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Enum (
        name = "AdditionalRequestedCAMEL_SubscriptionInfo"
    )
    public class AdditionalRequestedCAMEL_SubscriptionInfo implements IASN1PreparedElement {        
        public enum EnumType {
            
            @ASN1EnumItem ( name = "mt-sms-CSI", hasTag = true , tag = 0 )
            mt_sms_CSI , 
            @ASN1EnumItem ( name = "mg-csi", hasTag = true , tag = 1 )
            mg_csi , 
            @ASN1EnumItem ( name = "o-IM-CSI", hasTag = true , tag = 2 )
            o_IM_CSI , 
            @ASN1EnumItem ( name = "d-IM-CSI", hasTag = true , tag = 3 )
            d_IM_CSI , 
            @ASN1EnumItem ( name = "vt-IM-CSI", hasTag = true , tag = 4 )
            vt_IM_CSI , 
        }
        
        private EnumType value;
        private Integer integerForm;
        
        public EnumType getValue() {
            return this.value;
        }
        
        public void setValue(EnumType value) {
            this.value = value;
        }
        
        public Integer getIntegerForm() {
            return integerForm;
        }
        
        public void setIntegerForm(Integer value) {
            integerForm = value;
        }

	    public void initWithDefaults() {
	    }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(AdditionalRequestedCAMEL_SubscriptionInfo.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }


    }
            