
package com.agnity.map.asngenerated;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Sequence ( name = "AnyTimeModificationRes", isSet = false )
    public class AnyTimeModificationRes implements IASN1PreparedElement {
            
        @ASN1Element ( name = "ss-InfoFor-CSE", isOptional =  true , hasTag =  true, tag = 0 , hasDefaultValue =  false  )
    
	private Ext_SS_InfoFor_CSE ss_InfoFor_CSE = null;
                
  
        @ASN1Element ( name = "camel-SubscriptionInfo", isOptional =  true , hasTag =  true, tag = 1 , hasDefaultValue =  false  )
    
	private CAMEL_SubscriptionInfo camel_SubscriptionInfo = null;
                
  
        @ASN1Element ( name = "extensionContainer", isOptional =  true , hasTag =  true, tag = 2 , hasDefaultValue =  false  )
    
	private ExtensionContainer extensionContainer = null;
                
  
        @ASN1Element ( name = "odb-Info", isOptional =  true , hasTag =  true, tag = 3 , hasDefaultValue =  false  )
    
	private ODB_Info odb_Info = null;
                
  
        
        public Ext_SS_InfoFor_CSE getSs_InfoFor_CSE () {
            return this.ss_InfoFor_CSE;
        }

        
        public boolean isSs_InfoFor_CSEPresent () {
            return this.ss_InfoFor_CSE != null;
        }
        

        public void setSs_InfoFor_CSE (Ext_SS_InfoFor_CSE value) {
            this.ss_InfoFor_CSE = value;
        }
        
  
        
        public CAMEL_SubscriptionInfo getCamel_SubscriptionInfo () {
            return this.camel_SubscriptionInfo;
        }

        
        public boolean isCamel_SubscriptionInfoPresent () {
            return this.camel_SubscriptionInfo != null;
        }
        

        public void setCamel_SubscriptionInfo (CAMEL_SubscriptionInfo value) {
            this.camel_SubscriptionInfo = value;
        }
        
  
        
        public ExtensionContainer getExtensionContainer () {
            return this.extensionContainer;
        }

        
        public boolean isExtensionContainerPresent () {
            return this.extensionContainer != null;
        }
        

        public void setExtensionContainer (ExtensionContainer value) {
            this.extensionContainer = value;
        }
        
  
        
        public ODB_Info getOdb_Info () {
            return this.odb_Info;
        }

        
        public boolean isOdb_InfoPresent () {
            return this.odb_Info != null;
        }
        

        public void setOdb_Info (ODB_Info value) {
            this.odb_Info = value;
        }
        
  
                    
        
        public void initWithDefaults() {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(AnyTimeModificationRes.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            