
package com.agnity.map.asngenerated;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Sequence ( name = "CSG_SubscriptionData", isSet = false )
    public class CSG_SubscriptionData implements IASN1PreparedElement {
            
        @ASN1Element ( name = "csg-Id", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private CSG_Id csg_Id = null;
                
  
        @ASN1Element ( name = "expirationDate", isOptional =  true , hasTag =  false  , hasDefaultValue =  false  )
    
	private Time expirationDate = null;
                
  
        @ASN1Element ( name = "extensionContainer", isOptional =  true , hasTag =  false  , hasDefaultValue =  false  )
    
	private ExtensionContainer extensionContainer = null;
                
  
        
        public CSG_Id getCsg_Id () {
            return this.csg_Id;
        }

        

        public void setCsg_Id (CSG_Id value) {
            this.csg_Id = value;
        }
        
  
        
        public Time getExpirationDate () {
            return this.expirationDate;
        }

        
        public boolean isExpirationDatePresent () {
            return this.expirationDate != null;
        }
        

        public void setExpirationDate (Time value) {
            this.expirationDate = value;
        }
        
  
        
        public ExtensionContainer getExtensionContainer () {
            return this.extensionContainer;
        }

        
        public boolean isExtensionContainerPresent () {
            return this.extensionContainer != null;
        }
        

        public void setExtensionContainer (ExtensionContainer value) {
            this.extensionContainer = value;
        }
        
  
                    
        
        public void initWithDefaults() {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(CSG_SubscriptionData.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            