
package com.agnity.map.asngenerated;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Sequence ( name = "DestinationNumberCriteria", isSet = false )
    public class DestinationNumberCriteria implements IASN1PreparedElement {
            
        @ASN1Element ( name = "matchType", isOptional =  false , hasTag =  true, tag = 0 , hasDefaultValue =  false  )
    
	private MatchType matchType = null;
                
  
        @ASN1Element ( name = "destinationNumberList", isOptional =  true , hasTag =  true, tag = 1 , hasDefaultValue =  false  )
    
	private DestinationNumberList destinationNumberList = null;
                
  
        @ASN1Element ( name = "destinationNumberLengthList", isOptional =  true , hasTag =  true, tag = 2 , hasDefaultValue =  false  )
    
	private DestinationNumberLengthList destinationNumberLengthList = null;
                
  
        
        public MatchType getMatchType () {
            return this.matchType;
        }

        

        public void setMatchType (MatchType value) {
            this.matchType = value;
        }
        
  
        
        public DestinationNumberList getDestinationNumberList () {
            return this.destinationNumberList;
        }

        
        public boolean isDestinationNumberListPresent () {
            return this.destinationNumberList != null;
        }
        

        public void setDestinationNumberList (DestinationNumberList value) {
            this.destinationNumberList = value;
        }
        
  
        
        public DestinationNumberLengthList getDestinationNumberLengthList () {
            return this.destinationNumberLengthList;
        }

        
        public boolean isDestinationNumberLengthListPresent () {
            return this.destinationNumberLengthList != null;
        }
        

        public void setDestinationNumberLengthList (DestinationNumberLengthList value) {
            this.destinationNumberLengthList = value;
        }
        
  
                    
        
        public void initWithDefaults() {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(DestinationNumberCriteria.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            