
package com.agnity.map.asngenerated;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Sequence ( name = "ExternalSignalInfo", isSet = false )
    public class ExternalSignalInfo implements IASN1PreparedElement {
            
        @ASN1Element ( name = "protocolId", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private ProtocolId protocolId = null;
                
  
        @ASN1Element ( name = "signalInfo", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private SignalInfo signalInfo = null;
                
  
        @ASN1Element ( name = "extensionContainer", isOptional =  true , hasTag =  false  , hasDefaultValue =  false  )
    
	private ExtensionContainer extensionContainer = null;
                
  
        
        public ProtocolId getProtocolId () {
            return this.protocolId;
        }

        

        public void setProtocolId (ProtocolId value) {
            this.protocolId = value;
        }
        
  
        
        public SignalInfo getSignalInfo () {
            return this.signalInfo;
        }

        

        public void setSignalInfo (SignalInfo value) {
            this.signalInfo = value;
        }
        
  
        
        public ExtensionContainer getExtensionContainer () {
            return this.extensionContainer;
        }

        
        public boolean isExtensionContainerPresent () {
            return this.extensionContainer != null;
        }
        

        public void setExtensionContainer (ExtensionContainer value) {
            this.extensionContainer = value;
        }
        
  
                    
        
        public void initWithDefaults() {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(ExternalSignalInfo.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            