
package com.agnity.map.asngenerated;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1BoxedType ( name = "MobilityTriggers" )
    public class MobilityTriggers implements IASN1PreparedElement {
                
            @ASN1ValueRangeConstraint ( 
		
		min = 1L, 
		
		max = 10L 
		
	   )
	   
            @ASN1SequenceOf( name = "MobilityTriggers" , isSetOf = false)
	    private java.util.Collection<MM_Code> value = null; 
    
            public MobilityTriggers () {
            }
        
            public MobilityTriggers ( java.util.Collection<MM_Code> value ) {
                setValue(value);
            }
                        
            public void setValue(java.util.Collection<MM_Code> value) {
                this.value = value;
            }
            
            public java.util.Collection<MM_Code> getValue() {
                return this.value;
            }            
            
            public void initValue() {
                setValue(new java.util.LinkedList<MM_Code>()); 
            }
            
            public void add(MM_Code item) {
                value.add(item);
            }

	    public void initWithDefaults() {
	    }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(MobilityTriggers.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }


    }
            