
package com.agnity.map.asngenerated;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Choice ( name = "RoutingInfo" )
    public class RoutingInfo implements IASN1PreparedElement {
            
        @ASN1Element ( name = "roamingNumber", isOptional =  true , hasTag =  false  , hasDefaultValue =  false  )
    
	private ISDN_AddressString roamingNumber = null;
                
  
        @ASN1Element ( name = "forwardingData", isOptional =  true , hasTag =  false  , hasDefaultValue =  false  )
    
	private ForwardingData forwardingData = null;
                
  
        
        public ISDN_AddressString getRoamingNumber () {
            return this.roamingNumber;
        }

        public boolean isRoamingNumberSelected () {
            return this.roamingNumber != null;
        }

        private void setRoamingNumber (ISDN_AddressString value) {
            this.roamingNumber = value;
        }

        
        public void selectRoamingNumber (ISDN_AddressString value) {
            this.roamingNumber = value;
            
                    setForwardingData(null);
                            
        }

        
  
        
        public ForwardingData getForwardingData () {
            return this.forwardingData;
        }

        public boolean isForwardingDataSelected () {
            return this.forwardingData != null;
        }

        private void setForwardingData (ForwardingData value) {
            this.forwardingData = value;
        }

        
        public void selectForwardingData (ForwardingData value) {
            this.forwardingData = value;
            
                    setRoamingNumber(null);
                            
        }

        
  

	    public void initWithDefaults() {
	    }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(RoutingInfo.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }


    }
            