
package com.agnity.map.asngenerated;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Choice ( name = "SubscriberIdentity" )
    public class SubscriberIdentity implements IASN1PreparedElement {
            
        @ASN1Element ( name = "imsi", isOptional =  false , hasTag =  true, tag = 0 , hasDefaultValue =  false  )
    
	private IMSI imsi = null;
                
  
        @ASN1Element ( name = "msisdn", isOptional =  false , hasTag =  true, tag = 1 , hasDefaultValue =  false  )
    
	private ISDN_AddressString msisdn = null;
                
  
        
        public IMSI getImsi () {
            return this.imsi;
        }

        public boolean isImsiSelected () {
            return this.imsi != null;
        }

        private void setImsi (IMSI value) {
            this.imsi = value;
        }

        
        public void selectImsi (IMSI value) {
            this.imsi = value;
            
                    setMsisdn(null);
                            
        }

        
  
        
        public ISDN_AddressString getMsisdn () {
            return this.msisdn;
        }

        public boolean isMsisdnSelected () {
            return this.msisdn != null;
        }

        private void setMsisdn (ISDN_AddressString value) {
            this.msisdn = value;
        }

        
        public void selectMsisdn (ISDN_AddressString value) {
            this.msisdn = value;
            
                    setImsi(null);
                            
        }

        
  

	    public void initWithDefaults() {
	    }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(SubscriberIdentity.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }


    }
            