
package com.agnity.map.asngenerated;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Enum (
        name = "UnavailabilityCause"
    )
    public class UnavailabilityCause implements IASN1PreparedElement {        
        public enum EnumType {
            
            @ASN1EnumItem ( name = "bearerServiceNotProvisioned", hasTag = true , tag = 1 )
            bearerServiceNotProvisioned , 
            @ASN1EnumItem ( name = "teleserviceNotProvisioned", hasTag = true , tag = 2 )
            teleserviceNotProvisioned , 
            @ASN1EnumItem ( name = "absentSubscriber", hasTag = true , tag = 3 )
            absentSubscriber , 
            @ASN1EnumItem ( name = "busySubscriber", hasTag = true , tag = 4 )
            busySubscriber , 
            @ASN1EnumItem ( name = "callBarred", hasTag = true , tag = 5 )
            callBarred , 
            @ASN1EnumItem ( name = "cug-Reject", hasTag = true , tag = 6 )
            cug_Reject , 
        }
        
        private EnumType value;
        private Integer integerForm;
        
        public EnumType getValue() {
            return this.value;
        }
        
        public void setValue(EnumType value) {
            this.value = value;
        }
        
        public Integer getIntegerForm() {
            return integerForm;
        }
        
        public void setIntegerForm(Integer value) {
            integerForm = value;
        }

	    public void initWithDefaults() {
	    }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(UnavailabilityCause.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }


    }
            