//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b26-ea3 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.12.10 at 09:51:58 AM CST 
//


package com.genband.tcap.xjc;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlRootElement;
import com.genband.tcap.xjc.BeginReqEventType;
import com.genband.tcap.xjc.ContinueReqEventType;
import com.genband.tcap.xjc.DialogueReqEventType;
import com.genband.tcap.xjc.EndReqEventType;
import com.genband.tcap.xjc.UnidirectionalReqEventType;
import com.genband.tcap.xjc.UserAbortReqEventType;


/**
 * <p>Java class for dialogue-req-event-type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="dialogue-req-event-type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="user-abort-req-event" type="{}user-abort-req-event-type"/>
 *         &lt;element name="unidirectional-req-event" type="{}unidirectional-req-event-type"/>
 *         &lt;element name="continue-req-event" type="{}continue-req-event-type"/>
 *         &lt;element name="begin-req-event" type="{}begin-req-event-type"/>
 *         &lt;element name="end-req-event" type="{}end-req-event-type"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "dialogue-req-event-type", propOrder = {
    "userAbortReqEvent",
    "unidirectionalReqEvent",
    "continueReqEvent",
    "beginReqEvent",
    "endReqEvent"
})
public class DialogueReqEventType extends DialogueReqEventInterface {

    @XmlElement(name = "user-abort-req-event")
    protected UserAbortReqEventType userAbortReqEvent;
    @XmlElement(name = "unidirectional-req-event")
    protected UnidirectionalReqEventType unidirectionalReqEvent;
    @XmlElement(name = "continue-req-event")
    protected ContinueReqEventType continueReqEvent;
    @XmlElement(name = "begin-req-event")
    protected BeginReqEventType beginReqEvent;
    @XmlElement(name = "end-req-event")
    protected EndReqEventType endReqEvent;

    /**
     * Gets the value of the userAbortReqEvent property.
     * 
     * @return
     *     possible object is
     *     {@link UserAbortReqEventType }
     *     
     */
    public UserAbortReqEventType getUserAbortReqEvent() {
        return userAbortReqEvent;
    }

    /**
     * Sets the value of the userAbortReqEvent property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserAbortReqEventType }
     *     
     */
    public void setUserAbortReqEvent(UserAbortReqEventType value) {
        this.userAbortReqEvent = value;
    }

    /**
     * Gets the value of the unidirectionalReqEvent property.
     * 
     * @return
     *     possible object is
     *     {@link UnidirectionalReqEventType }
     *     
     */
    public UnidirectionalReqEventType getUnidirectionalReqEvent() {
        return unidirectionalReqEvent;
    }

    /**
     * Sets the value of the unidirectionalReqEvent property.
     * 
     * @param value
     *     allowed object is
     *     {@link UnidirectionalReqEventType }
     *     
     */
    public void setUnidirectionalReqEvent(UnidirectionalReqEventType value) {
        this.unidirectionalReqEvent = value;
    }

    /**
     * Gets the value of the continueReqEvent property.
     * 
     * @return
     *     possible object is
     *     {@link ContinueReqEventType }
     *     
     */
    public ContinueReqEventType getContinueReqEvent() {
        return continueReqEvent;
    }

    /**
     * Sets the value of the continueReqEvent property.
     * 
     * @param value
     *     allowed object is
     *     {@link ContinueReqEventType }
     *     
     */
    public void setContinueReqEvent(ContinueReqEventType value) {
        this.continueReqEvent = value;
    }

    /**
     * Gets the value of the beginReqEvent property.
     * 
     * @return
     *     possible object is
     *     {@link BeginReqEventType }
     *     
     */
    public BeginReqEventType getBeginReqEvent() {
        return beginReqEvent;
    }

    /**
     * Sets the value of the beginReqEvent property.
     * 
     * @param value
     *     allowed object is
     *     {@link BeginReqEventType }
     *     
     */
    public void setBeginReqEvent(BeginReqEventType value) {
        this.beginReqEvent = value;
    }

    /**
     * Gets the value of the endReqEvent property.
     * 
     * @return
     *     possible object is
     *     {@link EndReqEventType }
     *     
     */
    public EndReqEventType getEndReqEvent() {
        return endReqEvent;
    }

    /**
     * Sets the value of the endReqEvent property.
     * 
     * @param value
     *     allowed object is
     *     {@link EndReqEventType }
     *     
     */
    public void setEndReqEvent(EndReqEventType value) {
        this.endReqEvent = value;
    }

}
