//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b26-ea3 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.12.10 at 09:51:58 AM CST 
//


package com.genband.tcap.xjc;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.adapters.HexBinaryAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import com.genband.tcap.xjc.ComponentIndEventType;
import com.genband.tcap.xjc.DialoguePortionType;
import com.genband.tcap.xjc.NoticeIndEventType;
import com.genband.tcap.xjc.SccpUserAddressType;


/**
 * <p>Java class for notice-ind-event-type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="notice-ind-event-type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;group ref="{}dialogue-ind-event-group"/>
 *         &lt;element name="destination-address" type="{}sccp-user-address-type" minOccurs="0"/>
 *         &lt;element name="originating-address" type="{}sccp-user-address-type" minOccurs="0"/>
 *         &lt;element name="report-cause" type="{http://www.w3.org/2001/XMLSchema}hexBinary"/>
 *       &lt;/sequence>
 *       &lt;attribute name="dialogue-id" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "notice-ind-event-type", propOrder = {
    "dialoguePortion",
    "componentIndEvent",
    "destinationAddress",
    "originatingAddress",
    "reportCause"
})
public class NoticeIndEventType extends NoticeIndEventInterface {

    @XmlElement(name = "dialogue-portion")
    protected DialoguePortionType dialoguePortion;
    @XmlElement(name = "component-ind-event")
    protected List<ComponentIndEventType> componentIndEvent;
    @XmlElement(name = "destination-address")
    protected SccpUserAddressType destinationAddress;
    @XmlElement(name = "originating-address")
    protected SccpUserAddressType originatingAddress;
    @XmlElement(name = "report-cause", type = String.class)
    @XmlJavaTypeAdapter(HexBinaryAdapter.class)
    protected byte[] reportCause;
    @XmlAttribute(name = "dialogue-id")
    protected BigInteger dialogueId;

    /**
     * Gets the value of the dialoguePortion property.
     * 
     * @return
     *     possible object is
     *     {@link DialoguePortionType }
     *     
     */
    public DialoguePortionType getDialoguePortion() {
        return dialoguePortion;
    }

    /**
     * Sets the value of the dialoguePortion property.
     * 
     * @param value
     *     allowed object is
     *     {@link DialoguePortionType }
     *     
     */
    public void setDialoguePortion(DialoguePortionType value) {
        this.dialoguePortion = value;
    }

    /**
     * Gets the value of the componentIndEvent property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the componentIndEvent property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getComponentIndEvent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ComponentIndEventType }
     * 
     * 
     */
    public List<ComponentIndEventType> getComponentIndEvent() {
        if (componentIndEvent == null) {
            componentIndEvent = new ArrayList<ComponentIndEventType>();
        }
        return this.componentIndEvent;
    }

    /**
     * Gets the value of the destinationAddress property.
     * 
     * @return
     *     possible object is
     *     {@link SccpUserAddressType }
     *     
     */
    public SccpUserAddressType getDestinationAddress() {
        return destinationAddress;
    }

    /**
     * Sets the value of the destinationAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link SccpUserAddressType }
     *     
     */
    public void setDestinationAddress(SccpUserAddressType value) {
        this.destinationAddress = value;
    }

    /**
     * Gets the value of the originatingAddress property.
     * 
     * @return
     *     possible object is
     *     {@link SccpUserAddressType }
     *     
     */
    public SccpUserAddressType getOriginatingAddress() {
        return originatingAddress;
    }

    /**
     * Sets the value of the originatingAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link SccpUserAddressType }
     *     
     */
    public void setOriginatingAddress(SccpUserAddressType value) {
        this.originatingAddress = value;
    }

    /**
     * Gets the value of the reportCause property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public byte[] getReportCause() {
        return reportCause;
    }

    /**
     * Sets the value of the reportCause property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReportCause(byte[] value) {
        this.reportCause = ((byte[]) value);
    }

    /**
     * Gets the value of the dialogueId property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getDialogueId() {
        return dialogueId;
    }

    /**
     * Sets the value of the dialogueId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setDialogueId(BigInteger value) {
        this.dialogueId = value;
    }

}
